### ISSUE TITLE
Enable academic staff for mediated SPEC request type

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/sul-requests#1002]
- [x] Wording change needed in form to add in academic staff to the eligibility statement on the Intro page:

Under Who can visit the Reading Room?

Professors (including emeriti), academic staff, post-docs, graduate students, fellows, and Stanford Visiting Scholars with a current Stanford ID card.
To maintain social distancing, the Reading Room will admit one researcher per table in 2-hour blocks.

- [x] add affiliation group stanford:staff:academic to the list of eligible priv groups

**Comment by jvine** [comment]
- [ ] and add "academic staff" to the eligibility list on the failure page, too.
