### ISSUE TITLE
Add eligibility overlay for RUMSEY

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/sul-requests#1008]

**Comment by jvine** [comment]
Change to title and first line of text.

```
    <h1>David Rumsey Map Center request</h1>
    <p>Restricted items are made available for use in the Special Collections Reading Room of Green Library.</p>
```

<img width="611" alt="Screen Shot 2020-06-22 at 4 27 01 PM" src="https://user-images.githubusercontent.com/6945691/85344776-798b5780-b4a5-11ea-9f7e-52cdb9db2c3d.png">
