### ISSUE TITLE
Add eligibility overlay for Art Locked Stacks

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/sul-requests#1009]

**Comment by jvine** [comment]
Change to title and first line of text.

```
    <h1>Art Locked Stacks request</h1>
    <p>Restricted items are made available for use in the Special Collections Reading Room of Green Library.</p>
```

<img width="609" alt="Screen Shot 2020-06-22 at 4 27 14 PM" src="https://user-images.githubusercontent.com/6945691/85344720-53fe4e00-b4a5-11ea-80e3-74a0c2c0efd0.png">
