### ISSUE TITLE
Replace proxy user info look up with a symws call

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/sul-requests#1037]
We're getting information about whether a user is a proxy/sponsor using a call to the proxy cgi-bin script. Since we know how to do this with symws, use the SymphonyClient (From ####) to do that instead.

**Comment by mejackreed** [comment]
See https://github.com/sul-dlss/sul-requests/pull/1041/commits/c07a16f2597d55bfdcba738278f9a053128c04f7
