### ISSUE TITLE
Scan requests shouldn't email SYM error 722 "user already has hold on this item" to requesting user

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/sul-requests#1085]
For SCAN requests only...

If a user is placing a Scan request, and the SYM response is "user already has a hold on this material", we should not register that as an error state on the request status page or alert the user via email.  The user should get the approval_status_for_scan mailer.

Example in requests-stage: https://requests-stage.stanford.edu/scans/12/status

**Comment by jkeck** [comment]
@saseestone when you get a chance, can you try another scan request in stage?

**Comment by saseestone** [comment]
Looks great! User received correct on-screen messaging and approval status mailer.  Thanks!

**Comment by jkeck** [comment]
Closed by cedc037 in #1041
