### ISSUE TITLE
utilize BorrowDirect API more

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/sul-requests#1170]
We're not utilizing the BorrowDirect API as often as we could or should at this time.  My understanding is that we're only utilizing the BD API when the request type = HoldRecall. We haven't assigned a HoldRecall request type since March 2020.
Instead, the vast majority of requests placed are assigned request type = PAGE, even if the item is currently checked out or in another temporary status (like INPROCESS).  The result is that holds are placed on Stanford materials currently checked out (or otherwise unavailable), and we could be getting the materials from BD partners.

Options:
A. do the work to re-enable request type = HoldRecall.  This will take some analysis to determine what/if changes need to be made given the permanent changes made to request type = Page (using enabled Library/Location/ItemType designations). **Note** that we'll likely need to do this work anyway this summer, in preparation for more people being on campus in the Fall and the expansion (or resumption) of more "services". 

B. determine if we should place the BD API in the flow for request type = PAGE. Might require the same analysis described in option A. 

C. something else that is brilliant.

**Comment by saseestone** [comment]
another note about re-enabling request type = HoldRecall - 

We can do it safely now because Symphony can serve as the gatekeeper of recalls. After the BD API check, we'd be placing holds in Symphony that might turn into recalls some-day (and everything would be set up for the Circ people to decide when...)

**Comment by anarchivist** [comment]
This is interrelated with the paging/hold changes we may need to make for fall. We'll know more after the 2021-06-21 LAX meeting.

**Comment by saseestone** [comment]
closing because we enabled request type holdrecall.
