### ISSUE TITLE
Need to handle Symphony message 116 better

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/sul-requests#1175]
We have a report from East Asia staff about SAL3 items requested that don't arrive on campus, particularly when requesting many items from a title with many volumes.  [Request status page from one example](https://requests.stanford.edu/pages/264413/status) reveals that Symphony returned msgcode:116 with message: "The records are currently in use. Please try again later."

In the confirmation email sent to the user, we preface the call number with "Attention:" but that's the only indication that something went wrong AND we don't give the user any ideas about what they should do about the issue.
![image](https://user-images.githubusercontent.com/14897546/118044247-448d2b00-b32b-11eb-8fe0-a4f0c1c5b318.png)

Similarly on the Request status page, we preface with "Attention:" and mark it in red, but again, no indication of what went wrong or what to do.
![image](https://user-images.githubusercontent.com/14897546/118044511-97ff7900-b32b-11eb-95ac-c8ee86048999.png)

This needs design, but at the minimum we should tell the user that the request failed.

**Comment by cbeer** [comment]
It looks like we intend to include error text after the call number, but maybe this particular error doesn't include text in the same way as other failures (or it got dropped/changed with the switch to symws?). 

That said, should we retry Symphony requests that fail in this way? I thought we used to, but maybe the old perl script did a better job blowing up?

**Comment by saseestone** [comment]
I would prefer to retry the requests that fail in this way, but the question I have is how quickly after and how many times before we determine it's a failure.

@shelleydoljack or @dlrueda might be able to help us determine speed and frequency.

**Comment by shelleydoljack** [comment]
I will look into what a retry interval should be or if there are outstanding support tickets from SirsiDynix regarding this.

**Comment by shelleydoljack** [comment]
Current thinking is 2 seconds would be a good interval.

**Comment by saseestone** [comment]
This needs to be prioritized in Access team work
