### ISSUE TITLE
Remove Education from pickup library list 

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/sul-requests#1186]
Because the Education library will be under construction for the next 3-4 years, we need to remove it from the list of eligible pickup libraries.

We won't need to do anything with the PAGE-ED designation, as they won't have any items in that Home Location and know not to add any as long as the building is under construction.  (There is one item in that location currently, and they will modify it to PAGE-GR.)

**Comment by cbeer** [comment]
As I'm reading it, education isn't a current pickup library, right?

**Comment by saseestone** [comment]
Not currently, but it has been in a master list of pickup libraries when a specific pickup library is not specified.  Though, with a quick search, I can't see that list anymore.  Maybe Jessie blitzed it last summer in the all the request work.

So closing this.

**Comment by cbeer** [comment]
👍 ; I think this is (probably) that list:

```
        'ART',
        'BUSINESS',
        'EARTH-SCI',
        'EAST-ASIA',
        'EDUCATION',
        'ENG',
        'GREEN',
        'HOPKINS',
        'LAW',
        'MUSIC',
        'RWC',
        'SCIENCE'
```

but (I think) we're currently using:

```
        'BUSINESS',
        'EAST-ASIA',
        'GREEN',
        'HOPKINS',
        'LAW'
```
