### ISSUE TITLE
Restore pickup library list on 9/7/21 for HoldRecall and Page

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/sul-requests#1205]
We'll need to restore the pickup library list to it's pre-pandemic glory, allowing users the ability to pickup materials from any open campus library.  (Unless we have rules that restrict the pickup - i.e. "PAGE-" locations.) This should apply to both PAGE and HoldREcall request types.

We should plan to update the list on 9/7/21 when campus libraries open.

If there are no restrictions, the following library list should display:
Art & Architecture Library (Bowes)
Business Library
Earth Science Library (Branner)
East Asia Library
Engineering Library
Green Library
Law Library (Crown)
Marine Biology Library (Miller)
Music Library
Science Library (Li and Ma)

**Comment by cbeer** [comment]
Just confirming we're dropping Education (obviously) and RWC, and adding MEDIA-MTXT?

**Comment by saseestone** [comment]
Ack. Good catch Chris.  MEDIA-MTXT shouldn't go in the general list.  We need it as an option for restricted paging though (e.g. PAGE-LP & PAGE-MD and the new PAGE-MM)

Confirming we are dropping Education and RWC for now.
