### ISSUE TITLE
in Rumsey request mediation, can't mark as done

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/sul-requests#1220]
I'm getting an error in the Rumsey mediation space when we try to "mark as done"

![image](https://user-images.githubusercontent.com/14897546/133528527-49eb23b6-ca0f-4aa4-814c-9a3bc93702f1.png)

**Comment by cbeer** [comment]
I think I tracked these down to an older request that was still set up to deliver to SPEC-COLL, but wasn't approved/marked as done until after the new delivery rules went into effect.

I updated the old request in the database and marked it was done.
