### ISSUE TITLE
update email confirmation mailer for mediated page

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/sul-requests#1221]
Now that the Rumsey Map Center is open, we need to update the user confirmation email for mediated pages to make it more generic.

**New body text should be:**
We've received your request for the item(s) below.

What happens now?
1. A librarian will review and approve your request, or contact you.
2. When material is ready for use, we'll send you an email with instructions.
3. On the day of your visit, follow the required health and safety protocols for [library access](https://library.stanford.edu/status)

We also need to remove "Requests are typically approved 1-3 days before your scheduled visit."
And we need to ensure:

-  the contact information under "Questions about your request?" corresponds to the origin library (e.g. Request is for Rumsey materials, so we should have Rumsey library contact info. Art materials = Art contact info. etc.)
- the email is sent from the correct origin library.

**Comment by cbeer** [comment]
Are we removing:

> If you haven’t already, complete COVID-19 Hygiene Best Practices, EHS-2470-WEB before your visit.

**Comment by camillevilla** [comment]
@cbeer I think this still applies for Stanford affiliates. Anyone who can make these requests needs a SUNet ID. This page was recently reviewed and still has a reference to the EHS class	: https://library.stanford.edu/using/access-and-privileges

**Comment by saseestone** [comment]
Confirming that we should leave in "If you haven't already, complete COVID-19..."

for now.

**Comment by saseestone** [comment]
MASSIVE apologies but can we use https://library.stanford.edu/using/access-and-privileges as the url for "library access" instead of https://library.stanford.edu/status
