### ISSUE TITLE
Create a request in Illiad when Scan requests are made

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/sul-requests#123]

**Comment by jgreben** [comment]
These are sample forms in ILLiad that Rose and Alex will see:
![screen shot 2015-05-19 at 12 47 46 pm](https://cloud.githubusercontent.com/assets/3093850/7730719/bdda548a-fed0-11e4-8828-7399038c51ce.png)
![screen shot 2015-05-19 at 12 46 59 pm](https://cloud.githubusercontent.com/assets/3093850/7730720/bddd3c18-fed0-11e4-8b27-85abfcb4063a.png)
