### ISSUE TITLE
Upgrade from Bootstrap 3 to 4

### ISSUE THREAD

**Issue by camillevilla** [sul-dlss/sul-requests#1252]
Here's a representative list of interfaces in the application:
https://docs.google.com/document/d/1a6w-rJwIN4BzvQ5nBh5s0Atl46-RxsvSzLS3d6lKmpM/edit#heading=h.35ylgm5otm1l

**Comment by jcoyne** [comment]
Some work has been started in https://github.com/sul-dlss/sul-requests/pull/1048

**Comment by corylown** [comment]
Also started here: https://github.com/sul-dlss/sul-requests/pull/1888
