### ISSUE TITLE
Patrons without SUNet IDs should be able to page/request materials (by May 2, 2022)

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/sul-requests#1269]
I'd heard from Alexis that LEG has discussed next steps for reopening SUL services to visitors (SPEC researchers, 7 day pass, fee card holders, etc.). The desired outcome is that patrons without SUNet IDs should be able to page/request materials by **May 1, 2022**, which is the day that SUL expects to reopen to the public.

I'd suggested to her that we'd need about 2 weeks to test things out and make any changes. She said that there are no expected policy changes, and that this would be a return to pre-pandemic policies for those patron groups.

This is a placeholder ticket for now and may spin off new tickets in sul-dlss/mylibrary or other applications as needed. I'm passing this off to @saseestone to do the requisite analysis once she's back in the office.

**Comment by saseestone** [comment]
Roll-out date moved to Monday, May 2nd.

**Comment by saseestone** [comment]
Planning document: https://docs.google.com/document/d/1PjODhd7ekihhbM6gbIeYq4RmsJ4GqT3uaARYJjJU3yw/edit#
