### ISSUE TITLE
When LibID option allowed, validate LibID before submitting request

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/sul-requests#1272]
Part of work to open SUL to visitors and Library ID card holders on 5/2/22, and an update of JV's original #898  

When providing the Library ID option to users, we should check that the LibID provided is valid using Symphony webservices. If it is not, we should display an error in place in the form, so that the user can correct and re-submit.

Overall process:
1. User selects "I don't have a SUNet ID" 
2. User enters LibID and clicks send
3. We check if LibID as entered exists in Symphony
4. If it does, we process the request as normal and proceed to the "we got your request" page
5. If it does not exist, we display the error in place in the form, so the user can correct it and re-submit.

### After user clicks "Send request", disable button and add spinner
Since the check might take more time than the usual Send, it would be good to give users a clue that something is happening.
![image](https://user-images.githubusercontent.com/14897546/163654144-d4fd36aa-2c7e-4212-9438-566a7c5ac588.png)

### For Page & Mediated page, the Library ID is optional and should appear like
![image](https://user-images.githubusercontent.com/14897546/163653503-769540fb-87c5-4103-966b-1f031a14a27f.png)

- Add help text directly under the Library ID input box "ID is a 10-digit number." to appear directly under the Library ID input box

### For HoldRecall when SUNet ID or Library ID is required:
![image](https://user-images.githubusercontent.com/14897546/163654144-d4fd36aa-2c7e-4212-9438-566a7c5ac588.png)

### Display the error condition on the form:
If the libID comes back as invalid:

- Change the `h1` to `Request not sent: Library ID is incorrect` **(1)**
- Add a cardinal-red border around the libID input **(2)**
- Add the error message immediately below the input (replaces the help block)  **(3)**
   - in `<div role="alert">` so it will announce to the SR 
   - use class `alert-danger` for styling 
   - add danger icon in front of the first line of text (I used `<p>` to separate the two sections of text.) **(4)**
   - use `aria-describedby` to link the error to the input 
   - add an `aria-label` for the `8 0 6 0 9` number so it reads as separate digits for SR: **(5)**
      - `<span aria-label="8 0 6 0 9">80609</span>`
      - style the span with `font-weight: bold; letter-spacing: .1em;`

<img width="608" alt="request - error message" src="https://user-images.githubusercontent.com/6945691/67040412-4ef82c00-f0d8-11e9-9df2-854aa0440725.png">

**Comment by saseestone** [comment]
@ggeisler we're going to need a mockup of what the error condition should look like on the form if Library ID is Optional.  The one I used above (from JV) displays the LIbrary ID field as required AND doesn't indicate that Name/Email is an option.

The name/email option should be extremely prominent, so I don't think we'd need to say some version of "Why don't use use the name/email option instead" in the error text.

**Comment by saseestone** [comment]
Example web services call to get patron record using the library ID:
https://symws-prod.stanford.edu/symws/user/patron/search?q=ID:TEST-BD

**Comment by thatbudakguy** [comment]
as far as we can tell, this is done. @saseestone and I verified in prod that the error message designed above appears if you submit an invalid library ID. Jessie's original PR https://github.com/sul-dlss/sul-requests/pull/903 implemented the symws portion of this, and it's still active:
https://github.com/sul-dlss/sul-requests/blob/febe6711268f6eef07e84f46e67a9d0c478cd362/app/models/concerns/request_validations.rb#L61-L72

so, closing as done.
