### ISSUE TITLE
For 5/2/22: Reinstate planned date of use for Mediated pages

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/sul-requests#1278]
Part of work to open SUL to visitors and Library ID card holders on 5/2/22.

We need to re-add "needed_date" (displays to users as "Planned date of use") for all mediated paging (Art, Education, Marine Biology, Earth Science, Rumsey, and Special Collections) 

- Add input field to Mediated request forms directly under "Earliest delivery date".
-- Include calendar widget to help user select a date
- Include date input in confirmation mailers
- Include date input in [Status](https://requests.stanford.edu/mediated_pages/313192/status) page
- In the [staff mediation space](https://requests.stanford.edu/admin/SPEC-COLL), include date input under "Needed by" column

**Comment by saseestone** [comment]
@corylown tested this today, and I tried to input an "I plan to visit on" date that was a Saturday. I'm getting a great failure message, but also (encoded) help text that indicates only Stanford community members can input the request.

Here's a screengrab:
![image](https://user-images.githubusercontent.com/14897546/165408341-df3ae465-302b-458a-afc6-2d04ebaf309c.png)

We should keep the red "This library is not open on [date]", but lose the black "Researchers in the Stanford community can request...by appointment only" text.

**Comment by corylown** [comment]
@saseestone it looks to me like the note that displays under "I plan to visit on" ("Researchers in the Stanford...") is coming from the holdings record for the requested item. I can definitely suppress any message from displaying there but I'm wondering if the plan is to remove that note from the holdings record instead?

**Comment by corylown** [comment]
For my own reference...here's a request that displays the message: http://localhost:3000/mediated_pages/new?item_id=1211410&origin=SPEC-COLL&origin_location=BARCHAS

**Comment by corylown** [comment]
The message comes from SearchWorks. This was fixed via https://github.com/sul-dlss/SearchWorks/pull/2831
