### ISSUE TITLE
For 5/2/22: Remove eligibility statement on page & scan form choice page

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/sul-requests#1287]
Part of work to open SUL to visitors and Library ID card holders on 5/2/22.

When the user is presented the screen to select between "page" and "scan", we need to remove the eligibility statement that is appearing under the "Request & pickup" button.

For "Request & pickup" the user should only see the "Earliest delivery date". 

<img width="523" alt="image" src="https://user-images.githubusercontent.com/14897546/165434008-9aca9950-b5d6-4093-9f7b-6127d3d39b04.png">

**Comment by saseestone** [comment]
Noting here that the text that appears under the "Scan to PDF" option should remain (i.e. the page limitation AND the user availability statement.)

**Comment by corylown** [comment]
@saseestone I've deployed this change to https://requests-dev.stanford.edu/ for testing.

**Comment by saseestone** [comment]
Tested in dev and it looks good.  Thanks for the quick fix!
