### ISSUE TITLE
Aeon 2022: SearchWorks => Aeon request analysis

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/sul-requests#1322]
To implement Aeon for SUL, we'd like to improve on work we did for for Hoover Library & Archives when a request is going directly from SearchWorks to Aeon (e.g. there is *no* OAC Finding Aid in the record.)

An important improvement is to address the problem of the call number not being carried from SearchWorks to the Aeon form in the constructed OpenURL.

We're aiming for a **mid-August 2022 implementation of Aeon for SUL**. Gary and I have been working on the desired user flow using this [context document](https://docs.google.com/document/d/1VwHrVS0CyE57o2bu_cmFfHVjFjg1yNjTdEIdlBYZSlk/edit#)

Summarized, we'd like to explore a solution that uses an [Aeon's External Request Endpoint](https://support.atlas-sys.com/hc/en-us/articles/360011820054-External-Request-Endpoint). This solution is used by UW-Madison when there are multiple volumes or copies. Example record: https://search.library.wisc.edu/catalog/9911124690702121/room. It allows us to keep a similar look and feel in the request form, preserving our checkbox interaction and submitting requests to Aeon for multiple volumes in one call.

If it is determined that this is not a viable solution, we'd like to look at redesigning the paging request form **only for SPEC-COLL, RUMSEY, ARS and some collections in EAL** to include a request button next to each volume or copy, so that we can pass the call number requested via [Aeon's OpenURL](https://support.atlas-sys.com/hc/en-us/articles/360011919573-Submitting-Requests-via-OpenURL). Many Aeon sites use this solution, but we find it clunky if the user needs to request multiple volumes from the same title record.  Here are examples from Duke of this approach: [multi-copy](https://requests.library.duke.edu/item/001608588), [multi-volume](https://requests.library.duke.edu/item/000227879)

If neither is deemed possible ☹️, we still need to implement a SearchWorks to Aeon OpenURL pathway for SUL materials without a Finding Aid. Using the current solution applied for Hoover Library & Archives is less than ideal, but better than no solution.

**Comment by cbeer** [comment]
```html
            <form action="https://stanford.aeon.atlas-sys.com/aeon/aeon.dll?Action=11&Type=200" method="post">
              <h3>ERE Form</h3>
              <!-- 
                Can we add/remove fields from the requests form?

                What parameters should we send?
                1. ItemTitle
                2. ItemAuthor
                3. CallNumber
                4. Barcode??
                5. ??

                How do we know what EAL items get an Aeon form?

                TODO: Magic javascript to turn the requests form into an ERE request form?

                Why can't we choose a reading room?

                How do we restrict which items can be picked up a which library?

                Does the saved requests page give enough context? Can we add more?
              -->
              <input type="hidden" name="SystemID" value="sul-requests-dev" />
              <input type="hidden" name="ItemTitle" value="Puf! : revista cartonera" />
              <input type="hidden" name="ItemAuthor" value="De Mora, Draupadí" />
              <input type="hidden" name="Request" value="1" />
              <input type="hidden" name="CallNumber_1" value="Z239.71 .P84 NO.1-2" />
              <!-- <input type="hidden" name="" value="36105231375622" /> -->

              <input type="hidden" name="Request" value="2" />
              <input type="hidden" name="CallNumber_2" value="Z239.71 .P84 NO.11,13" />
              <!-- <input type="hidden" name="" value="36105231236378" /> -->

              <input type="submit" />
            </form>
```

**Comment by cbeer** [comment]
![Screen Shot 2022-07-14 at 11 28 59](https://user-images.githubusercontent.com/111218/179056125-401c6133-442a-463b-9e52-9c45f0b1a1c1.png)

🤯

**Comment by cbeer** [comment]
We believe this work is blocked until the Aeon customizations are complete. It's a little too hard to tell what's working or not working in its current state, and whether the ERE approach will create an acceptable UX 🤷

**Comment by saseestone** [comment]
Our Atlas Systems contact confirmed today that customizations are in development. They estimate 1-2 weeks of work. 

Katie at Atlas has also confirmed that we can isolate requests submitted using the External Request Endpoint solution, and route them automatically to the "Outstanding Requests" queue (which is the flow the user would expect and mirrors what happens when the user submits from the Online Archive of California.) She also confirmed that outstanding customizations include the removal of the "Site" and "Reading room" sections that appear in Chris' screengrab above.

She did note that we need to pass a "site value" in the ERE.  Aeon site values correspond to the Symphony/FOLIO owning library using the following map: 
**Symphony/FOLIO owning library => Aeon site value**
SPEC-COLL => SPECUA 
ARS => ARS
EAST-ASIA => EASTASIA
RUMSEY => RUMSEY
