### ISSUE TITLE
Place item + instance ("title") level holds using the mod-patron (edge-patron) API

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/sul-requests#1331]

**Comment by thatbudakguy** [comment]
possible that our version of FOLIO doesn't even support title level holds yet?

**Comment by thatbudakguy** [comment]
(sorta) blocked on #1434

**Comment by thatbudakguy** [comment]
we think:
- title-level holds "officially" supported in nolana
- title-level holds for on-order instances still unclear.

**Comment by thatbudakguy** [comment]
to complete this ticket, compare the mod-patron and edge-patron APIs in FOLIO to decide which one we want to use, based on the data that is available to requests at the time (who the user is, what catkey (title) or barcode (item) was requested, where they want it to go). ideally we can use mod-patron since it comes "for free"; we could install and configure edge-patron if needed. does the API actually work and match its docs?

**Comment by jcoyne** [comment]
The primary difference between the mod-patron and edge-patron APIs is the value of the account id.  mod-patron requires "The UUID of a FOLIO user" and edge-patron uses "Patron's external system Id stored in FOLIO user record".  How would we link a FOLIO user id to a sunetid?

**Comment by thatbudakguy** [comment]
blocked until we figure out why hold requests are timing out; there doesn't seem to be enough error output to get to the bottom of this. more investigation needed (from libsys?)

**Comment by thatbudakguy** [comment]
see slack thread: https://stanfordlib.slack.com/archives/G018TJ20XGE/p1683211174057659

**Comment by thatbudakguy** [comment]
closing since our retry strategy has unblocked this.

**Comment by cbeer** [comment]
I'm reopening this because I think we only discovered which API endpoints to call and verified we could call them with some data.

I think we need to finish investigating the API parameters to send in order to create the same types of user experiences. In requests today, our users can send:
- a free-form comment (currently truncated to 50 characters to meet Symphony requirements; is there any restriction in FOLIO-land?)
- specifying a "fill by date"/expiration for their recall or mediated page

And the system decides whether or not a hold request triggers a recall or not (certain types of patrons can't recall material). Is this something we can control, or does FOLIO take care of it automatically?

An additional API investigation is... the current contract with Symphony involves using catkeys and barcodes, but it looks like FOLIO wants UUIDs. Do we know the right API endpoints to hit for converting from catkeys + barcodes to the appropriate UUIDs?

**Comment by cbeer** [comment]
> a free-form comment (currently truncated to 50 characters to meet Symphony requirements; is there any restriction in FOLIO-land?)

No surprise, there's no real restrictions in FOLIO.

**Comment by cbeer** [comment]
Fixed by #1437 + #1459; the start of TLR split to #1450
