### ISSUE TITLE
Aeon: Create a Requests informational page

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/sul-requests#1335]
As noted in https://github.com/sul-dlss/SearchWorks/issues/3014, the new Request-to-Aeon page flow includes a Requests informational page. This page is needed for all three request page flow variations (single volume/copy item, multi-volume/copy item, and finding aid item). We've tried to keep the page content as generic as possible but there are some use case and library/location specific variations.

<img width="804" alt="Screen Shot 2022-09-02 at 2 05 56 PM" src="https://user-images.githubusercontent.com/101482/188237751-5e06ddce-cd2d-47ba-a0fc-3f33a50259cb.png">

---

**A:** `[Special Collections] access`
- Use the existing H1 styling in Requests (e.g. same as [the heading on this page](https://requests.stanford.edu/mediated_pages/new?item_id=13864637&origin=SPEC-COLL&origin_location=GUNST))
- The bracketed part differs by the owning library/location of the item. It should be either "Special Collections", "East Asia Library", "Archive of Recorded Sound", or "David Rumsey Map Center".

**B:** `Restricted items are made available for use in the Reading Room. They cannot be checked out from the library or borrowed via Interlibrary Loan.`
- This text is generic and doesn't change based on either use case or owning library/location.

**C:** `How does it work?`
- This is an H2 but shouldn't use the existing H2 styling I see on the current Requests selection page. It remains the same font size (~22px) but should be regular weight Source Sans Pro, `#3f3c30` color, without the special letter-spacing used in the H1 heading.
- This text is generic.

**D:** `On-site and digital access requests are managed by Aeon, an archives and special collections system. If you haven’t already created a Stanford Aeon special collections research account, you will need to do so as part of the request process. Once you have an Aeon account, you will be able to check the status of requests, edit or cancel requests, create a new appointment or edit an existing appointment, and review your request history.`
- This text is generic.

**E:** `To make a request:`
- This text is generic.

**F:** The steps here differ by type of use case. See the separate section below for details.

**G:** `For more details, visit the [owning library/location] Reading Room service page`
The bracketed part differs by the owning library/location of the item, as does the link target:
- Special Collections: https://library.stanford.edu/spc/using-our-collections
- East Asia Library: https://library.stanford.edu/eal/special-collections-east-asia
- Archive of Recorded Sound: https://library.stanford.edu/ars/using-archive
- David Rumsey Map Center: https://library.stanford.edu/rumsey/about-center/visitor-policies

**H:** The "Continue" button is styled as a primary button and redirects the user to either Aeon (non-finding aid item) or OAC (when a finding aid item, as described in https://github.com/sul-dlss/SearchWorks/issues/3014). The "Cancel" button returns the user to the previous page they were on.

## Callout F variations
The steps in this section are somewhat different depending on whether it is a single-volume/copy, multi-volume/copy, or finding aid item. I'll include a link for each use case to the appropriate prototype -- you'll need to select a request button to navigate to the Requests information page.

### Single-volume/copy steps
Example: https://www.figma.com/proto/CquVTLOGUVavYkwkUWs0VQ/SW---Requests---Aeon?node-id=1008%3A176&scaling=scale-down&page-id=1008%3A175&starting-point-node-id=1008%3A176

```
1. Log in to your Stanford Aeon user account (or create one)
2. Complete the request form
3. For on-site requests, create an appointment so we know when you’re planning to arrive
4. Submit your request
```

### Multi-volume/copy steps
Example: https://www.figma.com/proto/CquVTLOGUVavYkwkUWs0VQ/SW---Requests---Aeon?node-id=1009%3A238&scaling=scale-down&page-id=1009%3A14&starting-point-node-id=1009%3A238

```
1. Select the materials you would like access to
2. Log in to your Stanford Aeon user account (or create one)
3. Complete the request form
4. For on-site requests, create an appointment so we know when you’re planning to arrive
5. Submit your request
```

### Finding aid steps
Example: https://www.figma.com/proto/CquVTLOGUVavYkwkUWs0VQ/SW---Requests---Aeon?node-id=1119%3A621&scaling=scale-down&page-id=1119%3A614&starting-point-node-id=1119%3A621

```
1. Review the Collection Guide in the Online Archive of California
2. Select “Request items”
3. Log in to your Stanford Aeon user account (or create one)
4. Select the materials you would like access to
5. Complete the request form
6. For on-site requests, create an appointment so we know when you’re planning to arrive
7. Submit your request
```

**Comment by saseestone** [comment]
A few clarifying points about this interstitial page:

1. It should only appear for requests that are currently classified as mediated_pages. Said another way, all requests that will need to be routed to Aeon are currently classified as mediated_pages. 

2. Not all mediated_pages will be handled by Aeon after we go live. These library/location combos will **NOT** be handled by Aeon:

- All mediated_pages for Library = ART (e.g. locations = ARTLCKL, ARTLCKL-R, etc.)
- Location = PAGE-MP
- Library = EDUCATION, Location = LOCKED-STK
