### ISSUE TITLE
Aeon: Update the Requests selection page

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/sul-requests#1336]
The [current Requests selection page](https://requests.stanford.edu/mediated_pages/new?item_id=13414178&origin=SPEC-COLL&origin_location=GUNST) includes sections that will now be handled by Aeon and we should therefore remove from the page.

<img width="804" alt="Screen Shot 2022-09-02 at 3 38 04 PM" src="https://user-images.githubusercontent.com/101482/188243273-f09471e2-615f-44ba-b7b8-90c3670a0c73.png">

**A:** Update the page heading to `Request access` (removing the "on-site" part)

**B:** The entire yellow backgrounded appointment box should be removed. This is handled in Aeon.

**C:** The comment label/textarea should be removed. Also handled in Aeon.

**D:** We now only need one, simpler primary button, with a label of `Continue to complete request`. This should redirect to Aeon, as described in sul-dlss/SearchWorks#3014.

The selection behavior of the form should remain as it is. That is, when the user arrives at the page, the "0 items selected" message should appear, the "[Select one or more items from the list above.]" message text should be displayed, and the primary button should be disabled. Those elements should then change as they currently do when the user selects one or more items from the list.

Here are mockups of how things should look after the updates above.

## Initial, disabled state

<img width="804" alt="Screen Shot 2022-09-02 at 3 37 06 PM" src="https://user-images.githubusercontent.com/101482/188243349-8a1133d1-3d61-40f4-aa60-badf24e258c2.png">

## After the user makes a selection
<img width="804" alt="Screen Shot 2022-09-02 at 3 37 48 PM" src="https://user-images.githubusercontent.com/101482/188243355-d775ba5a-2fa1-401a-9d8a-1f4bcbf5b7f6.png">

**Comment by cbeer** [comment]
(Note that we also use this same form for requests that won't go to Aeon, e.g. https://requests.stanford.edu/pages/new?item_id=433334&origin=SAL3&origin_location=STACKS)
