### ISSUE TITLE
For 12/13/22: Replace current BorrowDirect API with new ReShare API

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/sul-requests#1367]
IPLC, the governing body for BorrowDirect, is moving away from Relais to ReShare. We will need to replace our current API with a new ReShare API when routing RecallHold requests to BorrowDirect.

There is API documentation available in basecamp: https://3.basecamp.com/5319802/buckets/26606684/documents/5132521312
Since it requires a basecamp account, I've copied it here: https://docs.google.com/document/d/1u8NouCFH1DVBV74vNtxv30zp9D0HmQI6yGrCMV9W7Wo/edit#
Hilary Thorsen arranged for my basecamp account, and we can request others through her as needed.

IPLC plans to cut over from Relais to ReShare on ~~12/1/22 OR on~~ ~12/6/22~ 12/13/22.

**Comment by corylown** [comment]
Dropping some notes on this:

- The VuFind Search API is unrestricted at the moment; no authorization is required. It enables us to lookup a record by an ISN (or other fields) and find its lending status and its shared inventory record ID, which is required for placing a request via the OpenURL Resolver. (example VuFind Search API ISN request: https://borrowdirect.reshare.indexdata.com/api/v1/search?lookfor=0791056554&type=ISN&field%5B%5D=id&field%5B%5D=lendingStatus&sort=relevance&page=1&limit=20&prettyPrint=false&lng=en
- The Open URL Resolver will enable us to place a request for an item using the shared inventory ID. **It's IP restricted, so we'll need to share (with someone?) our server IP addresses for access.**
- mod-rs API will let us lookup request status. We'll need a **username**, **password**, and **tenant** **(do we need to request these?)**. I think this would be used by mylibrary to display request status to patrons. I've created a ticket over in mylibrary to represent this work: https://github.com/sul-dlss/mylibrary/issues/757

**Comment by saseestone** [comment]
Just heard from Hilary that the earliest date for ReShare will be 12/6, and it might be delayed again.  IF there is a delay, James R. will announce by 11/17.
