### ISSUE TITLE
Update sul-requests to Rails 7

### ISSUE THREAD

**Issue by corylown** [sul-dlss/sul-requests#1391]
Update when complete: https://docs.google.com/spreadsheets/d/12fTiyvn6lz3gkVRyAhttxYua6dYHHSCZ1rJFaAd1X6U/edit#gid=1480620710

**Comment by thatbudakguy** [comment]
May be blocked on https://github.com/sul-dlss/sul-requests/issues/1252 because of bootstrap gem compatibility.
