### ISSUE TITLE
Fill in missing data on mediation page

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/sul-requests#141]

**Comment by jvine** [comment]
Columns in order - note **columns should be sortable**.

* [ ] remove Type column 
* [ ] add Needed on date (display as Mon May 18) 
 * requires date picker in form
 * column should be present only if the request type supports it
* [ ] add Yes & No action columns
* Location column is ok
* [ ] add Current (current location, ONLY if different from home location)
* [ ] add Call number 
 * [ ] add public note + user comment as child rows [not shown in screenshot]
 * click on call number to display
 * example https://datatables.net/examples/api/row_details.html
* [ ] remove Destination
* Title column is ok
* Requester column is ok
* Requested on column is ok **default sort**

![screen shot 2015-05-18 at 11 39 32 am](https://cloud.githubusercontent.com/assets/6945691/7687508/a8b602fe-fd52-11e4-9be6-06940bb3ccfc.png)
