### ISSUE TITLE
Remove bootstrap-editable library

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/sul-requests#1431]
This library relies on BS3 glyphicon classes and we are hosting ("vendorized") it in our repository as of https://github.com/sul-dlss/sul-requests/pull/1403/commits/9e558fde714162a78d442dc6e768f9c64c105c47

We only use the library in one place in the app: https://github.com/sul-dlss/sul-requests/blob/97aacf9ee2f38bb3aaeca498f9dab74015a72579/app/views/admin/_library_table.html.erb#L40

We initialize the library here: https://github.com/sul-dlss/sul-requests/blob/97aacf9ee2f38bb3aaeca498f9dab74015a72579/app/assets/javascripts/application.js#L51

This library is no longer maintained and will stop working correctly with future versions of Bootstrap. It seems like a modern approach could be to use turboframes for inline editing.

**Comment by jcoyne** [comment]
Fixed by #1899
