### ISSUE TITLE
Finish setting up requests-folio-dev

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/sul-requests#1434]
we have a server created by ops, but that's about it. needs some work to ensure it's configured and running correctly.

**Comment by thatbudakguy** [comment]
as far as I can tell, this is done:
- the app is deployed to requests-folio-dev.stanford.edu
- searchworks-folio-dev request links correctly point to requests-folio-dev
- clicking a request link seem to take me to requests-folio-dev and do the right thing

**Comment by cbeer** [comment]
TODO:

- [ ] point requests-folio-dev at searchworks-folio-dev
- [ ] hook up requests-folio-dev to FOLIO, not symphony
- [ ] ???
