### ISSUE TITLE
Place requests on behalf of pseudo-patrons

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/sul-requests#1451]
We use pseudopatrons to place requests under a variety of conditions:
- when the request is placed with just a name + email (esp. for mediated pages) or the patron's status is inactive but a member of the general public could do it (in FOLIO, this would be a Page request using the pseudopatron, but with the person's name and email in a "comment" field — should be obvious which property this is). 
- <s>when the patron is inactive, but we want to eagerly page material from off-site before they resolve their account problems</s> (see #1527)
- for scanning, where the item isn't actually delivered to the patron
- <s>for other weird scenarios</s>

When we place a pseudopatron hold, we try to include enough information in the hold comment to let staff figure out what's going on.

We need to understand what the FOLIO pseudopatrons are and how its usage differs from Symphony, and then implement similar logic for FOLIO requests.

One complication of pseudopatrons in Symphony-land is when we attempt to place requests on the same item for patrons that map to the same pseuopatron (e.g. 2 different name-email requestors that both want to see the same item in SPEC). Our current error handling sends an email to staff for manual processing. Does FOLIO give us any hope of a better approach?

**Comment by thatbudakguy** [comment]
@saseestone to determine what the current practices are in FOLIO regarding pseudopatrons and how it differs from symphony.

**Comment by saseestone** [comment]
> when the request is placed with just a name + email (esp. for mediated pages) or the patron's status is inactive but a member of the general public could do it

This scenario will remain, and the plan is to create a new patron group specific to "psuedopatron for paging" and add circrule lines for that patron group to allow them to "page only"

@dlrueda is it ok for me to go ahead and create this group? Alex, Will, Alice, Catherine, and Kelly know it's coming. Leah & Alex indicated they wanted to use this group as well in their circules.

**Comment by saseestone** [comment]
> when the patron is inactive, but we want to eagerly page material from off-site before they resolve their account problems

See https://github.com/sul-dlss/sul-requests/issues/1460. Most block conditions won't block renewals automatically, or as part of a block template. I think we can do away with this scenario. Staff will have to explicitly remove an individual's ability to request materials, and we should honor that.

We may need to create a failure message that displays the "display description" from the block.

**Comment by saseestone** [comment]
> for scanning, where the item isn't actually delivered to the patron

We can use the "psuedopatron for paging" patron group for these psuedo-patrons.  That will allow the item to be paged for scanning.

**Comment by saseestone** [comment]
> for other weird scenarios(?)

Ummmm. I haven't come across any more. We'd need to specify more this more.
