### ISSUE TITLE
Figure out if circ rules give us a way to know whether name + email are sufficient to place a page request

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/sul-requests#1452]
We currently keep some business logic in abilities (e.g. [name + email is insufficient to page material to BUSINESS](https://github.com/sul-dlss/sul-requests/blob/master/app/models/ability.rb#L72) or to [place hold/recalls](https://github.com/sul-dlss/sul-requests/blob/master/app/models/ability.rb#L76)).

Is this information also available in circ rules? Can we use circ rules to drive abilities?

**Comment by thatbudakguy** [comment]
answer is probably no; but can we find a workaround?

**Comment by thatbudakguy** [comment]
for placing holds/recalls, maybe we could create a circ rule that only applies to a patron group of name/email patrons, and then attach a request policy like:
```js
  {
    "id": "1a376854-636f-44e6-8405-65987ea90e95",
    "name": "Allow paging",
    "description": "Items may be pulled off the shelf.",
    "requestTypes": ["Page"],
    "metadata": {
      "createdDate": "2023-05-11T17:03:42.702+00:00",
      "createdByUserId": "3e2ed889-52f2-45ce-8a30-8767266f07d2",
      "updatedDate": "2023-05-11T17:03:42.702+00:00",
      "updatedByUserId": "3e2ed889-52f2-45ce-8a30-8767266f07d2"
    }
  },
```

so paging only, no holds/recalls (we already have this policy defined).

for the `BUSINESS` case, i can't find anywhere in folio that lets you add logic based on where an item is being paged _to_, so I'm not sure what to do there...

**Comment by cbeer** [comment]
I think the trick is people coming to requests with just a name&email don't have patron accounts at all; do we need multiple types of pseudopatrons?

**Comment by thatbudakguy** [comment]
resolution: create a new name/email pseudopatron type and talk to circ rules folks about implementing rules specific to it.
