### ISSUE TITLE
Propose a strategy for dealing with location-restricted paging

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/sul-requests#1454]
We currently keep a mapping of location codes -> pickup libraries:
https://github.com/sul-dlss/sul-requests/blob/master/config/settings.yml#L428-L478

A cursory look suggests FOLIO doesn't provide equivalent information in its circ rules (but maybe it could?).

Do some investigation to see what FOLIO can do for us, or see if we're stuck with maintaining that logic locally.

**Comment by thatbudakguy** [comment]
It seems that folio locations support storing arbitrary key-value data on locations at `location.details`. The example given in the docs shows:
```js
{
  "id": "d9cd0bed-1b49-4b5e-a7bd-064b8d177231",
  "name": "Miller General Stacks",
  "code": "UA/CB/LC/GS",
  "isActive": true,
  "description": "The very general stacks of Miller",
  "discoveryDisplayName": "Miller General",
  "institutionId": "4b2a3d97-01c3-4ef3-98a5-ae4e853429b4",
  "campusId": "b595d838-b1d5-409e-86ac-af3b41bde0be",
  "libraryId": "e2889f93-92f2-4937-b944-5452a575367e",
  "details": {
    "a": "b",
    "foo": "bar"
  },
  "primaryServicePoint": "79faacf1-4ba4-42c7-8b2a-566b259e4641",
  "servicePointIds": [
    "79faacf1-4ba4-42c7-8b2a-566b259e4641"
  ]

}
```

maybe we could use this to store the UUIDs of valid pickup locations for items paged from that location?

unfortunately none of the other location types (library, campus, institution) support the `details` object, so this wouldn't let us do library-level configuration for pickup locations.

**Comment by thatbudakguy** [comment]
closing in favor of #1505, which is our strategy
