### ISSUE TITLE
Date Formats

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/sul-requests#150]
We has them.

Can we look over all the different date formats that we want to present to users and put them into i18n so we can reference them around the app.

See https://github.com/sul-dlss/sul-requests/pull/149#discussion-diff-30710374

**Comment by jvine** [comment]
Patron facing dates in static text have this format:  **Weekday, Mon dd yyyy, time**
- estimated delivery: **Wednesday, Feb 11 2015, after 11am**
- cancel date / planned date of use: 
 - in the date field - **Feb 11 2015**
 - on the success page/email/status page - **Wednesday, Feb 11 2015**

Mediator-facing dates have 2 different formats:
- "Needed on" (planned date of use): **Wed Feb 11** - quick-scan, near-future date
- "Requested on":  designed as **2015-01-12 9.05a** - meant as a time-stamp. This one is negotiable, could be **Feb 11 2015, 9:05a** to match the pattern above.

**Comment by jkeck** [comment]
@jvine you commented that we should format the date "in the date field".

However; that date format comes from the browser's configured date format and is not necessarily customizable (per the HTML5 spec).  I think we should ship w/ the browser configured date in the date field and possibly explore other options when we implement the picker widget.
