### ISSUE TITLE
Define information to be captured in FOLIO service point description to support pickup library logic

### ISSUE THREAD

**Issue by hudajkhan** [sul-dlss/sul-requests#1519]
The settings file is/was divided into sections defining rules for paging, scanning, and hold/recall.  The app reads these rules in to identify which pickup libraries can be displayed for the user.

Instead of relying on this settings file, we want to capture information at the FOLIO service point level and then show these service points in the dropdown.  This issue focuses on identifying which information needs to be captured at the service point level in FOLIO.  As part of this issue, we'll mockup the information and see if a local service points JSON file with that information supports the logic we want to see.  

Generated from #1455

**Comment by hudajkhan** [comment]
While reviewing location rules to get a sense of the landscape, I parsed the settings file to output the pageable section as a CSV sorted by pickup library/service point location.  Each row represents one location rule.  The "location matches" property wasn't taken into account. 
[servicepointinfo.csv](https://github.com/sul-dlss/sul-requests/files/11807742/servicepointinfo.csv)

**Comment by hudajkhan** [comment]
Information about aeon sites and relevant mediation groups will be stored at the location level.  Based on earlier discussions with Nick and Marlo, and looking over the spreadsheet, the following seems like information we can save at a service point level: whether it's a default pickup location, where it should be the default selection in a dropdown, where it should be added to the default list of pickup service points.  We may also wish to encode the pickup rules at the service point location level, to help with determining which combination of origin location and origin library apply to a service point.

**Comment by hudajkhan** [comment]
Also, we want to capture if the service point is a scanning location or scanning approval location (i.e. when a request is made to scan material,  the item is sent to a location to be scanned or approved for scanning).

**Comment by cbeer** [comment]
> where it should be added to the default list of pickup service points.

You're thinking of cases like adding the Media/Microtext desk for their material? I wonder if the location/details information can just point at any service point, and the service point doesn't need to know?

**Comment by hudajkhan** [comment]
That will probably work : )

**Comment by hudajkhan** [comment]
Linked to https://github.com/sul-dlss/folio-graphql/pull/89
