### ISSUE TITLE
Replace pickup libraries display with pickup service points display

### ISSUE THREAD

**Issue by hudajkhan** [sul-dlss/sul-requests#1520]
Once #1519 has been completed, and service point descriptions have been added to FOLIO, ensure the front-end is able to display these service points correctly. 

Generated from #1455

**Comment by saseestone** [comment]
Putting a note here that I've confirmed that Lane Library (FOLIO service point = LANE-DESK) will need to be added as a default pickup Library. 

If we don't end up using the service point details to determine the default list, then we need to remember to add Lane Library to our (hardcoded) default list.

**Comment by hudajkhan** [comment]
This can be closed now with the integration of https://github.com/sul-dlss/sul-requests/pull/1638
