### ISSUE TITLE
Handle group patron in FOLIO

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/sul-requests#1554]
Currently `Folio::Patron#group` is just a stub method.

**Comment by jcoyne** [comment]
There is no equivalent of a Group in FOLIO, so we can just remove this code.

**Comment by cbeer** [comment]
I'm confused; `Group` is our own creation in requests/mylibrary (the sponsor + all their proxies). Doesn't that still apply to FOLIO?

**Comment by jcoyne** [comment]
I thought I heard Sarah say this in planning on Friday. I could have misunderstood.

**Comment by cbeer** [comment]
I chatted a bit with Sarah. Unlike in MyLibrary, groups in sul_requests have nothing to do with Symphony's concept of group (which is a database + workflows things, never exposed in the web services APIs).

sul_requests uses `Folio::Patron#group` to make sure that if you have a patron acting as a proxy for someone else, notification emails (also?) go to the proxy's sponsor. We may not need the `#group` method, but we certainly need the effect.

**Comment by cbeer** [comment]
Fixed by #1583
