### ISSUE TITLE
Inprocess item should not show request and scan option

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/sul-requests#1557]
URL: https://searchworks-folio-dev.stanford.edu/view/14600413

What should show for an inprocess item?

From https://docs.google.com/spreadsheets/d/1D6M-m1IYNakKPfHfH0072tImrFY6x-yKfhu6bvGpVSI/edit?pli=1#gid=1019581243

**Comment by cbeer** [comment]
In production, in-process items are hold/recall requests and the patron doesn't have any other options.

E.g. https://requests.stanford.edu/requests/new?item_id=14718622&origin=SAL3&origin_location=INPROCESS
