### ISSUE TITLE
Change hold/recall confirmation email to inform patrons of processing delay during shutoff

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/sul-requests#1576]
We need to inform patrons that their hold/recalls opened during the changeover period will be delayed in processing until the switch to FOLIO.

**Comment by cbeer** [comment]
I think this ticket should probably say the request success page, not email.

**Comment by thatbudakguy** [comment]
waiting on text for this email from @saseestone

**Comment by saseestone** [comment]
Are we talking about **both** the holdrecall mailer and the page mailer?

For the holdrecall mailer (and I think it's this one https://github.com/sul-dlss/sul-requests/blob/main/app/views/request_status_mailer/request_status_for_holdrecall.html.erb)

As the first line of body text, let's use the following (and bolding it, or calling it out in some other way would be best...)
"Stanford Libraries will be undergoing a major system upgrade Saturday, August 19 through Sunday, August 27.  Requests fulfilled by our BorrowDirect partners may be available for pickup during the upgrade. You will be notified by staff. Most requests will be processed  and available after August 31. [More information about the upgrade](https://library.stanford.edu/news/major-system-upgrade-august-19-27)"

Then use the standard:
 You have been added to the hold queue for the following item(s):<br/>
      Title: <%= @request.item_title %>
    </p>

    <p>Call number(s):</p>

For the page mailer, let's do something similar. As the first line of body text, bolded or called out in some way, use:
"Stanford Libraries will be undergoing a major system upgrade Saturday, August 19 through Sunday, August 27.  Requests will be processed on August 28, and items will be available for pickup on or after August 31. [More information about the upgrade](https://library.stanford.edu/news/major-system-upgrade-august-19-27)"

If you need/want the same statement for both mailers, use the text for the page mailer.

**Comment by jcoyne** [comment]
@saseestone the link https://library.stanford.edu/news/major-system-upgrade-august-19-27 does not resolve.  Is that yet to be published?

**Comment by saseestone** [comment]
@jcoyne Apologies that I didn't specify that the news article would publish late Sunday 8/6, but we got there in the end.

As for the mediation mailer, I don't know exactly how to answer as I thought we were essentially moving all page requests to a type of mediation. Do we have the option to have a separate email for our "regular" mediation materials (e.g. PAGE-ART, LOCKED-STKS for Education, etc.)?
