### ISSUE TITLE
Use mediation for all non-aeon paging temporarily during Symphony shutoff

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/sul-requests#1577]
This will allow staff to defer all non-critical page requests until after the shutoff by looking at the "needed by:" date supplied by the patron.

This should be as simple as setting `mediated: true` for all non-Aeon entries in the `pageable:` config in settings.

**Comment by cbeer** [comment]
Looking at all the test failures on https://github.com/sul-dlss/sul-requests/pull/1666, I'm not sure it's as easy as setting `mediated` (and, one other downside that occurred to me is we lose the ability to tell real mediated pages apart from regular pages being held... i think we could tell them apart by location but that gets a little ugly post-migration)

Instead, perhaps we can treat pages as if they were mediated (maybe as simple as `class Page < MediatedPage` and some tweaks: #1674 )?
