### ISSUE TITLE
Use picklist system to handle paging during Symphony shutoff

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/sul-requests#1578]
This will help staff handle the potentially large volume of material being paged from SAL- and education locations. This functionality exists in requests now and is used for SPEC material.

- [ ] restore picklist functionality: https://github.com/sul-dlss/sul-requests/pull/1580
- [ ] remove spec-coll-isms and streamline picklists for paging (remove excess bib. info, patron details, etc)
- [ ] reformat picklist into a table (e.g. no need to provide picklist info in duplicate, 1 request per page)

**Comment by jcoyne** [comment]
I'm not clear what this means. Can you provide more details?

**Comment by cbeer** [comment]
We should revert https://github.com/sul-dlss/sul-requests/pull/1412, add picklist mailers for at least SAL, EDUCATION, SAL3.

**Comment by thatbudakguy** [comment]
we have revised estimates of how much paging will actually occur; and staff are anticipating not using picklists to do the paging that does occur. no longer needed.
