### ISSUE TITLE
Handle scan requests via email to staff during Symphony shutoff

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/sul-requests#1579]
We still want to send scans to ILLiad, but instead of placing a hold, we want to send an email to a staff mailing list so that they can pick up the request, contact the patron, and handle it from there.

The staff email to use (regardless of material/location) is sulcirchelp@stanford.edu.

**Comment by cbeer** [comment]
Do we need to send emails for scan requests. I thought ILLiad takes care of all that

**Comment by thatbudakguy** [comment]
No need to email staff. ILLiad handles it all.
