### ISSUE TITLE
ILLiad 'ScanAndDeliverRequest' HTML (Needs Error Check Design)

### ISSUE THREAD

**Issue by jgreben** [sul-dlss/sul-requests#158]
This is the ILLiad page that is called when using the rft.scananddeliver OpenURL param. Need to think about error checking we may need and what should display to the user if something goes wrong, for example, if the webauth user is not also a current user in ILLiad:

https://gist.github.com/jgreben/8262ba57425e39fbc1b3

This is the ILLiad Main Menu with redirect functions back to sul-requests:

https://gist.github.com/jgreben/e65237a065b8da544ec7

**Comment by jgreben** [comment]
One way to handle this would be to set a timeout function (5-10 seconds) on the 2 illiad html pages. If either page lingers too long, indicating something went wrong and the user is stuck there, it will redirect back to an info page in the requests app. e.g. http://localhost:3000/scans/180/error (that page would need design). On this page will be a message tells the user we are working on their request, and the app also emails the item information to the document delivery staff. This way they can still process the request and we can track what went wrong with illiad.

**Comment by jvine** [comment]
![screen shot 2015-09-02 at 5 23 28 pm](https://cloud.githubusercontent.com/assets/6945691/9647928/5b5eafe4-5197-11e5-978d-6895424a5b97.png)

**Comment by jgreben** [comment]
@jkeck @cbeer I was thinking about simply creating a new route to /sorry/index for that page. Does that sound kosher or should it be integrated into one of the existing views?

**Comment by jkeck** [comment]
@jgreben do you mean in the requests app or Illiad?  I wonder if there is any benefit to redirecting to the requests app, or if the error message should live in Illiad.  Hmm.  Any thoughts?

**Comment by jgreben** [comment]
@jkeck yes I meant to redirect back to the request app, but I guess if they are in the modal they will still be in searchworks anyway. If we redirect back to the request app we could perhaps set some kind of session flag, cookie or rails magic to not give them the scan option again, but maybe for now I can just create the page in illiad and leave it at that. Your thoughts about these options?

**Comment by jkeck** [comment]
I could go either way tbh. We theoretically already have the contact information in requests so perhaps it belongs there.

**Comment by jgreben** [comment]
Ok, I will commit and push the branch and you can see what you think.
