### ISSUE TITLE
Folio Mediated page item status is wrong

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/sul-requests#1635]
On https://requests-folio-dev.stanford.edu/admin/ART?done=true
<img width="1228" alt="Screenshot 2023-07-26 at 12 04 01 PM" src="https://github.com/sul-dlss/sul-requests/assets/92044/459e2d6f-6bef-4db4-8f4d-22c42bd3e31b">

I believe it's always showing "Added to pick list" (e.g. `en.status_text.other`)

@saseestone what should it be showing here?

**Comment by saseestone** [comment]
We can keep the text the same.  Staff refer to the lists they get out of Symphony (and FOLIO) as "picklists".

**Comment by jcoyne** [comment]
@saseestone my point was more about it always being "picklist" and never being one of these other options:

https://github.com/sul-dlss/sul-requests/blob/bb3339c857287788d06daaacdf1e7b6baf2c4d75/config/locales/en.yml#L176-L179
