### ISSUE TITLE
Handle paging schedules for coordinate libraries

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/sul-requests#1661]
Coordinate libraries have SAL3 locations in FOLIO:

e.g.
HILA-SAL3-STACKS
LANE-SAL3
LANE-SAL3X
BUS-SAL3-STACKS
BUS-SAL3-PAGE-BU
SPEC-SAL3-MSS

Currently, all paging schedules are based around the library the material is being transferred to/from. We should use the SAL3 origin paging schedule for these types of locations.

Use the origin location's `pagingSchedule` information in `details` to pick the right origin paging schedule (e.g. an origin location with the `pagingSchedule` of `SAL3` means we should ignore the location's library code and use the paging schedule code instead.

**Comment by saseestone** [comment]
The Location details for these locations have been updated EXCEPT for SPEC-SAL3-MSS.  That location is being handled by Aeon, and therefore has the location detail "pageAeonSite" = SPECUA
