### ISSUE TITLE
[sul-requests/folio-dev] RuntimeError: Hold request request for user_id: 562a5cb0-e998-4ea2-80aa-34ac2b536238, item_id: 3296cea8-a0a9-59b9-87f3-12384c0d2ca1 was not successful. status: 422, {
  "errors" : [ {
    "message" : "Cannot find a valid request type for this item",
    "parameters" : [ {
      "key" : "itemId",
      "value" : "3296cea8-a0a9-59b9-87f3-12384c0d2ca1"
    } ]
  } ]
}

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/sul-requests#1664]
## Backtrace

    line 184 of [PROJECT_ROOT]/app/services/folio_client.rb: check_response
    line 105 of [PROJECT_ROOT]/app/services/folio_client.rb: create_item_hold
    line 108 of [PROJECT_ROOT]/app/jobs/submit_folio_request_job.rb: place_item_hold

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/49963/faults/98810485)

**Comment by jcoyne** [comment]
This occurred when I went to https://requests-folio-dev.stanford.edu/admin/ART and tried to approve https://searchworks-folio-dev.stanford.edu/view/10386182
<img width="1267" alt="Screenshot 2023-08-03 at 8 24 05 AM" src="https://github.com/sul-dlss/sul-requests/assets/92044/4ab8f4fc-af29-4fb6-959c-a74e000bef2f">

**Comment by thatbudakguy** [comment]
pending @saseestone convo with circ staff about what to do

**Comment by saseestone** [comment]
Circ staff will be editing the circrules to r allow-paging-hold for any circrule lines that currently have r allow-paging

They will also start generating a report for items that are currently available on shelf, but have an open request with request type = hold.
