### ISSUE TITLE
Submit Reshare requests even when the ILS is unavailable

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/sul-requests#1671]
We should be able to submit reshare requests for eligible patrons when the ILS is unavailable. One step in submitting the reshare request is validating the patron's eligibility; we're currently doing that by checking whether the ILS has a `university_id` on file.

## Backtrace

    line 157 of [PROJECT_ROOT]/app/jobs/submit_symphony_request_job.rb: patron_barcode
    line 209 of [PROJECT_ROOT]/app/jobs/submit_symphony_request_job.rb: generic_request
    line 220 of [PROJECT_ROOT]/app/jobs/submit_symphony_request_job.rb: block in place_hold_params

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/49963/faults/98842632)

**Comment by saseestone** [comment]
I will connect with Resource Sharing staff about:
- Can we pass the Symphony Library ID (barcode provided by user in the request form)?

If not, can RS staff do a user lookup.  We won't be able to check/get the Univ ID number for the request.

**Comment by saseestone** [comment]
Resource Sharing staff have indicated that passing the Library ID on to ReShare will cause issues. We should pass requests to BorrowDirectly only for authenticated users. 

Users that input a Library ID into a Hold/Recall form should have their request queued up for placement in FOLIO once it is live.
