### ISSUE TITLE
Update confirmation mailer for Blocked user

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/sul-requests#1737]
Currently, we're sending a mailer to Blocked users indicating that we can't process their request.  We show this statement for both Hold/Recall and PAGE requests. But then we do actually process their requests. 

Mailer is here: https://github.com/sul-dlss/sul-requests/blob/d9a33f8cf6063f94e4386f53e3432b2ae2a79282/app/views/request_status_mailer/request_status_for_u003.html.erb

We should:

- [x] update the first line in the body of the text to read: 

Your library account is currently BLOCKED. Request assistance by replying to this email, or check [My Account](https://mylibrary.stanford.edu/) for more information. 

We will process your request, but your account must be in good standing to pickup the item."

- Then show the Call Number block

- [x] Remove the statement after the Call Number and item list that reads "Even though your status is blocked, you are eligible for Scan to PDF. You can request a single article or chapter, up to 50 pages." and remove the link to scan version of the request . 

- Keep the "Request was placed:...", "Questions about your requests" and the Contact info.

**Comment by alundgard** [comment]
This sounds good to me! [This branch](https://github.com/sul-dlss/sul-requests/tree/mailer-blocked-user) reflects these changes (with a slight grammatical edit: "pick up"). Please feel free to use them or not. However, corresponding changes must be made to the [test suite](https://github.com/sul-dlss/sul-requests/blob/mailer-blocked-user/spec/mailers/request_status_mailer_spec.rb), which is getting outside of my wheelhouse.
