### ISSUE TITLE
Show + handle temporary locations

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/sul-requests#1776]
This item has 2 items that are on course-reserve. The items on course reserve should not be pageable (because their current circ rule doesn't allow it)

https://requests.stanford.edu/pages/new?item_id=13956859&origin=LAW&origin_location=STACKS-1

I believe the current implementation is basically “look at what the item status has to say about its availability”. The app  groups items by their permanent location (because searchworks does it).. and usually permanent location is good enough to figure out the circ rules.

However:
if an item has an effective location/material type/etc that doesn’t allow paging, holds or recalls (under the circ policy…), we need to:
- show the temporary location (just/kinda like we do in searchworks)
- disable the checkbox for the item
- ??

**Comment by thatbudakguy** [comment]
Should the UI for this look similar to how it does for checked out items, except that you can't actually check the box? Or do we not need the ability to expand the status by clicking on it?

![Screenshot 2023-08-30 at 11 10 42](https://github.com/sul-dlss/sul-requests/assets/4924494/5b61f7a7-cf8b-4e60-b753-59b22fada7ae)
