### ISSUE TITLE
Support receiving a FOLIO location code instead of the Symphony library + location code

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/sul-requests#1789]
Requests currently receives the Symphony library (`origin`) + location code (`origin_location`). It should be sufficient to pass the FOLIO location code (either as `origin` or `origin_location`, a new query parameter, or maybe just bake it into the URL?)

Until we fully migrate over, we need to keep full backwards compatibility with the Symphony codes too.

**Comment by thatbudakguy** [comment]
The implementation should support both codes simultaneously.
