### ISSUE TITLE
Implement🚦MVP for FOLIO

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/sul-requests#1792]
![Image](https://github.com/sul-dlss/sul-requests/assets/111218/359c654d-fadd-490b-8430-a09ba20b5b15)

MVP is a:

- form field where you can scan a barcode (and auto-submits if the barcode is 14 characters... or something more clever?)
- check in FOLIO whether the item is checked out or not
- if the item isn't checked out, play a noise.
- a rolling log (with the most recent entries at the top.. expiring entries after 3 minutes?) that displays:
  - the scanned barcode
  - either "green check emoji" if the item is checked out, or "STOP:" if the item isn't
  - the item's title if the item isn't checked out

There's additional nuance about patron groups and workflows (in process: https://docs.google.com/document/d/1G-o96CA0uig_ce8gk993IwirBH1bCv15TVfmooMfE38/edit), but the base implementation should be simple enough.

I think there's also an opportunity to improve the design + styling, and perhaps show more information about the item (in a "more details" model/panel/etc)?

We should be careful to not leak any patron information on this page. We might also choose to implement some form of authorization (webauth? ip restrictions?) in the future.

**Comment by thatbudakguy** [comment]
this is access services' "red light/green light" system that we've agreed to help out with fixing, which checks if books need to be checked out when patrons physically leave a library (using fancy scanner things).

**Comment by dlrueda** [comment]
Don’t forget that Lane and GSB barcodes are not 14 digits.  I think they start with 205 and 245 and are 11 digits

**Comment by shelleydoljack** [comment]
the perl script that runs this is `sirsi@bodoni /var/www/cgi-bin/CircCheck/circCheck.pl` not sure if looking at that would be helpful.

**Comment by saseestone** [comment]
This looks like a great starting point to me. I'm meeting briefly with Mario Pamplona (who manages the exit) and Tyler Mitchell (Green Circulation Operations Manager) at 1pm, and I've given them access to the document linked above.
