### ISSUE TITLE
Improve shelved-by-title call number display

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/sul-requests#1852]
https://requests.stanford.edu/pages/new?item_id=576562&origin=HOPKINS&origin_location=SHELBYTITL

<img width="662" alt="Screenshot 2023-09-19 at 07 47 50" src="https://github.com/sul-dlss/sul-requests/assets/111218/df41fb5e-ccfd-4a18-92d8-8dc1cc67e48b">

Callnumber `UNCLASSIFIED` isn't helpful (and doesn't appear in e.g. Searchworks that way). It should just say "Shelved by title" or similar.

**Comment by dnoneill** [comment]
closed by https://github.com/sul-dlss/sul-requests/pull/2438
