### ISSUE TITLE
Direct all hold/recall requests to ILLiad instead of ReShare or FOLIO

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/sul-requests#1889]
Access Services has been working with SUL branches and coordinates on a plan to direct all hold/recall requests to the SUL ILLiad environment for fulfillment. They are ready to move forward. 

ILLiad will determine the best course of action for the request (fulfillment via BorrowDirect, UC agreements, other ILL agreements, or placing a hold FOLIO) 

There are some preliminary docs that have been prepared to map SearchWorks fields with ILLiad fields: https://docs.google.com/spreadsheets/d/1bvMuOL4xDjAlXl-QjpsTWHf8Lc3icB7O3ED3FDmKvTQ/edit#gid=0

Work will also need to be done in My Library. An older ticket on that effort: https://github.com/sul-dlss/mylibrary/issues/300

**Comment by saseestone** [comment]
@thatbudakguy We haven't talked about how the request dashboard will look when requests are directed to ILLiad.  Can you confirm:

- Hold/recall requests will continue to be added to the request dashboard
- Will the status page for the request include information on the ILLiad response?

**Comment by thatbudakguy** [comment]
I will double-check, but to my knowledge nothing around this has changed, so it should all "just work". The functionality to show the ILLiad response will still be there, and the ILLiad response data should correctly get added when a Hold/Recall is sent to ILLiad.
