### ISSUE TITLE
[sul-requests/prod] NoMethodError: undefined method `callnumber' for nil:NilClass

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/sul-requests#1903]
## Backtrace

    line 9 of [PROJECT_ROOT]/app/views/application/_item_selector.html.erb: block in _app_views_application__item_selector_html_erb__2102414554257885310_46680
    line 2 of [PROJECT_ROOT]/app/views/application/_item_selector.html.erb: _app_views_application__item_selector_html_erb__2102414554257885310_46680
    line 6 of [PROJECT_ROOT]/app/views/requests/_form.html.erb: block in _app_views_requests__form_html_erb___2803922545306347340_46600

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/49963/faults/88982212)

**Comment by jcoyne** [comment]
This occurs because their are no holdings found in the specified location:

```
hr = HoldRecall.new(origin: 'BUSINESS', item_id: '14261607', origin_location: 'BUS-CRES', barcode: '20503757316')
hr.all_holdings.send(:items_in_location)
 => []
 ```
 
 I think this is because the folio_location_code is nil
 ```
 hr.library_location.folio_location_code
 => nil
 ```

**Comment by cbeer** [comment]
This is still happening.
