### ISSUE TITLE
Truncate title to one line w ellipsis ...

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-requests#191]
Add to h2 title:
```
white-space: nowrap;
overflow: hidden;
text-overflow: ellipsis;
```

Before
![full title](https://cloud.githubusercontent.com/assets/6945691/8362778/c045d64c-1b2f-11e5-954a-166d1fcc4a0d.png)

After
![truncated title](https://cloud.githubusercontent.com/assets/6945691/8362781/c540a938-1b2f-11e5-8510-8dff0f879542.png)

**Comment by cbeer** [comment]
Do we need a way to reveal the full title at all?

**Comment by jvine** [comment]
I'm suppressing the full title because a) some are long enough that most of the form will be hidden when they open the popup, and b) they will generally be in the context of the record in SW when they open the popup - so it's more confirmation than information.

That said, if there's a simple way to do display the full title on (say) hover without moving the other content on the page, it would not be a bad thing. (But not the browser default tooltip showing the title attribute, please.)
