### ISSUE TITLE
Mediated-page form layout

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-requests#192]
* [x] Make a form-group div for the unlisted items field. Label is "Add unlisted items". 
* [x] Move the "Refer to" instructions below the field, like so:
```<p class="help-block">Refer to the collection's Finding Aid to identify the items you need.<br>Example: Series 1, Box 1</p>```
* [x] Make a form-group div for the Selected items list. Label is "# items selected".
* [x] Switch the order of the date and comment fields.
* [x] "Needed on" should be "Planned date of use"

![screen shot 2015-06-25 at 1 39 53 pm](https://cloud.githubusercontent.com/assets/6945691/8365078/b55b01ac-1b3f-11e5-9b55-286932ecf9dd.png)

**Comment by cbeer** [comment]
>  Switch the order of the date and comment fields.

Just to be clear, what order do you want them in?

**Comment by jvine** [comment]
Date, then comments. Or, stated differently: comments last before the submit button.

![screen shot 2015-06-30 at 1 31 13 pm](https://cloud.githubusercontent.com/assets/6945691/8441340/706b20b8-1f2c-11e5-9ca0-a4b3837e750e.png)
![screen shot 2015-06-30 at 1 31 01 pm](https://cloud.githubusercontent.com/assets/6945691/8441341/706c870a-1f2c-11e5-8736-11482f08784c.png)
