### ISSUE TITLE
Fix request parameter rewriting in rails 7.1.x

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/sul-requests#1934]
It seems that in rails 7.1 our HTTP request parameters are being rewritten during the delegation process, where e.g.:
> https://requests.stanford.edu/requests/new?a=b&c=d

should become
> https://requests.stanford.edu/hold_recalls/new?a=b&c=d

but instead becomes (note ampersand)
> https://requests.stanford.edu/hold_recalls/new?a=b&amp;c=d

this causes the parameters to be parsed incorrectly by the receiving controller:
```
Started GET “/hold_recalls/create?request[barcodes][36105231817524]=1&amp;request[destination]=GREEN-LOAN&amp;request[item_id]=in00000001563&amp;request[needed_date]=2024-10-23&amp;request[origin]=SAL3&amp;request[origin_location]=STACKS”
Parameters: {“request”=>{“barcodes”=>{“36105231817524”=>“1"}}, “amp;request”=>{“destination”=>“GREEN-LOAN”, “item_id”=>“in00000001563”, “needed_date”=>“2024-10-23”, “origin”=>“SAL3”, “origin_location”=>“STACKS”}}
```

this behavior originates here:
https://github.com/sul-dlss/sul-requests/blob/e1276a5e579215e19e8a2f6df145b09a6cb4bf27/app/controllers/requests_controller.rb#L148-L153

**Comment by thatbudakguy** [comment]
we can't replicate this problem locally, so it may interact with some configuration on our servers (Apache?)

**Comment by cbeer** [comment]
Were you able to reproduce this on requests-dev? I deployed https://github.com/sul-dlss/sul-requests/pull/1950 there and can't reproduce. Do you have example requests that this happened on?

**Comment by thatbudakguy** [comment]
My memory is that we replicated and fixed this on stage; I don't think we did anything with dev. When I was testing, I did so with https://searchworks.stanford.edu/view/in00000001563. That resulted in https://app.honeybadger.io/projects/49963/faults/101591418/01HDEW0GXPZ486GB2K9862T6WT.

**Comment by cbeer** [comment]
I see; it's not the redirect from `requests/new` to `hold_recalls/new`, but actually submitting the form?

**Comment by thatbudakguy** [comment]
That would make sense! I just saw that the params from SW were coming in correctly but getting messed up somewhere inside requests, and assumed it was during request type delegation.

**Comment by hudajkhan** [comment]
Note: Chris may have a PR already for this which requires review/rebasing.

**Comment by mjgiarlo** [comment]
@hudajkhan @cbeer Can y'all confirm whether there is a PR for this already?

**Comment by jcoyne** [comment]
The PR was https://github.com/sul-dlss/sul-requests/pull/1950 AFACT
