### ISSUE TITLE
"Don't have a SUNet ID?" formatting

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-requests#195]
* [x] "Don't have a SUNet ID?" should be an h3.
* [ ] h3 font size should be 1.3em (not 24px) - computed size is ~18px
* [x] this specific h3 should have a 1em top margin

(I can't figure out how to make anything space correctly after the red button without adding a `<div class="clearfix">` immediately after the button... that doesn't seem right?)

![screen shot 2015-06-25 at 4 06 08 pm](https://cloud.githubusercontent.com/assets/6945691/8367580/92772818-1b54-11e5-9c3d-dd253170dcb6.png)

**Comment by jkeck** [comment]
h3 font size will be addressed in a separate ticket
