### ISSUE TITLE
Remove "Deliver to [library]" from Scan request

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-requests#199]
Scan form is showing the Deliver to select control... shouldn't be present for scan requests. 

![screen shot 2015-06-29 at 1 24 25 pm](https://cloud.githubusercontent.com/assets/6945691/8417550/3ac5fe30-1e62-11e5-9162-6aa490d70d67.png)

![screen shot 2015-06-29 at 1 25 03 pm](https://cloud.githubusercontent.com/assets/6945691/8417568/4afccc98-1e62-11e5-82e7-fb0e2993ca57.png)

**Comment by jkeck** [comment]
I actually noticed this and am working to resolve this in the PR that I'm working on right now.
