### ISSUE TITLE
Item selector: if displaying a Bound-with, communicate about its parent

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/sul-requests#1998]
See https://github.com/sul-dlss/SearchWorks/issues/3200 for more context

This would be if one item in the selector is a Bound-with
There may be existing UI code for showing extra data around an item

For example, if one of these was a Bound-with, we would show info about the parent in this same space (which is the book/title you will end up receiving)
<img width="721" alt="Screenshot 2024-01-31 at 5 05 37 PM" src="https://github.com/sul-dlss/sul-requests/assets/1328900/98813396-9aff-4bcc-a4f5-20b357bf72f5">

**Comment by dbranchini** [comment]
Screens have been designed to display a bound-with item request when there are multiple items and an item selector screen. See two example screenshots below:

<img width="640" alt="Screenshot 2024-02-29 at 11 35 20 AM" src="https://github.com/sul-dlss/sul-requests/assets/6816624/eb7b6d6a-c96e-4f83-9b60-7fc2ded34ca0">

<img width="716" alt="Screenshot 2024-02-29 at 11 31 19 AM" src="https://github.com/sul-dlss/sul-requests/assets/6816624/f97a9224-31bc-45c8-a739-4c5435ee2b8b">

**Comment by dbranchini** [comment]
**Design specifications:**

Mainly, the display is carried over from SearchWorks for consistency using the current layout/styles that exist in the Request app for the item selector. Each item should be expanded (not collapsed) by default.

**Comment by dnoneill** [comment]
Believe this was closed with https://github.com/sul-dlss/sul-requests/commit/85a26958327fa583a01b803a2e564c1dc160a0e7
