### ISSUE TITLE
Order items appearing in volume picker same (or similar) to how they display in SearchWorks record view

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/sul-requests#2002]
When displaying the "volume picker" feature, which allows the user to indicate which volume or specific copy they want to request, we should be ordering the items as they appear in the SearchWorks record view.

@dbranchini has a good example record for when the sort order changes.

**Comment by dbranchini** [comment]
It's this record - https://searchworks.stanford.edu/view/5490833. Screenshots follow. 

**Record view - descending order:**
<img width="375" alt="Screenshot 2024-02-07 at 4 26 31 PM" src="https://github.com/sul-dlss/sul-requests/assets/6816624/d2824acb-1692-4762-b54b-4785162a273c">

**Record view - ascending order:**
<img width="478" alt="Screenshot 2024-02-07 at 4 26 46 PM" src="https://github.com/sul-dlss/sul-requests/assets/6816624/deaef1cc-f70e-4eef-8e69-e44685dfb2e0">

**Comment by dbranchini** [comment]
See #2005 for related display issue in requests app
