### ISSUE TITLE
Change limit plus copyright notice on scan to PDF requests

### ISSUE THREAD

**Issue by dbranchini** [sul-dlss/sul-requests#2017]
## Problem Statement

Stakeholders have requested copy edits to two statements - scanning limitations and copyright notice - on two pages - the _Request option_ and the _Scan to PDF request_ screens. Revisions are requested in order to make these statements more accurate.

## Solution

The description regarding the **scanning limitations** should be revised on two pages - the _Request option_ and the _Scan to PDF request_ screens (see screenshots) as follows:

> Limited to one article/chapter, not to exceed 50 pages or 10% of the work

The **copyright notice** should be revised on the _Scan to PDF request_ screen as follows:

> **Copyright notice**

> The copyright law of the United States (title 17, United States Code) governs the making of photocopies or other reproductions of copyrighted material. Under certain conditions specified in the law, libraries and archives are authorized to furnish a photocopy or other reproduction. One of these specific conditions is that the photocopy or reproduction is not to be “used for any purpose other than private study, scholarship, or research.” If a user makes a request for, or later uses, a photocopy or reproduction for purposes in excess of “fair use,” that user may be liable for copyright infringement. Stanford Libraries reserves the right to refuse to accept a copying order if, in its judgment, fulfillment of the order would involve violation of copyright law.

---

**User flow:**

1. From this page - https://searchworks.stanford.edu/view/524199
2. Click Request in the At the library > SAL3 card
3. Goes to Request options screen
4. Click Scan to PDF
5. Goes to the Scan to PDF request screen

**Screenshots:**

![Image](https://github.com/sul-dlss/sul-requests/assets/6816624/786498f5-9a61-4880-8ca4-9fafe4a737f3)

![Image](https://github.com/sul-dlss/sul-requests/assets/6816624/f842e63c-dae7-456b-bcfe-ecb57ea32040)

---

This ticket summarizes a request and discussion with stakeholders captured here - https://docs.google.com/document/d/1iXGmNf5MuEwjdpIOD7jF1PVFhZScULgufxVKBm1VugI/edit.

**Comment by dbranchini** [comment]
We are waiting for stakeholders' final okay on the exact wording for these changes.

**Comment by taylor-steve** [comment]
@dbranchini I have screenshots in my draft PR https://github.com/sul-dlss/sul-requests/pull/2020. Look right to you?
