### ISSUE TITLE
intermintent issue with all_holdings

### ISSUE THREAD

**Issue by dnoneill** [sul-dlss/sul-requests#2037]
Sometimes [all_holdings returns none?](https://github.com/sul-dlss/sul-requests/blob/8c717d1a55697b81e6e7e95e0917f366868e387f/app/views/application/_item_selector.html.erb#L3) which means that the call number does not display on the page. This is happening in production. The result I see it most on is https://requests.stanford.edu/hold_recalls/new?item_id=6290245&origin=GREEN&origin_location=GRE-STACKS. 

The way I was able to replicate the result was go to the URL for a different request (https://requests.stanford.edu/pages/new?item_id=2279186&origin=SAL3&origin_location=SAL3-STACKS) and then reload the url for https://requests.stanford.edu/hold_recalls/new?item_id=6290245&origin=GREEN&origin_location=GRE-STACKS. What I see is below and for some reason the folio id is for the 2279186 record not the 6290245.

![Screenshot 2024-03-08 at 2 53 33 PM](https://github.com/sul-dlss/sul-requests/assets/19173991/4c91b638-d238-42a3-968d-50e398ba9949)

**Comment by corylown** [comment]
Maybe we're memoizing or caching something we shouldn't be?

**Comment by dnoneill** [comment]
@corylown I think I found it in the bound-with branch https://github.com/sul-dlss/sul-requests/compare/832b97533cb25cb1a0c3085b2c87dc6b9cd6d8b2..3990918bf988048594fe2639193dcede1f6d95d9. I am not quite sure why it is happening on production yet.

**Comment by dnoneill** [comment]
Actually might have just been a branch issue. http://localhost:3000/hold_recalls/new?item_id=6290245&origin=GREEN&origin_location=GRE-STACKS doesn't have any items on main so it shouldn't be showing holdings so I think we can probably close this issue.
