### ISSUE TITLE
Need 'dejavu_sansextralight' font for titles w diacritics

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-requests#204]
The h2.searchworks-item titles need to be in 'dejavu_sansextralight' to avoid yucky diacritics. (cf. SearchWorks)

![screen shot 2015-06-29 at 4 40 19 pm](https://cloud.githubusercontent.com/assets/6945691/8420965/92468952-1e7d-11e5-845b-72168cd40d48.png)
![screen shot 2015-06-29 at 4 39 51 pm](https://cloud.githubusercontent.com/assets/6945691/8420966/924c45f4-1e7d-11e5-9961-0e927a99c928.png)

**Comment by mejackreed** [comment]
If this gets implemented, we should seriously consider consolidation of our fonts, icon sets to a common static file system. This would make the 3rd endpoint to make use of this font.
