### ISSUE TITLE
Update sul-requests list.js search to not include index

### ISSUE THREAD

**Issue by dnoneill** [sul-dlss/sul-requests#2046]
This might not be possible. When we updated the call number we had to use an index value for the list.js sort. It got added here: https://github.com/sul-dlss/sul-requests/blob/7cb6f9b6ab04a2da1f78705474ec1d34d2357fc9/app/javascript/item_selector/item_selector_filtering.js#L7. Unfortunately the addition also meant that field is searchable. In list.js there is a way to search only a single field but figuring out how to implement it is going to be the real issue. https://listjs.com/api/

**Comment by hudajkhan** [comment]
Associated PR references https://listjs.com/api/#searchColumns
