### ISSUE TITLE
Confirmation page formatting

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-requests#205]
* [ ] Confirmation page currently has 2 `<dl>`s. Can these be merged into one list?
* [x] Username/email should be visually formatted like an h2 
```
  color: #8c1515;
  font-size: 1.6em;
  letter-spacing: 0;
  line-height: 1.2em;
  font-weight: 300;
```
 * [x] Hidden dt label for username is currently "User" - pls change to "Requested by"

![page recall confirmation](https://cloud.githubusercontent.com/assets/6945691/8421250/e512a082-1e80-11e5-8442-61d33209322b.png)

**Comment by cbeer** [comment]
>  Confirmation page currently has 2 `<dl>`s. Can these be merged into one list?

As discussed -- these `<dl>`s are coming from two different partials that are shared between the the status + success pages.
