### ISSUE TITLE
Aeon interstitial page constructs bad url

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/sul-requests#2059]
Items in FOLIO location = SAL3-PAGE-AS have a location details key `pageAeonSite` with a value of `ARS`

Using that loc details, we send the request off to Aeon, but through sul-requests so the user see's the Aeon interstitial page: https://requests.stanford.edu/aeon_pages/new?item_id=11060578&origin=SAL3&origin_location=SAL3-PAGE-AS

That interstitial page has a link at the bottom for more information. 
![image](https://github.com/sul-dlss/sul-requests/assets/14897546/c5108229-1849-477a-ae2b-706f518bdfba)

For items in this location, that link loops the user back to the interstitial page. :(

When g-core looked at this in Nov 2023, Chris thought that link was being constructed based on the library of the permanent loc. That's why it tries to send you to the "SAL3 (off-campus storage) Reading Room service page".  

IF we keep this Aeon interstital page, we should use the loc details value of `ARS` to know that ARS manages this location, and construct the url (and link to the information page) based on that value. Not the perm library of the location. 

JIRA issue of original report: https://jirasul.stanford.edu/jira/browse/SW-4259

**Comment by hudajkhan** [comment]
This line defines the location: 
https://github.com/sul-dlss/sul-requests/blob/main/app/views/aeon_pages/_info_modal.html.erb#L18

The parameters are library which gets the name for the origin library code and reading_room_url is the reading room for the library corresponding to the origin library code.
