### ISSUE TITLE
Broadcast messages formatting

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-requests#206]
Finding the current layout a bit hard to scan/read.

 * [x] Indent the "messages" div by 2em
 * [x] give .status `color: #8c1515`
 * [x] give .active `color: green' and 'font-weight: bold'
 * [x] can we make the text area `class="alert alert-warning"` instead of `well` so it looks the way it will it context?
 * [x] The message types are all currently h2s, which is semantically okay but visually a bit overwhelming. 
 * option 1: style the h2s in this context with `color: #000; font-size: 1.2em; font-weight: normal;`
 * option 2: make them not h2s, but links to the edit form (and style the links with `font-size: 1.2em;`) 
 * [x] I'd like the add/edit link more strongly associated with the request type - 
 * option 1: move the link beside the heading, possibly style it as a button
 * option 2: do option 2 above.

### With buttons

![broadcast messages formatting buttons](https://cloud.githubusercontent.com/assets/6945691/8421617/49dc2e52-1e86-11e5-949d-bf9ebb48a895.png)

### Message types as links

![broadcast messages formatting links](https://cloud.githubusercontent.com/assets/6945691/8421620/50ac84ac-1e86-11e5-8fe9-17f863835f40.png)

**Comment by jgreben** [comment]
I got this mostly done, but the button font has weird spacing after adding in the glyphicon:

![screen shot 2015-08-13 at 10 45 25 am](https://cloud.githubusercontent.com/assets/3093850/9257095/88194b38-41a8-11e5-85ce-9053bee2f7e9.png)

**Comment by jvine** [comment]
Also now you have links AND buttons - with explicit buttons, the "Page from..." text should just be h2s.

**Comment by jgreben** [comment]
OK I removed the links and left the buttons, but there is still extra spacing between the words...

**Comment by jgreben** [comment]
Closed by PR #288
