### ISSUE TITLE
Automatically detect logged in users

### ISSUE THREAD

**Issue by dnoneill** [sul-dlss/sul-requests#2128]
When just going to a url it makes you login if you don't have &step=select in the url. We should probably redirect if the user is logged in.

![Screenshot 2024-04-03 at 12 31 34 PM](https://github.com/sul-dlss/sul-requests/assets/19173991/486ee526-1200-4d4b-8195-556babb8ef9c)

**Comment by cbeer** [comment]
I suspect we want to always send users through this, e.g. in case someone needs to use their library id. Probably needs more conversation with @dbranchini and @saseestone

**Comment by thatbudakguy** [comment]
As of standup today we think that the only cases where we would _not_ want to do this are now solved:
- for proxies/sponsors, the need to use a separate account is resolved by FOLIO's structure, so they do not need to use library ID
- for people with a shib account but not a FOLIO account, they can't do anything useful anyway, so we should kick them back out (#2171)
