### ISSUE TITLE
add barcode to serialized field not patronrequest

### ISSUE THREAD

**Issue by dnoneill** [sul-dlss/sul-requests#2130]
If the url has a barcode it is being passed to requests_patron. This is causing an error when it happens.

**Comment by cbeer** [comment]
I think this happens for item-level request links for hold/recall, so it's something we'll need to account for. I don't think we can just remove it.

**Comment by dnoneill** [comment]
https://stanfordlib.slack.com/archives/G018TJ20XGE/p1712000082213759

**Comment by cbeer** [comment]
👍 . I hope we can just shove it in the existing `data` field instead of creating another database field.
