### ISSUE TITLE
Fix location estimate to say no estimate for items we have no estimate for

### ISSUE THREAD

**Issue by dnoneill** [sul-dlss/sul-requests#2132]
http://localhost:3000/patron_requests/new?instance_hrid=14720993&origin_location_code=GRE-STACKS&step=select

When you load this page the estimated delievery date keeps saying loading.... because http://localhost:3000/paging_schedule/GRE-STACKS/GREEN-LOAN returns an error. We should update the estimate to provide a no estimate available if this is true.

**Comment by cbeer** [comment]
I suspect I fixed this with https://github.com/sul-dlss/sul-requests/pull/2131/commits/2b3f0cb663c43e221934b1368ea92062b078b332 (part of #2131).

**Comment by dnoneill** [comment]
@cbeer It does not.
