### ISSUE TITLE
Integrate the request type picker (when applicable) into the request form

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/sul-requests#2155]
![Image](https://github.com/sul-dlss/sul-requests/assets/111218/8797c960-b1db-47db-a8cc-a01e085e5a73)

Existing work (on the inner content) was done in https://github.com/sul-dlss/sul-requests/pull/2142, but needs to be integrated with e.g. an accordion.

Also: the next accordion will display different information based on the current selection

Statefulness in these settings that would push us in a JavaScript direction. 

Candidate for group work aka swarming

**Comment by thatbudakguy** [comment]
- [ ] sketch out the html for all the possible steps on the request page after you are auth'd (render all steps except first as hidden)
- [ ] for cases where there is no chance you could do something, don't bother rendering it
- [ ] for cases where there are multiple request types, render all the corresponding request details steps ("versions" of the step)

**Comment by dnoneill** [comment]
closed with https://github.com/sul-dlss/sul-requests/pull/2181
