### ISSUE TITLE
Give proxy sponsors the ability to choose whether the request is personal or for the group

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/sul-requests#2156]
![Image](https://github.com/sul-dlss/sul-requests/assets/111218/73bc5be6-1c71-44c1-acca-fe1b32d44e85)

**Comment by hudajkhan** [comment]
The Figma image has been updated since the screenshot above.

**Comment by saseestone** [comment]
Noting that Huda and I determined that in the FOLIO call to retrieve details on the Proxies, if "requestForSponsor" = no, then we should not include that proxy on the form (in the list of Proxies).

The "requestForSponsor" relates to a field in the FOLIO UI that asks staff to indicate if a proxy should be able to place a FOLIO request on behalf of the Sponsor (in addition to checking an item out on behalf of a sponsor).  If the staff have indicated "no", then we should not list the proxy on our Request form.

Here's a snapshot of the FOLIO UI: 
<img width="546" alt="image" src="https://github.com/sul-dlss/sul-requests/assets/14897546/0462efb9-3ad7-4565-93d1-6a22a7d18afa">
