### ISSUE TITLE
Build out the item selector

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/sul-requests#2157]
Build out the item selector:

![Image](https://github.com/sul-dlss/sul-requests/assets/111218/73621d4f-3c61-41ff-9b73-f091e0f0921a)

Some existing work is in https://github.com/sul-dlss/sul-requests/pull/2150, but needs to be fleshed out with, e.g.:
- styling
- availability information
- item public notes
- appropriate call number sorting
- single vs multiple selections

**Comment by saseestone** [comment]
Darcy pointed out that in the prototype there are scenarios (based on user type & circrules) there may be disabled items on the list.

**Comment by hudajkhan** [comment]
Broken out into multiple issues:

- #2182 
- #2183 
- #2184 
- #2185 
- #2186

**Comment by dnoneill** [comment]
Pretty sure this can be closed
