### ISSUE TITLE
Pickup request selection

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/sul-requests#2158]
Darcy changed the visual (per comments below): 
![Image](https://github.com/sul-dlss/sul-requests/assets/6816624/c80c93cd-b7f5-409d-948f-eac72b7cdc1a)

**Comment by hudajkhan** [comment]
Started on related work in #2150

**Comment by saseestone** [comment]
Red x - could we add an "Are you sure?"

**Comment by hudajkhan** [comment]
Useful to be able to change selections on this page, e.g. once the user sees something is not available when they look at this page, they may wish to remove it

**Comment by saseestone** [comment]
Darcy will put another visual in here that doesn't include the speed question for each unavailable item.

**Comment by dbranchini** [comment]
After the user removes an item, a toast appears at the bottom right of the screen with the option to undo your last action. 


![Image](https://github.com/sul-dlss/sul-requests/assets/6816624/c4447c8a-6119-4a9b-9a5b-acd0db71fd24)

**Comment by thatbudakguy** [comment]
I split the remaining parts of this ticket into #2236 and #2237. Closing, since the rest is done.
