### ISSUE TITLE
Finish populating confirmation pages for the different types of requests

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/sul-requests#2159]
Preliminary work was done in https://github.com/sul-dlss/sul-requests/pull/2154, but needs additional:
- additional logic to account for the different types of requests (scan vs page vs hold/recall vs mediated page)
- style refinement
- item-level information

**Comment by hudajkhan** [comment]
There may be an additional design screen added for this (multiple item screen)

**Comment by thatbudakguy** [comment]
Note that the confirmation page design also shows the call number next to the title in parentheses if it was a single item, which we don't currently do.

**Comment by saseestone** [comment]
I think in prod, we might not be sending confirmation mailers for some request types. After conversations with ILL, I think we need to plan to send a confirmation mailer for all request types from request app. 

It may result in multiple process emails sent to the user (e.g. one from request app, another from ILLiad alerting the user that BD or ILL will be used to fulfill the request, etc.) but more seems better than a.) confusion about what app is sending what and b.) reliance on other library departments to actually send confirmations.
