### ISSUE TITLE
Proxy.pl script returns Group Notice Master Email address

### ISSUE THREAD

**Issue by jgreben** [sul-dlss/sul-requests#216]
This is currently in test on Morison:
http://morison.stanford.edu/cgi-bin/proxy.pl?libid=[REDACTED]

returns:

SEESTONE_SARAH|SPONSOR|seestone@stanford.edu|

(Question: will adding a third index break whatever currently uses this in production?)

**Comment by cbeer** [comment]
:+1: looks good to me. I can't speak to all production uses, but the current requests app should be fine with the change.
