### ISSUE TITLE
Send recalls to ILL for some FOLIO item statuses

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/sul-requests#2160]
For the expedited case. Only for particular FOLIO patron groups, requesting materials that are not on shelf.

We should check in FOLIO if there are other requests on the Stanford copy. If yes, direct to ILLiad. 
If no other requests, and item has a FOLIO Item status of:

- Checked out
- Missing
- Aged to lost
- Claim returned
- Declared lost
- Long Missing
- Lost and paid
- Paged

Send request to ILLiad

**Comment by hudajkhan** [comment]
Note: For the "expedite this" case

**Comment by saseestone** [comment]
FOLIO user groups that are eligible for the request to go to ILLiad (either for hold/recall requests or scan requests):

- faculty
- fellow
- graduate
- postdoctoral
- staff
- undergrad
- visiting scholar

**Comment by thatbudakguy** [comment]
moved the request queue piece of this to #2234
