### ISSUE TITLE
Broadcast messages aren't displaying in the new design

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/sul-requests#2211]
We should display Broadcast messages on the new forms. And it's likely to need a little design tweaking by @dbranchini 

Reminder that broadcast messages are related specifically to requests, and tend to be messages about disruptions in request services that are outside application/system outages. Examples: a building needs to close unexpectedly due to wildfire smoke or a leak, the SAL3 delivery truck is unavailable, or we're closed for Winter Break. 

To create broadcast messages, go to http://requests.stanford.edu/messages or https://requests-dev.stanford.edu/messages

Beyond parity: 
We've had feedback that it would be good to include broadcast messages on the confirmation message and in the confirmation email that is sent.

**Comment by saseestone** [comment]
Sarah & Darcy just [created "Page anywhere" and "Scan anywhere" messages](https://requests-dev.stanford.edu/messages), and neither are appearing.

**Comment by cbeer** [comment]
Do we need request-specific broadcast messages, or is origin-specific messaging sufficient (now that users don't pick the request type up-front, displaying type-specific messages would take more work...)?

**Comment by saseestone** [comment]
@cbeer you're completely right that it makes most sense to only have origin (e.g. owning library) specific messages and not "page anywhere" vs. "scan anywhere" messages. We'll just have one message that appears based on "all" or a specific library, and the text of the message will need to indicate what services (page or scan) are effected.

Does that track with what you did?
