### ISSUE TITLE
Apply 5-item limit to PAGE-SP items

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-requests#222]
Request from Spec: Items that can be paged to Spec should have the same 5-item max as SPEC-COLL items.

PAGE-SP example
http://searchworks.stanford.edu/view/1556354
PAGE-AR example
http://searchworks.stanford.edu/view/358069

**Comment by cbeer** [comment]
@jvine with `PAGE-AR`, we mean to enforce the 5-item limit even when `ART` is the destination library?

**Comment by jvine** [comment]
That's why I put the issue in the icebox. I don't think Art cares, but will verify. If they specifically do not want a limit, then we need different behaviour; and I think this is not a high-frequency issue for Spec.

**Comment by jvine** [comment]
Response from Art on this was that they would prefer not to have a limit, but would accept the same limit as Spec if necessary. Recommend that we leave this as-is (no limit on PAGE-* items) for now.
