### ISSUE TITLE
Mediated page case: origin=HV-ARCHIVE&origin_location=STACKS-30

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-requests#223]
Hoover Library and Hoover Archive have examples of items with origin of HOOVER or HV-ARCHIVE and a STACKS-30 location that means the items are at SAL3. This means they need a mediation workflow.

Example HV-ARCHIVE item:
http://searchworks.stanford.edu/view/6193580

Doesn't just magically work, sadly:
https://requests-dev.stanford.edu/pages/new?item_id=6193580&origin=HV-ARCHIVE&origin_location=STACKS-30

**Comment by jkeck** [comment]
@jvine just out of curiosity did you just update the URL with those params?  When I go to https://requests-dev.stanford.edu/requests/new?item_id=6193580&origin=HV-ARCHIVE&origin_location=STACKS-30 (the URL that SearchWorks will use) I am delegated to the correct mediated page form.  It's possible that we may need to do something to prevent users from getting to the page form (by hacking the URL) for an item that is not pageable (which is perhaps what this ticket should be about).

**Comment by jvine** [comment]
Oh you're right! Whew.
