### ISSUE TITLE
Allow the user to undo removal of items from the request

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/sul-requests#2236]
Extracted from #2158.

The designs have a system where the user can click the "x" on the item labels/pills to remove it. When this happens, a toast appears notifying the user of what happened and offering them the ability to undo their choice.

![Image](https://github.com/sul-dlss/sul-requests/assets/6816624/c4447c8a-6119-4a9b-9a5b-acd0db71fd24)

**Comment by cbeer** [comment]
Fixes #2239
