### ISSUE TITLE
We need to send confirmation mailers

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/sul-requests#2240]
In testing, I've submitted several tests and haven't received a confirmation email. Are we sending them? If not, we should :) 

At first, I thought it was because the user record had a test email address (dlss-access-team...or foliotesting@...) But I've updated a couple of users to use my email address and the mailers haven't come.

**Comment by thatbudakguy** [comment]
The email is more or less a repeat of the info on the confirmation screen.

**Comment by thatbudakguy** [comment]
@saseestone received feedback today (from production) that patrons don't receive a confirmation mailer for scans. this could be because we assume(d) that ILLiad was sending emails and thus didn't want to send our own, but in fact ILLiad isn't sending them? more investigation needed.

**Comment by saseestone** [comment]
and we definitely need to send a mailer for all request types from request app.
