### ISSUE TITLE
Use FOLIO patron group "Description" field for text that appears after the user's name

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/sul-requests#2245]
If the user has a FOLIO account that is. If not, use "Visitor"

![Image](https://github.com/sul-dlss/sul-requests/assets/14897546/00050dcc-d4ab-4782-b60f-5d67cebec530)

Sarah is working with FOLIO administrators to update this field in FOLIO.

**Comment by thatbudakguy** [comment]
Done when @saseestone updates the appropriate descriptions in FOLIO. dev work is done

**Comment by saseestone** [comment]
Updates made in FOLIO test. Will get updates in FOLIO prod before release.
