### ISSUE TITLE
Ask proxies which sponsor should see the request, if any

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/sul-requests#2249]
We know when a proxy is a member of a group now (and there are designs).

**Comment by dbranchini** [comment]
![Image](https://github.com/sul-dlss/sul-requests/assets/6816624/21105cd4-2d60-4dd0-91a5-2d57ca17e7ef)

https://www.figma.com/file/sqzYVhfRgn3nMArUAdrs0n/SearchWorks?type=design&node-id=734-6908&mode=design&t=Wqp0woLgWDWuVYfg-4

**Comment by dnoneill** [comment]
@dbranchini Couple of questions:
1. I am assuming this should have a continue button like everything else and the reason it doesn't is just time.
2. Should the select a sponsor only show up if the user has selected "this is for a sponsor" or should it always be there (I definitely see how it can be helpful if someone isn't sure what a sponsor is).
3. Height of the sponsor (if the user has say 10 sponsers I am assuming we would want that to be a scroll and not the whole page. Based on this view I am guessing height caps at 4?).

**Comment by hudajkhan** [comment]
Regarding the questions above, the attached pull request maintains the continue button in that section and has the "select a sponsor" section show up when the user has selected the sponsor option.  The rest of the details are in the pull request.

I did not do anything for handling a longer list of sponsors.
