### ISSUE TITLE
Change visitor accounts to use the new visitor folio patron group

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/sul-requests#2258]
Currently we assign visitors the permissions of `sul-purchased`. Once the new `visitor` group in FOLIO is created, we can change to use that group's permissions. Then we can also remove the harcoded restriction that limits visitors to page requests, since that will become encoded as circ rules for the `visitor` group.

**Comment by dnoneill** [comment]
I think this is a backlog issue until circ creates a visitor group?

**Comment by saseestone** [comment]
I created the visitor group in folio-test, but circ folks need to populate the circ rules. I'll press on that today.

**Comment by saseestone** [comment]
Circ admins added one circulation rule for the new Visitor group in folio-test. It allows paging-holds for material type = Book for Loc = SAL3-STACKS.  Example records that we can use for testing:
https://searchworks-stage.stanford.edu/view/551208
https://searchworks-stage.stanford.edu/view/6728286
https://searchworks-stage.stanford.edu/view/13651442
