### ISSUE TITLE
Page title for hold/recall is wack

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-requests#226]
Checked out item
https://requests-dev.stanford.edu/hold_recalls/new?barcode=36105212946136&item_id=10766632&origin=GREEN&origin_location=STACKS

![screen shot 2015-07-15 at 2 43 37 pm](https://cloud.githubusercontent.com/assets/6945691/8710635/0faaa6d8-2b00-11e5-9dc6-1d88a1513c66.png)

On order item
https://requests-dev.stanford.edu/hold_recalls/new?barcode=36105212095934&item_id=10783664&origin=GREEN&origin_location=STACKS

![screen shot 2015-07-15 at 2 45 44 pm](https://cloud.githubusercontent.com/assets/6945691/8710649/31879d24-2b00-11e5-9e1f-e14ac119c8eb.png)

**Comment by jkeck** [comment]
Closed by #239
