### ISSUE TITLE
Scans can't be shared with proxy/sponsor

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/sul-requests#2264]
When we release 2024 Requests work, we'll have the Proxy/Sponsor question as the first step (if the user is a part of a research group). 

That is problematic if they select the "Scan" request type in Step 2. We can't share scans with proxy members because ILLiad doesn't know about the research group.  We may need to change the order of the proxy/sponsor question OR show an alert/text letting the user know we can't share the scans. 

Noting that this question was first raised when testing Mediated paging, and Chris, Sarah & Darcy determined that we would allow the proxy/sponsor selection for mediated pages.

**Comment by hudajkhan** [comment]
Consensus: Use an alert for now. 
Text: "Scans won't be shared with your proxy group." Put it on the scan/pickup step.
