### ISSUE TITLE
hanging hypen after "Earliest available" on page pickup request section of form

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/sul-requests#2267]

**Comment by dbranchini** [comment]
![Image](https://github.com/sul-dlss/sul-requests/assets/6816624/2dc15c4a-12d2-4814-8219-d5c69f7539f0)

**Comment by dbranchini** [comment]
Also, can we remove some space above the earliest available and add some space below it? And this screenshot came from a regular page, not a mediated page, so it should read, "Pickup after:" instead of "Earliest available:". For a mediated page, it will still read "Earliest available:".
