### ISSUE TITLE
Cancel request after... needs default date (holds/recalls)

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-requests#227]
In hold/recall requests, the "Cancel request after" date should default to today plus one year.

![screen shot 2015-07-15 at 3 07 56 pm](https://cloud.githubusercontent.com/assets/6945691/8711242/18a3152c-2b05-11e5-8eef-664ee8b6a107.png)

If a hold/recall request is triggered in the course of a page request, the "Cancel" date should default to today plus THREE years. In this case, the date is not visible to the end user, but has to be part of the request.

**Comment by jkeck** [comment]
Will do the three year default date as part of #201
