### ISSUE TITLE
Required fields

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-requests#228]
Some fields need to be required before the form is submitted. There are a couple of different patterns.

### Simple always-required field

Add `<span class="label label-warning" aria-hidden="true">Required</span>` to the field label, on a separate line below the label.
Add `required aria-required="true"` to the input.
(label is aria-hidden so the screen-reader hears "required" just once, not multiple times)

* [x] **Planned date of use**:  required wherever it occurs
![screen shot 2015-07-16 at 11 07 51 am](https://cloud.githubusercontent.com/assets/6945691/8733031/3a7817d6-2bb6-11e5-8824-8213ac682be2.png)

* [x] **Title** in Scan request
![screen shot 2015-07-16 at 11 06 57 am](https://cloud.githubusercontent.com/assets/6945691/8733038/4326f4f6-2bb6-11e5-818e-4295e11f9acf.png)

* [ ] **Library ID** in hold/recall request (if user has chosen the "I don't have a SUNet ID" path)
![screen shot 2015-07-16 at 11 32 52 am](https://cloud.githubusercontent.com/assets/6945691/8733051/54733d82-2bb6-11e5-8444-e08fc1024a7a.png)

### Required but not labelled

* [x] **Cancel request after** - needs `required aria-required="true"` but no visible label. Field has a default value and we want it to be unobtrusive. If the user deletes the default date without providing an alternate date, then the "required" setting will prevent submitting the form. (Alternatively... if they delete the default date we can just reinsert it on submit...?)

### Prevent requests with no items selected

* **Item selector** on multi-item pages. User needs to select (or add) at least one item. 
  * [x] add "required" label to the "item count" label
  * [x] add text that appears only when 0 items are selected (use style "help-block")
  * [x] disable the submit button and "I don't have a SUNet ID" link until an item is selected

![screen shot 2015-07-16 at 1 44 17 pm](https://cloud.githubusercontent.com/assets/6945691/8734801/4b1c3382-2bc1-11e5-981c-b6221e449f74.png)
![screen shot 2015-07-16 at 1 44 41 pm](https://cloud.githubusercontent.com/assets/6945691/8734807/506fc2ea-2bc1-11e5-9a9f-1af14c2a9849.png)

### Library ID OR Name + email
For page/mediated page requests where the user selects "I don't have a SUNet ID". No individual field is required, so no "required" attribute or label will help. :disappointed: 
* [ ] We can try disabling the Send button until we have the information we need, but I'm concerned that it won't be clear why the button is disabled. I'd like to add something like a tooltip, but it doesn't appear that a bootstrap tooltip will appear when the control is disabled. Suggestions?
![screen shot 2015-07-16 at 1 21 18 pm](https://cloud.githubusercontent.com/assets/6945691/8734840/8390e46a-2bc1-11e5-846f-f00e7dd63b1e.png)

**Comment by cbeer** [comment]
How important is both `required` and `aria-required`? It looks like we get `required` out-of-the-box, but would have to do more work to get `aria-required` too.

**Comment by cbeer** [comment]
The suggested way to display a `required` label for the bootstrap form seems to use CSS, e.g.:

```css
label.required {
  &:after {
    @extend .label;
    @extend .label-warning;
    content: " Required";
  }
}
```

I'm not sure what the screen-reader implications are, though. We certainly don't get a chance to hang custom `aria-*` attributes on it.

**Comment by jvine** [comment]
Okay, it looks like `aria-required` is only needed for user agents that don't support HTML5. Let's go with `required`.

**Comment by cbeer** [comment]
Whew, thanks.
