### ISSUE TITLE
Scan requests confirmation screen changes from original design

### ISSUE THREAD

**Issue by dbranchini** [sul-dlss/sul-requests#2361]
![Image](https://github.com/sul-dlss/sul-requests/assets/6816624/62dc9bba-3ea7-4a7d-90eb-c66bcaebc2b9)

### Scan confirmation screens:

- [x] **Change opening copy to:** Expect a confirmation email shortly at griffins@stanford.edu. You will receive an email when your PDF scan is ready to be downloaded from your interlibrary loan account. You can also check the status of your request anytime at My Account.

- [x] **Email and phone number:**

scan-and-deliver@stanford.edu
(650) 725-1278

--

### All confirmation screens:

- [ ] Also, please drop the link to RLCP from ALL confirmation screens. Let me know if I need to file a different ticket for this.

**Comment by dnoneill** [comment]
Believe RLCP removal was able done.

**Comment by dbranchini** [comment]
Sorry, Sarah and I chatted this morning and decided to change the message at the top to:

Expect a confirmation email shortly at **griffins@stanford.edu**. You can also check the status of your request anytime at [My Account](https://mylibrary.stanford.edu/). We'll notify you by email once your scan request is ready. Remember to download the PDF within 30 days of notification.
