### ISSUE TITLE
Reset user pin still results in error message

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/sul-requests#2371]
When trying to request a pin for a Library cardholder, I continue to see an error message.  Here are the urls from the test:

Login screen url: https://requests-dev.stanford.edu/patron_requests/new?instance_hrid=17205&origin_location_code=SAL3-STACKS

![Image](https://github.com/sul-dlss/sul-requests/assets/14897546/b2cae2a8-c49e-4334-8d50-9ccfa0a8d2b1)

NOTE: I'm simply clicking the "Forgot your PIN? Don't have one yet?" link. I have **not** been filling in the Library ID field and then clicking the "Forgot.." link.

Reset pin url: https://requests-dev.stanford.edu/reset_pin?referrer=https%3A%2F%2Frequests-dev.stanford.edu%2Fpatron_requests%2Fnew%3Finstance_hrid%3D17205%26origin_location_code%3DSAL3-STACKS
<img width="738" alt="image" src="https://github.com/sul-dlss/sul-requests/assets/14897546/0f746fca-384e-4e85-bb2a-4365dfcd4837">

Error message url: https://requests-dev.stanford.edu/reset_pin?referrer=https%3A%2F%2Frequests-dev.stanford.edu%2Fpatron_requests%2Fnew%3Finstance_hrid%3D17205%26origin_location_code%3DSAL3-STACKS
<img width="1153" alt="image" src="https://github.com/sul-dlss/sul-requests/assets/14897546/75a357b7-7aee-470c-bd99-100a347cae6d">

**Comment by dnoneill** [comment]
Closed with https://github.com/sul-dlss/shared_configs/pull/2160
