### ISSUE TITLE
Pickup request confirmation screen

### ISSUE THREAD

**Issue by dbranchini** [sul-dlss/sul-requests#2378]
Slight change in the copy at the top to:

Expect a confirmation email shortly at **uurgula@stanford.edu**. You can also check the status of your request anytime at [My Account](https://mylibrary.stanford.edu). You will receive an email when the item(s) are ready for pickup.

![Image](https://github.com/sul-dlss/sul-requests/assets/6816624/4982483e-322a-4d0e-a977-1697bd81270f)

https://www.figma.com/file/sqzYVhfRgn3nMArUAdrs0n/SearchWorks?type=design&node-id=259-5468&mode=design&t=D2M8w7LrvDdmuZNu-4

**Comment by dnoneill** [comment]
Think this is done?

**Comment by dbranchini** [comment]
Yes, except one thing - Instead of Pickup location on the pickup confirmation screens, can we change that label to "Preferred pickup location?" There are times when they can't route it to the preferred pickup location so that's why we used that language.
