### ISSUE TITLE
"Pickup after" values

### ISSUE THREAD

**Issue by dbranchini** [sul-dlss/sul-requests#2423]
After going live, we talked about updating the service that renders the pickup after values so that the date/time format is as follows: 

Pickup after: Wednesday, May 8, 2024, 4 pm

**Comment by dbranchini** [comment]
Is this date/time format used anywhere else? I have a vague memory that it is and it might cause an issue to update it. (Not thinking of the old requests app... just another field?)

**Comment by cbeer** [comment]
I think we can do whatever we want with the times -- they're just plain text we append to the date.
