### ISSUE TITLE
[sul-requests/prod] KeyError: key not found: "username"

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/sul-requests#2436]
## Backtrace

    line 38 of [PROJECT_ROOT]/app/models/folio/patron.rb: fetch
    line 38 of [PROJECT_ROOT]/app/models/folio/patron.rb: username
    line 370 of [PROJECT_ROOT]/app/models/patron_request.rb: illiad_request_params

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/49963/faults/107743125)

**Comment by dnoneill** [comment]
clsoed with https://github.com/sul-dlss/sul-requests/pull/2437
