### ISSUE TITLE
Show Planned date of use for SAL3 PAGE-MP

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/sul-requests#2452]
Testing in requests-dev. I would have expected a planned date of use to appear on a SAL3 PAGE-MP request. Instead, I'm getting "Earliest available".

Example records: 
https://searchworks-stage.stanford.edu/view/9521863
https://searchworks-stage.stanford.edu/view/5814591

On folio-test, I'm a proxy, and got the proxy step. I answered "myself". 
<img width="1148" alt="image" src="https://github.com/sul-dlss/sul-requests/assets/14897546/ffbd2b55-4d0b-4c24-ac38-0b69ff13ca8f">

**Comment by cbeer** [comment]
PAGE-MP doesn't use needed dates: https://github.com/sul-dlss/sul-requests/issues/266 🤷‍♂️

**Comment by saseestone** [comment]
Ok that's odd and I definitely didn't remember/document. So then our alert text is off. (Since there is no planned visit date)

**Comment by saseestone** [comment]
Short term: We're going to remove the alert that indicated it's a staff mediated page and references "planned visit".

I'm talking with Branner map staff about if mediation is still desired, and if so if "planned date of use" is also desired
