### ISSUE TITLE
Mediation admin page doesn't include link for SAL3-PAGE-MP items when requests present

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/sul-requests#2453]
Testing with requests-dev. I was able to find submitted requests at the following urls: 

- https://requests-dev.stanford.edu/admin/SAL3
- https://requests-dev.stanford.edu/admin/SAL3-PAGE-MP

but would have expected a link to appear on the admin landing page as well (like Art & Education do)

<img width="773" alt="image" src="https://github.com/sul-dlss/sul-requests/assets/14897546/84d5abe1-e863-40e1-aed5-730f6fd677a9">

**Comment by cbeer** [comment]
Fixed by https://github.com/sul-dlss/sul-requests/pull/2451
