### ISSUE TITLE
How far into the future should we request library hours data?

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/sul-requests#248]
Currently we only request 2 months from the hours service.  However; this means that for "Planned date of use" dates we will only allow them to select a date that the pickup library is open within that 2 months.

Off the top of my head I can think of a few ways to handle this.

1. Extend the range of dates that we request to the maximum that we plan to allow in the date range.
  * If this span is very large we may need AS to gather hours data farther in advance.
2. Allow any date after the N months that we request from the hours service.
3. Allow any week-day after the N months that we request from the hours service.

**Comment by cbeer** [comment]
Can we asynchronously check the picked date?

**Comment by cbeer** [comment]
And, yes, we'll want AS to gather hours (or, at least, normal business hours). Right now, we probably still don't have library hours beyond mid-September.

**Comment by jkeck** [comment]
We could check the date async.  It's not how it is happening now but that was because we already had the list of business days from the response so we are just piggy-backing on that.
