### ISSUE TITLE
Add a path for the user's NVTGC before illiad/ in the URL. We will need to lookup their affiliation in LDAP

### ISSUE THREAD

**Issue by jgreben** [sul-dlss/sul-requests#250]
Add a path for the user's NVTGC before illiad/ in the URL. We will need to lookup their affiliation in LDAP

organization:sulair = "ST2";
organization:law = "RCJ";
organization:gsb = "S7Z";
else default is ST2

Currently the settings has the URL as: sul_illiad: 'https://sulils-test.stanford.edu/illiad.dll?'

Change to: sul_illiad: 'https://sulils-test.stanford.edu/' and add the illiad.dll? part in the ILLiad URL class.

**Comment by cbeer** [comment]
When you say "affiliation", do you know what LDAP attribute that corresponds to? The best I can come up with, right now, is `suPrimaryOrganizationID`, but that's a little indirect...

**Comment by jgreben** [comment]
I think it should be 'suAffiliation'  or it may be suGwAffilCode[1-5]. See https://itservices.stanford.edu/service/directory/datadefs/people

I would like to look at some examples to be sure.
