### ISSUE TITLE
Remove temporary code from Poppy update after launch

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/sul-requests#2502]
This appears in 2 files:

- `app/jobs/submit_folio_patron_request_job.rb`

   - [ ] [remove poppy_request key/value](https://github.com/sul-dlss/sul-requests/blob/6232178627cbd5cda6d81948bff0f95c91d9f817/app/jobs/submit_folio_patron_request_job.rb#L56)

- `app/services/folio_client.rb`
   - [ ] [remove okapi_version method](https://github.com/sul-dlss/sul-requests/blob/6232178627cbd5cda6d81948bff0f95c91d9f817/app/services/folio_client.rb#L167)
   - [ ] [remove poppy? method](https://github.com/sul-dlss/sul-requests/blob/6232178627cbd5cda6d81948bff0f95c91d9f817/app/services/folio_client.rb#L178)
   - [ ] [remove comment and poppy_request key ](https://github.com/sul-dlss/sul-requests/blob/6232178627cbd5cda6d81948bff0f95c91d9f817/app/services/folio_client.rb#L182)
   - [ ] [remove conditional](https://github.com/sul-dlss/sul-requests/blob/6232178627cbd5cda6d81948bff0f95c91d9f817/app/services/folio_client.rb#L189)
   - [ ] [remove option added via .merge](https://github.com/sul-dlss/sul-requests/blob/6232178627cbd5cda6d81948bff0f95c91d9f817/app/services/folio_client.rb#L204)

**Comment by dnoneill** [comment]
closed with https://github.com/sul-dlss/sul-requests/commit/5dc16e7447a1bf4d0a71ed0aa187e4e79aa7aee6
