### ISSUE TITLE
Allow for location specific mediation

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/sul-requests#253]
Right now, since its origin library is SAL3 it shows up under SAL3 mediation, but I'm going to guess that's not right.  Are there any other exceptions where we want the mediating library to be something other than the origin?

**Comment by jvine** [comment]
PAGE-MP is mediated by the destination library - i.e. Julie. I think this currently the only exception - the others are all done by the origin library. Going forward, my guess is that anything mediatable that originates at SAL3 will be mediated by the destination.
