### ISSUE TITLE
Title for mediated pages is not always correct

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-requests#262]
It looks like all mediated pages are getting "Request on-site access". This is appropriate for SPEC-COLL, HOOVER and HV-ARCHIVE, but not for HOPKINS and PAGE-MP, where the items are circulating items, and the title should be "Request delivery to campus library".

example - 2833307
![screen shot 2015-07-31 at 4 19 48 pm](https://cloud.githubusercontent.com/assets/6945691/9019414/04df43c4-37a0-11e5-8bc3-993c09b8a507.png)

**Comment by jkeck** [comment]
We should use the helper that will ship in #294 for this.
