### ISSUE TITLE
SAL-Newark items not all getting comments box

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-requests#263]
It looks like SAL-Newark items are getting a comments box only if they don't have a legit barcode.

Single item, real barcode, but no comment box:  2833045, 356446
Multiple barcoded items, no comment box: 5086259
No real barcode, gets comment + holdings:  4279331, 4472091

All SAL-Newark items should have a comments box plus holdings (if they exist), in addition to the item selector (if there are multiple barcoded items).

**Comment by jkeck** [comment]
The way it's currently coded is Page requests only get the comment box if it is SAL-NEWARK AND has NO holdings with real 36105 barcodes.

**Comment by jkeck** [comment]
My previous comment is no longer valid.  Do what's in the ticket.
