### ISSUE TITLE
Is item type a factor for Scan eligibility?

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-requests#265]
If origin=SAL3&origin_location=STACKS then Scan is available - are we looking at the item type at all?

Triggers table shows that only items with type STKS-MONO, STKS-PERI, STKS should be scannable, but it doesn't look like we're looking at this. However, it also looks like any item with origin=SAL3&origin_location=STACKS and an item type that is NOT one of these, is likely a data error. 

![screen shot 2015-07-31 at 4 57 50 pm](https://cloud.githubusercontent.com/assets/6945691/9019727/52a09522-37a5-11e5-9373-26039b3cf2d3.png)

Example item - 492383 - has both NEWSPAPER and STKS-PERI items. Technically, NEWSPAPER is not a scannable type, but they seem to be included the item selector. 

Really just wondering if item type has been coded or not - not asking for action.

**Comment by jkeck** [comment]
We allowing a scan because there is a single item in that location that is scannable.

What should the behavior be?  Should we omit any holdings that are not of the correct type from the item selector (only for scans)?

**Comment by jvine** [comment]
I think we should stay with what we are doing. The item types are inconsistently applied, and we will end up excluding stuff that is scannable, with no way to tell the user why. If we get feedback that people are requesting items that are actually unscannable, we can revisit and see if item types will help.


________________________________

**Comment by jvine** [comment]
Okay, we need to discuss this with Darsi again. Here's a sound recording that has the scan option:

https://sw-webapp-sandbox-b.stanford.edu/view/10260761

It is SAL3 : STACKS : STKS-MONO

a) I think this is incorrect, but
b) I think the part that will change is the STKS-MONO, which we are not currently looking at.

**Comment by jvine** [comment]
Closing this - the incongruous item is a data issue.
