### ISSUE TITLE
PAGE-MP and HOPKINS mediated pages should not have "planned date of use"

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-requests#266]
Kind of related to #262. 

PAGE-MP and HOPKINS are not "plan in advance to visit the library" - they are just page requests with an in-between step. They should not have a "Planned date of use" field. When they are also a hold/recall, they should have a "Cancel request after" field.

![screen shot 2015-07-31 at 5 18 49 pm](https://cloud.githubusercontent.com/assets/6945691/9019873/9e4a25bc-37a8-11e5-84f2-e20037f5c1be.png)
![screen shot 2015-07-31 at 5 22 45 pm](https://cloud.githubusercontent.com/assets/6945691/9019880/cc8b70f2-37a8-11e5-9a9f-e99c4f0864e5.png)

**Comment by jkeck** [comment]
Change goes here: https://github.com/sul-dlss/sul-requests/blob/master/app/models/requests/mediated_page.rb#L44-L46
