### ISSUE TITLE
requests.stanford.edu landing page?

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/sul-requests#28]
What should a user see when they go to requests.stanford.edu?  I don't imagine most personas ever ending up there, however it will be useful to staff to not have to remember/bookmark the URL to the admin page (as I believe is the case w/ the current app) and can navigate from the requests app landing page.

**Comment by jvine** [comment]
Webauthed page w workgroups.

Someone like Sarah Seestone would get everything:
![requests home - all options](https://cloud.githubusercontent.com/assets/6945691/6987834/914463b0-da00-11e4-881b-7bf14a520ae7.png)

Tim Noakes or any mediator would get the option for their own library/ies:
![requests home - limited options](https://cloud.githubusercontent.com/assets/6945691/6987843/9edc6cde-da00-11e4-9f30-430a2312efb5.png)

Random SUNet ID login:
![requests home - no options](https://cloud.githubusercontent.com/assets/6945691/6987850/ae0e364c-da00-11e4-9019-b8fcfbc4301b.png)

**Comment by jkeck** [comment]
:+1: Thanks!
