### ISSUE TITLE
Final Required Fields

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/sul-requests#282]
* [ ] **Library ID** in hold/recall request (if user has chosen the "I don't have a SUNet ID" path)
![screen shot 2015-07-16 at 11 32 52 am](https://cloud.githubusercontent.com/assets/6945691/8733051/54733d82-2bb6-11e5-8444-e08fc1024a7a.png)

For page/mediated page requests where the user selects "I don't have a SUNet ID". No individual field is required, so no "required" attribute or label will help. :disappointed: 
* [ ] We can try disabling the Send button until we have the information we need, but I'm concerned that it won't be clear why the button is disabled. I'd like to add something like a tooltip, but it doesn't appear that a bootstrap tooltip will appear when the control is disabled. Suggestions?
![screen shot 2015-07-16 at 1 21 18 pm](https://cloud.githubusercontent.com/assets/6945691/8734840/8390e46a-2bc1-11e5-846f-f00e7dd63b1e.png)

**Comment by jgreben** [comment]
@jvine Is the black speech bubble a component of some existing framework or is it an image? Do you already have the html for it?

**Comment by jvine** [comment]
http://getbootstrap.com/javascript/#tooltips

**Comment by jgreben** [comment]
Closed by #470
