### ISSUE TITLE
Full page chrome inside iframe after login 

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-requests#286]
Don't be logged in.
Pick a scannable SAL3 item
(https://sw-webapp-sandbox-b.stanford.edu/view/10260761)
Select Scan
Don't fill in the title
Click Send request
Login

You get this:

![screen shot 2015-08-13 at 3 50 19 pm](https://cloud.githubusercontent.com/assets/6945691/9263657/b5bd0c2a-41d3-11e5-81c0-6893cb874853.png)

If you are already logged in, it works correctly.

**Comment by jkeck** [comment]
:+1: thanks, that is very helpful.

**Comment by jvine** [comment]
This is happening more broadly. If I click "not you", then click Send request, 2 things:

a) it doesn't ask me to reauthenticate (which it should, since I just said I wasn't the logged in user)
b) it gives the full chrome with the success page

![screen shot 2015-08-13 at 4 16 34 pm](https://cloud.githubusercontent.com/assets/6945691/9263965/b078d9e4-41d6-11e5-9265-b273b64e288b.png)

**Comment by jkeck** [comment]
This is also happening after we get redirected back from Illiad.  We need to pass the modal param through the redirect param as well.
