### ISSUE TITLE
Add shim for HTML5 date field

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/sul-requests#293]
Webshims seems to be do-able: http://afarkas.github.io/webshim/demos/index.html http://jsfiddle.net/trixta/BMEc9/

Are there other shims worth evaluating for accessibility?
https://github.com/chemerisuk/better-dateinput-polyfill
http://www.useragentman.com/blog/2010/07/27/creating-cross-browser-html5-forms-now-using-modernizr-webforms2-and-html5widgets-2/

**Comment by jgreben** [comment]
Using: https://github.com/whatcould/webshims-rails
Run: 
bundle install
rake webshims:update_public_versioned
