### ISSUE TITLE
x + cancel + close + caching

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-requests#295]
User confusion about redundant close actions and "aggressive" caching.

* [x] remove the x from the upper right corner 
* [x] make the Cancel button clear the cache
* [x] do NOT clear the cache if the user clicks outside the popup (i.e. does not explicitly cancel)
* [x] on the success page, change Cancel to Close

**Comment by jkeck** [comment]
We should look into [postMessage](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) for communicating between SearchWorks and the iframe to know when we are at the success page. There are security considerations to take before implementing.
