### ISSUE TITLE
SAL-Newark volumes/issues - layout

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-requests#298]
Please format the textarea like a regular form-group, and change the label to just "Volumes/issues". The layout looks too disjointed at full width.

Also, when the textarea is the only item input on the form, it needs to be required. 

![screen shot 2015-08-14 at 2 37 39 pm](https://cloud.githubusercontent.com/assets/6945691/9284659/7b46d66a-4292-11e5-8cdf-456ba90e11ae.png)

Related to #263 - not sure how to combine this with the item selector.

**Comment by jgreben** [comment]
@jvine Just a little clarification on the requirement:
`when the textarea is the only item input on the form, it needs to be required.`

Is this the case where the page request only has a single holding?

So,
https://requests-dev.stanford.edu/pages/new?item_id=4472091&origin=SAL-NEWARK&origin_location=PAGE-GR
vs.
https://requests-dev.stanford.edu/pages/new?item_id=4279331&origin=SAL3&origin_location=PAGE-GR

**Comment by jgreben** [comment]
Jennifer says: "currently we are getting ONLY the text box OR the selector, but we should always get the text box, PLUS the selector when there are legit barcoded items

**Comment by jgreben** [comment]
Moved Required field requirement to #312 for clarification and specification.
