### ISSUE TITLE
Create sul name-spaced workgroups requests

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/sul-requests#31]
I don't have the ability to make top-level sul:* workgroups.  We need workgroups for each library that mediates requests as well as a top-level admin workgroup (we can re-purpose the existing one later if we want, but for development we may want to limit admin down to just us).

- [x] Special Collections (spec)
- [x] Earth Sciences (branner)
- [x] Marine Biology (hopkins)
- [x] Hoover Archives (hoover-archive)
- [x] Hoover Library (hoover-library)
- [x] Super Admin Group

**Comment by snydman** [comment]
![image](https://cloud.githubusercontent.com/assets/3279382/9319276/75903d1c-4501-11e5-8829-ca982d94e69d.png)

**Comment by cbeer** [comment]
:+1:
