### ISSUE TITLE
SAL-Newark volumes/issues field required under some conditions

### ISSUE THREAD

**Issue by jgreben** [sul-dlss/sul-requests#312]
"some conditions" TBD

![7b46d66a-4292-11e5-8cdf-456ba90e11ae](https://cloud.githubusercontent.com/assets/3093850/9398027/8944852c-4757-11e5-941e-59c914a46d75.png)

**Comment by jvine** [comment]
This is waiting on information from Sarah Seestone. We want the simplest possible solution for what may be a very edgy case.
