### ISSUE TITLE
mailto: links not working with Outlook 365

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-requests#326]
(Seriously, Microsoft?)

When I click a mailto link in the mediation table, it launches Outlook, but it doesn't open a new email addressed to the mailto address. This could be "just me", because it also forces Outlook to open in Chrome, no matter what browser I start in. 

If this isn't an easy fix, we should just unlink the addresses for now. Grr.

**Comment by cbeer** [comment]
I assume this is a problem on other sites too?

**Comment by jvine** [comment]
Yes. Microsoft broke the internet.

**Comment by jvine** [comment]
And it works now.
