### ISSUE TITLE
Not trapping dates in the past?

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-requests#330]
User entered 02/09/15 in the needed on date (in Firefox where there's no date control) intending September 2. Two things happened:

1. the app interpreted 15 as 1915 and trapped it as a closed day, which ... at least it trapped it?
2. once the user changed the year to 2015, the app interpreted 02/09 as Feb 9, and allowed the request to be created.

Needed on dates should not ever be before today's date.

**Comment by cbeer** [comment]
Will the date format confusion be fixed (enough) with the HTML5 shim?

**Comment by jvine** [comment]
If the HTML5 shim will work for all browsers, it does seem to prevent past dates, so I guess so.
