### ISSUE TITLE
Buckminster Fuller collection fails

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-requests#331]
https://sw-webapp-sandbox-b.stanford.edu/view/4332640

The form loads fine, but submit fails.

On Chrome: the browser hangs up.
On Firefox: got a Mouseflow error; stopped the script; then got a big red error message. 

![screen shot 2015-08-27 at 1 33 32 pm](https://cloud.githubusercontent.com/assets/6945691/9532461/a89a7a1c-4cc0-11e5-9d10-61b8cff8ee74.png)

![screen shot 2015-08-27 at 1 33 56 pm](https://cloud.githubusercontent.com/assets/6945691/9532465/ae5f625a-4cc0-11e5-96e2-0d4a07bc413a.png)

**Comment by cbeer** [comment]
It looks like we're storing too many items in the `request_status_data`, but I'm not sure where we're failing to filter the list correctly..
