### ISSUE TITLE
"Not you" logout doesn't let user login as someone else

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-requests#333]
Logged in as myself.
Another user fills in the form, clicks "Not you?" and gets "You have successfully logged out".
User clicks "Send request (login w SUNet ID)" and... is silently logged in as me and gets a success page.

The Send request should trigger the webauth form.

**Comment by cbeer** [comment]
I don't think we can do that without completely logging a user out of all their webauth sessions when they click "Not you?", which is probably a terrible experience (we'll log them out of e.g. webmail and any other webauthed sessions they're currently using, when they're probably just trying to use a proxy id).

What's the use case for this? People sharing computers?

**Comment by jvine** [comment]
The use case is public/kiosk computers. We want to encourage users to login. 

Go to Axess:  https://axess.sahr.stanford.edu - and click Sign out, then click Login. It will take you through full authentication again - it doesn't just silent auth you back into Axess, and it doesn't end any other sessions I have open. 

If we're not able to do this, I need to look at wording of the UI, because users are disconcerted by the current behaviour.

**Comment by cbeer** [comment]
I think axess uses a mode that always requires authentication, even if you're authenticated elsewhere. I'm pretty sure that's not what we want here either. When using public terminals, shouldn't people close the browser or log off after using them?

**Comment by jvine** [comment]
People should close browsers on public machines, yes. Regardless, the UI was intentionally designed to allow users to switch logins, and if that's not possible, then we can't present it the way it currently is, because people do not understand what it is/is not doing.

**Comment by cbeer** [comment]
I took another look at the Axess example. When I logged out, it did kill my entire webauth session (although applications that track session state locally may keep you logged in for longer). I'm not sure we could even be granular about logging out of just the application.

**Comment by cbeer** [comment]
Wait, I think I've confused what button we're talking about. If you click "Not You", we actually do want to kill all your webauth cookies, don't we?

**Comment by jvine** [comment]
I think you are right that if we kill all your webauth cookies, it will kill any other webauthed sessions you have open. So for the kiosk situation, that's good, but not for all scenarios. Don't change anything for now.

**Comment by jvine** [comment]
![requests - use a diff id](https://cloud.githubusercontent.com/assets/6945691/9593132/a085a922-4fff-11e5-99a9-c5473fd6051a.png)
![requests - layout adjustment](https://cloud.githubusercontent.com/assets/6945691/9593133/aeac8624-4fff-11e5-8edf-bca43a8be7af.png)

**Comment by cbeer** [comment]
How does this work with e.g. scans, where you must have a sunetid?

**Comment by jvine** [comment]
Sorry, missed copying these details:

if it's a delivery or hold/recall request:
- remove the "not you" link and the subsequent "you have successfully logged out" message
- add a "Use a different library ID" button (wording? because sometimes they could use name+email?)
- button behaves like the "I don't have a SUNet ID" button - opens up the alternate part of the form (see second screenshot)

if it's a scan request
- don't show the "not you" link at all - if they are logged in, they are logged in. (and can use the standard webauth logout/close browser procedure to re-auth).
