### ISSUE TITLE
HTML5 date field usability issues

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-requests#336]
The HTML5 date field is technically accessible, but not very usable. Many don't know that there is a calendar popup available, and the field template can be unforgiving. Wish I had video to show this.

Date selection was one of the primary usability issues we wanted to address with the new form. We've done a lot toward this by preventing selection of invalid dates, but people expect a calendar, and they are not seeing it. 

It looks like the webshim has the option to "openOnFocus", which would help a lot. Can we override Chrome's native behaviour with the webshim?

**Comment by jgreben** [comment]
@jvine I added the openOnFocus: true option for the date field in the #293 branch. I also made the replaceUI: true so this will happen for all browsers.

Right now I need to work with Chris or Jessie to get the tests to work that require the date field to be filled in. The webshim breaks the normal tests that fill in the date field and I have not been able to work out how to get them to work again.

**Comment by jgreben** [comment]
@jvine I tested as best I could the accessibility of this form using the keyboard. It works, but it was not necessarily intuitive. You have top use the Alt+down-arrow key to move from the field to the calendar popup. Let me know if this will be ok. Also there is a configuration option for what default level you want to appear in the cal popup (year, month, or day):

![screen shot 2015-09-03 at 11 01 02 am](https://cloud.githubusercontent.com/assets/3093850/9666499/444c05b0-522b-11e5-84b5-de77e83b1e4b.png)

![screen shot 2015-09-03 at 11 00 50 am](https://cloud.githubusercontent.com/assets/3093850/9666501/4e713d1c-522b-11e5-9259-e632bf598874.png)

![screen shot 2015-09-03 at 11 01 47 am](https://cloud.githubusercontent.com/assets/3093850/9666504/52153446-522b-11e5-83ef-4e13943f154c.png)

**Comment by jvine** [comment]
Just to record an IM discussion:  alt-down arrow is legit, and we want to start at the day level.
