### ISSUE TITLE
Auto-scroll down to show remainder of form when user clicks "no SUNet ID"

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-requests#338]
When user clicks on "I don't have a SUNet ID", it's right at the bottom of the page. Then we show the Library ID field with the focus in it, but the user can't always see that there are more options further down. 

Can we use an #id and window.location or window.scroll to show the remainder of the form? If the remainder is longer than the viewport (i.e. tiny viewport) then the Library ID should be at the top.

**Comment by cbeer** [comment]
I think I probably fixed this in #369, but we should verify when it's deployed.
