### ISSUE TITLE
Are library ID users supposed to get a confirmation email?

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-requests#342]
When you place a request using a library ID, there's no confirmation email message on the success page, and in fact, no confirmation email. Can we get this from Symphony?

**Comment by cbeer** [comment]
We're not currently querying Symphony for any patron information except for proxy access. @jgreben, do you know if this information is exposed anywhere currently?

**Comment by jgreben** [comment]
There is a script similar to proxy.pl that I use currently in MyAccount (e.g.): http://morison.stanford.edu/cgi-bin/userName.pl?uid=2554452340

This can be easily modified or duplicated with changes to a new script.
