### ISSUE TITLE
Change or define Settings.sul_illiad URL for GSB and Law

### ISSUE THREAD

**Issue by jgreben** [sul-dlss/sul-requests#347]
GSB and Law each have different base URLs.

if GSB then
  http://jblill.stanford.edu/
elsif Law then
  http://stanfordlaw.stanford.edu/
else
  http://sulils.stanford.edu

**Comment by cbeer** [comment]
So we don't need to do the ST2/RCJ/etc thing?

**Comment by jgreben** [comment]
Well, I first need to verify using a Law and a GSP account whether they can use the sulils url plus their nvtgc. For a moment I thought it could be a problem. If it doesn’t work we may need to use the full proxied url for each (with the nvtgc implied).

I will test and close the issue if it works.

On Aug 28, 2015, at 4:40 PM, Chris Beer <notifications@github.com<mailto:notifications@github.com>> wrote:


So we don't need to do the ST2/RCJ/etc thing?

**Comment by jgreben** [comment]
@cbeer can you check the LDAP attributes for mlemley@stanford.edu? He is a Law professor and (I think) should be eligible for S&D, however I get the ineligible message when I try to submit a scan request using his sunset id.

**Comment by cbeer** [comment]
What do you mean by "when I try to submit a scan request using his sunset id"?

**Comment by jgreben** [comment]
I mean when I spin up a rails server using his sunet id using  REMOTE_USER=mlemley rails


On Sep 3, 2015, at 9:03 AM, Chris Beer <notifications@github.com<mailto:notifications@github.com>> wrote:


What do you mean by "when I try to submit a scan request using his sunset id"?

**Comment by cbeer** [comment]
The LDAP attribute lookup doesn't happen locally. It requires Apache, `mod_webauthldap`, and a blessed keytab to work, so we only do it on our servers.

Locally, you can use `Settings.fake_ldap_attributes` [1] to provide fake data for the application.

[1] https://github.com/sul-dlss/sul-requests/blob/ddbabd607c87d31b6a7de75fbf4728953c232516/README.md#faking-workgroups-in-development

**Comment by jgreben** [comment]
So I tried putting this in my settings.yml or my development.yml

fake_ldap_attributes:
  mlemley:
    WEBAUTH_LDAPPRIVGROUP: 'stanford:faculty|stanford:affiliate:fellow'

But either way it does not work. Am I doing this correctly?

On Sep 3, 2015, at 9:36 AM, Chris Beer <notifications@github.com<mailto:notifications@github.com>> wrote:


The LDAP attribute lookup doesn't happen locally. It requires Apache, mod_webauthldap, and a blessed keytab to work, so we only do it on our servers.

Locally, you can use Settings.fake_ldap_attributes [1] to provide fake data for the application.

[1] https://github.com/sul-dlss/sul-requests/blob/ddbabd607c87d31b6a7de75fbf4728953c232516/README.md#faking-workgroups-in-development

**Comment by jgreben** [comment]
Ok, I see it is supposed to be in development.local.yml

**Comment by jgreben** [comment]
So after further investigation and testing it appears the we will not be able to use the current scheme we have for sul-illiad-test. We can either do what I described above, vis. the base urls, or we can use a new virtual proxy host. I went ahead and requested "scandeliver.stanford.edu" for this purpose.

**Comment by jgreben** [comment]
I requested the new vhost "scandeliver.stanford.edu" which we can use for production and that will fit in with the current scheme.
