### ISSUE TITLE
Minor color/text tweaks to scan/deliver choice page

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-requests#350]
- [x] make the deliver button btn-primary
- [x] make the scan button btn-default
- [ ] add the truck icon to the deliver button *if possible* (don't know if the icon font is available)
- [x] add text to the Scan deflist
```
<dt>Copyright limit</dt>
<dd>One article or chapter; maximum 50 pages.</dd>
<dt>Pilot service</dt>
<dd>Available to faculty, grad students, postdocs, academic staff, fellows, and visiting scholars.</dd>
```
![scan-deliver-choice](https://cloud.githubusercontent.com/assets/6945691/9588876/9b07e16a-4fdf-11e5-8071-a740b13969ee.png)

**Comment by cbeer** [comment]
Created #367 to handle the icon font later.
