### ISSUE TITLE
Add Searchworks icon font to the requests app

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/sul-requests#367]
(via sul_styles?) in order to support:

- [x]  add the truck icon to the deliver button if possible (don't know if the icon font is available)

![scan-deliver-choice](https://cloud.githubusercontent.com/assets/6945691/9588876/9b07e16a-4fdf-11e5-8071-a740b13969ee.png)

**Comment by mejackreed** [comment]
https://github.com/sul-dlss/sul_styles/issues/22
