### ISSUE TITLE
Add Undergraduate students to be eligible for the scan service

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/sul-requests#382]
We appeared to get pretty strong confirmation this morning that Undergrads will be **IN** for the launch of the scan service.  We need to add their affiliation (?) to our whitelist of scan eligible groups.

**Comment by jvine** [comment]
Sarah confirms that the complete stanford:student group is eligible, based on this description:

> includes regular students, students on leave, and MLA students; does not include NDO (non-degree option) students, incoming students, contingent students, students not registered, recent students, or nonactive students
