### ISSUE TITLE
Email to mediator when a request is made

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-requests#411]
For libraries that do not get requests daily, it would be helpful to get an email alert when a request is made and they need to do something in the mediation interface. 

HV-ARCHIVE
PAGE-MP
HOPKINS
HOOVER

Send email to mailing list (need to identify) with link to mediation UI.

**Comment by cbeer** [comment]
Can you provide some copy for that email?

**Comment by jvine** [comment]
>Subject: New request needs mediation
>
>Message: 
>On 2015-09-16 10.17a, John Doe (jdoe@gmail.com) requested the following:
>
>ʻIton ha-bonim
>
>Item(s) requested:
> TH113 .I75 I88 NO.1-7 1946
>
>Planned date of use: Wed Sep 30.
>
>Login to view and approve the request at http://requests.stanford.edu.


Same content as the email to the requester, but:
- show full date/time stamp for created_at (same as in mediation table)
- show requester 
- show planned date of use (this should be in the email to the user as well, btw)
