### ISSUE TITLE
Request failures - feedback to user

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-requests#423]
# Codes returned by Darsi

Codes and translations are listed here - also relevant to #251. Of the failure codes, only the three in bold have specific handling for patrons; the rest all fall into "something went wrong".

Success codes
209      Hold placed
S001    Scan submitted
P001    Paged
P001B  Not on shelf - hold placed for HOLD@xx
P002    Hold placed for HOLD@xx
P005  Not on shelf - hold placed  [new code added 9/30 5:22pm]

Not success codes
7          Item not found in catalog
**722     User already has a hold on this material**
I001    Record doesn't exist
U001   Required field missing: Library ID
U002   Library ID doesn't exist
**U003   User is BLOCKED**
**U004 User's privileges have expired** [new code added 9/30 5:22pm]
P004    Not a paging library
P003   Item not valid for page

# Request failure code 722

![screen shot 2015-09-29 at 5 16 21 pm](https://cloud.githubusercontent.com/assets/6945691/10181564/93dfbff6-66ce-11e5-8c27-503b75bb9c54.png)

# Request failure code U003 or U004

"We can't complete your request because your status is **blocked**"
"We can't complete your request because your privileges have expired"

![screen shot 2015-09-29 at 5 17 25 pm](https://cloud.githubusercontent.com/assets/6945691/10181570/a2f91dde-66ce-11e5-87c4-f4673b51df7f.png)

BUT SEE ALSO "Item is scannable" section below

# All other request failure codes

![screen shot 2015-09-29 at 5 19 35 pm](https://cloud.githubusercontent.com/assets/6945691/10181576/b82e9652-66ce-11e5-9045-692345f59170.png)

Use the default contact info.

# Item is scannable and user is blocked

See (2) in the screenshot below - if an item is scannable, AND the user has requested to page it, AND the user is blocked or expired, AND the user is otherwise eligible to scan... then they should be offered the option to scan. 

![screen shot 2015-09-29 at 3 14 34 pm](https://cloud.githubusercontent.com/assets/6945691/10179763/09e0d21a-66bd-11e5-8172-b8ae0b12fa95.png)
![screen shot 2015-09-29 at 3 14 43 pm](https://cloud.githubusercontent.com/assets/6945691/10179769/0f85d954-66bd-11e5-98d3-163fdc181f1d.png)

**Comment by dlrueda** [comment]
I have updated my Symphony code to use only these response codes, and have changed the text to what Jennifer indicates here.
