### ISSUE TITLE
User can click request submit button multiple times and submit the same request

### ISSUE THREAD

**Issue by jgreben** [sul-dlss/sul-requests#426]
Here is the behavoir:
![req_submit](https://cloud.githubusercontent.com/assets/3093850/10198435/d4ebff14-6750-11e5-92f9-3e9ef39187a5.gif)

Here is the result:
![screen shot 2015-09-30 at 8 39 56 am](https://cloud.githubusercontent.com/assets/3093850/10198453/e4dc6706-6750-11e5-948e-e3587e42f124.png)

**Comment by cbeer** [comment]
Fixed by #442
