### ISSUE TITLE
Update list of people eligible for scan service

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-requests#433]
This is no longer correct:
![screen shot 2015-10-02 at 10 31 43 am](https://cloud.githubusercontent.com/assets/6945691/10253190/da5bc7d0-68f0-11e5-8dfc-537c2cf98f31.png)

Also appears in an exception message.

Replacement text:
> Available to faculty and staff, students, fellows, postdocs, and visiting scholars.

**Comment by cbeer** [comment]
What about the text for ineligible users?

> This pilot service is currently available only to faculty, grad students, postdocs, academic staff, fellows, and visiting scholars. Your feedback will help us refine and expand the service!

**Comment by jvine** [comment]
That's what I meant by "Also appears in an exception message." :-)  More explicitly:

> This pilot service is currently available only to faculty and staff, students, fellows, postdocs, and visiting scholars. Your feedback will help us refine and expand the service!

**Comment by cbeer** [comment]
Thanks
