### ISSUE TITLE
Change email address for scan requests 

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-requests#452]
to scan-and-deliver@stanford.edu.

* [ ] the "From" address for the confirmation email
* [ ] the contact info at the bottom of the email

(is there anywhere else?)

**Comment by cbeer** [comment]
@jgreben I assume this from ILLiad?

**Comment by jvine** [comment]
request_confirmation.text.erb ??

**Comment by cbeer** [comment]
Oh, sorry, I confused this with your comment in slack.
