### ISSUE TITLE
Required fields no  longer correct

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-requests#471]
related to #228 

Planned date of use:  no longer has the "required" label.
![screen shot 2015-10-21 at 11 25 02 am](https://cloud.githubusercontent.com/assets/6945691/10646320/5ce9ba04-77e7-11e5-979e-f80af7f3bdea.png)

Title of article - has the label, but not the "required" attribute - so the validation is ONLY server-side. 
![screen shot 2015-10-21 at 11 33 35 am](https://cloud.githubusercontent.com/assets/6945691/10646381/9a32dd6e-77e7-11e5-8d99-b5aed378ec1c.png)

I think that's all.

**Comment by jkeck** [comment]
Closed by #473
