### ISSUE TITLE
Send Item Barcode in ILLiad ILL Number Field

### ISSUE THREAD

**Issue by jgreben** [sul-dlss/sul-requests#477]
So Doc Del Staff can search for the request in the ILLiad client using the item barcode.

**Comment by jgreben** [comment]
![screen shot 2015-10-22 at 10 09 07 am](https://cloud.githubusercontent.com/assets/3093850/10672663/49ac06d0-78a6-11e5-9bcd-b0a94468fdb4.png)

**Comment by jkeck** [comment]
@jgreben it looks like we're trying to do that in the `IlliadOpenurl` class (https://github.com/sul-dlss/sul-requests/blob/master/app/models/illiad_openurl.rb#L18)

So do we need to repeat that information in another field, move that information to another field, or is the information not coming through at all?

**Comment by jgreben** [comment]
I DO think we should repeat the barcode in both the ItemNumber field <#rft.item> and the ILLNumber field <#rft.ill_number> to indicate that this is the actual item number(barcode) AND so that they can search for it in the client.

ILLNumber can mean different things for different kinds of ILL requests, however, the barcode does not technically need to be in the item number field other than for clarity in the client. If you are really against repeating the information in two fields in the app, I can remove the #rft.item param, but then it won't show up in the ItemNumber field ion the client.

**Comment by jkeck** [comment]
Not against it at all, just looking for clarity.  Thanks for explaining.

**Comment by jkeck** [comment]
Closed by #480
