### ISSUE TITLE
Add drop-down to select a pickup-library/destination

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/sul-requests#48]
- [x] Default set
- [x] Library specific set
- [x] Location specific set

**Comment by jvine** [comment]
**Default set**
ART
BIOLOGY
BUSINESS
CHEMCHMENG
EARTH-SCI
EAST-ASIA
EDUCATION
ENG
GREEN
HOOVER
HOPKINS
LAW
MATH-CS
MUSIC
SAL

**Library-specific set**
ARS
HOOVER 
HV-ARCHIVE
SPEC-COLL
(Note that this list covers the -30 locations)

**Not a library, but will be**
MEDIA-MTXT

**Location-specific set**
(i.e. PAGE-* locations that define the pickup library)
AR -> ART, SPEC-COLL
AS -> ARS
BI -> BIOLOGY
BU -> BUSINESS
CH -> CHEMCHMENG
EA -> EAST-ASIA
ED -> EDUCATION
EN -> ENG
ES -> EARTH-SCI
GR -> GREEN
HA -> HV-ARCHIVE
HL -> HOOVER
HP -> GREEN, HOPKINS
HV -> HOOVER
IRON -> BUSINESS
LAW -> LAW
LP -> MUSIC, MEDIA-MTXT
MA -> MATH-CS
MD -> MUSIC, MEDIA-MTXT
MP -> EARTH-SCI
MSS -> SPEC-COLL
MU -> MUSIC
SL -> SAL
SP -> SPEC-COLL

**Just FYI, these libraries are never pickup libraries**
CLASSICS
LATHROP 
SAL3
SAL-Newark
TANNER
