### ISSUE TITLE
Remote users aren't seeing the "on site" note

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-requests#491]
Increased coverage of request form means more remote users finding items via Google and requesting (what they think will be) an e-version of the item. Spec is following up with users on a daily basis, and canceling requests when the user learns they must be on site.

Need a more effective solution than a note on screen.

**Comment by jvine** [comment]
From SW-1590 and multiple direct emails from Tim.

**Comment by jvine** [comment]
- [ ] Change "Must be used in" to "Will be delivered to"
- [ ] Change "Planned date of use" to "I plan to visit on"
- [ ] Move the text from the `<div class="alert alert-info"...` to a `<div class="help-block">` immediately below the date-picker
- [ ] Drop the `<h4>` text from that block 
- [ ] Wrap a `<div class="alert alert-warning"...` around the location, delivery, and date-picker 
- [ ] Futz with the margins until it doesn't wrap funny. Use of `white-space: nowrap` allowed.

## Before
![screen shot 2016-10-03 at 3 00 06 pm](https://cloud.githubusercontent.com/assets/6945691/19056022/cc659dde-897b-11e6-9bc2-6c21aebe6ef0.png)

## After 
![on-site-access-rumsey](https://cloud.githubusercontent.com/assets/6945691/19056032/d5221e52-897b-11e6-85f1-bddb1318916a.png)

**Comment by jkeck** [comment]
There will most likely be some CSS tweaking to get this to look right.  Unless we can get it exactly like the comp above, we should wait for @jvine to be back before :ship:ing.

**Comment by jkeck** [comment]
One potential issue with putting the library instruction as help text on the date picker field is that not every request form will have that field.  In practice right now, only SPEC-COLL and RUMSEYMAP have library instructions and I believe they both should get the date field, but we can't guarantee we won't try to add library instructions for a library that doesn't get the date field (and then that text wouldn't show up).
