### ISSUE TITLE
Users who enter invalid library ID are then not able to request by name + email

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-requests#493]
User enters a library ID plus name + email in a page request. Library ID is bad - either expired, or not the right kind, or whatever. Request fails. User then tries to enter only name + email, but we have permanently linked the name + email to the ID, and they continue to get "request failed" messages. User workaround is to use a different email address. Backend workaround is to manually delete the library ID from the requests database. Would be better to just use the info entered, and not link name + email to a previously entered ID.

SW-1588 plus December discussion in Slack channel around user marvina.

**Comment by jkeck** [comment]
The place where this logic lives is in the [`autosave_associated_records_for_user`](https://github.com/sul-dlss/sul-requests/blob/27a0435b538a5fedfd1b77f0b0488fff230b1452/app/models/request.rb#L65-L94) method and the methods that it  calls.

Basically, if a user is not a webauth user and did not supply a library ID, we use the given email address to attempt to associate the request with the appropriate user record.  When this record has a bad library ID then things start going awry.

**Comment by jgreben** [comment]
@tingulfsen: these web services gists might help you. LEt me know if you have any questions. You will need to use a special Symphony login an dpassword to make the lookup work: https://gist.github.com/jgreben/c3052ecc7531d63027f8811417787b56 and https://gist.github.com/jgreben/41e351012fab570ce130ab16838cf171

**Comment by tingulfsen** [comment]
I just had a chat with @jvine and @jkeck regarding this ticket. My initial idea was to prevent the user from being able to submit a request with an invalid library ID by doing a Symphony lookup. But we agreed it's probably better for now to make sure that we search and save users based on BOTH their library ID and email address. Currently, we only do the lookup by email.
