### ISSUE TITLE
Javascript in mediation UI not working for 1 known user

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-requests#494]
Julie is unable to mediate requests from her computer. She clicks to open a row, and a little space opens, but the embedded table never displays - never, ever.

Windows 7 Enterprise service pack 1; Chrome 47.0.2526

This is consistent on her browser (and witnessed by Sarah S) but I cannot reproduce it on cross-browser testing.

![image001](https://cloud.githubusercontent.com/assets/6945691/12861519/d3d1e2b0-cc18-11e5-803e-dabb0fc664bf.jpg)

**Comment by jgreben** [comment]
@jvine, (just my $0.02) I can see she has some kind of browser plug-in running. Maybe try disabling some or all of the plug-ins and see if that helps? When you do cross-browser testing does that mean you could not reproduce it on a different Windows machines as well?

**Comment by jvine** [comment]
@jgreben I can see LastPass, but I don't see anything else...? I only tried the one combination.

**Comment by jvine** [comment]
superseded by #507
