### ISSUE TITLE
Double requests, and double mediations still happening

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-requests#496]
We are still seeing incidents (1-2 daily) of users submitting a request, then resubmitting it a second later; they end up seeing the "You already have a hold" failure message.

Same issue seems to be happening with mediation, specifically with Hoover, where they try to zip through a list of requests and get a lot of "user already has a hold" notices. 

![pastedimage](https://cloud.githubusercontent.com/assets/6945691/12862713/f15c4f5a-cc22-11e5-8be5-b77c16419e8a.png)

**Comment by jkeck** [comment]
We're going to check after we move requests to background workers to see if users stop getting double requests.

We believe the issue for mediators has already been solved.

**Comment by ndushay** [comment]
we've done work to address this;  will close this and open specific new tickets if there are still problems.
