### ISSUE TITLE
@stanford.edu email isn't available for all sunetids

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-requests#497]
greencirc@stanford.edu is getting bounces from request confirmation emails to users who do not have a sunetid@stanford.edu address. That means the users aren't getting their confirmations.

Apparently users such as visiting scholars can have a sunetid and library privileges, but no sunetid@stanford.edu email account. Their actual email is in Symphony. 

Can we do anything with this? Can we tell from the webauth response whether they have a full service sunetid and if not, treat them like libraryID-only users (which I think has no confirmation email)?

**Comment by jkeck** [comment]
We would like to get this from LDAP (not from symphony).
