### ISSUE TITLE
Branner mediators getting AccessDenied errors

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/sul-requests#507]
Note: Branner's mediation is location based (`PAGE-MP`).

Mediators for Branner are able to get to the admin screen for their mediated requests (`/admin/PAGE-MP`), but when trying to view the details of the individual item (`/admin/:request-id/holdings`) they are getting `AccessDenied` errors.

One possible cause is that these items are mediated under location and not library, and the CanCan ability to manage mediated pages is not setup appropriately.

**Comment by jvine** [comment]
replaces issue #494
