### ISSUE TITLE
Remove "unlisted items" feature

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-requests#510]
Remove the label, input, and help block for unlisted items.

Before
![screen shot 2016-04-27 at 11 21 54 am](https://cloud.githubusercontent.com/assets/6945691/14863372/4b37dc38-0c6a-11e6-8575-90100e466807.png)

After
![screen shot 2016-04-27 at 11 20 09 am](https://cloud.githubusercontent.com/assets/6945691/14863333/1f799212-0c6a-11e6-806a-e8918c7a9b89.png)

**Comment by jkeck** [comment]
SAL-NEWARK/SPEC-COLL are the only ones that gets this.  (SAL-NEWARK may only get this under a rare circumstance).

Check @jvine before removing the feature.

**Comment by ndushay** [comment]
from config/application.rb:

```
config.ad_hoc_item_commentable_libraries = ['SAL-NEWARK', 'SPEC-COLL']
    config.item_commentable_libraries = ['SAL-NEWARK', 'SPEC-COLL']
```
