### ISSUE TITLE
Truncate long titles in admin UI

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-requests#511]
Truncate title at max 2 lines of text in admin table. 

Before
![screen shot 2016-04-27 at 11 30 34 am](https://cloud.githubusercontent.com/assets/6945691/14863724/c6343778-0c6b-11e6-9380-4fbd4f00bd62.png)

After
![screen shot 2016-04-27 at 11 32 18 am](https://cloud.githubusercontent.com/assets/6945691/14863728/c8438442-0c6b-11e6-9a2e-b3143375829d.png)

**Comment by ndushay** [comment]
@jvine: in just the individual library request mediation tables, or also in requests dashboard?

**Comment by ndushay** [comment]
@jkeck is there a way to set things up locally so 

a)  we have permission for admin (ie. webauth isn't running on our laptops)
b)  we don't get this `Firefox has detected that the server is redirecting the request for this address in a way that will never complete.` for http://localhost:3000/admin

**Comment by jkeck** [comment]
@ndushay check out the section on configuring workgroups in the README: https://github.com/sul-dlss/sul-requests#workgroups.  There are some examples there how to set SUNet IDs to be in LDAP workgroups locally (and one workgroup you set yourself in should be listed as a super admin workgroup).

You can then set your SUNet ID locally by starting the development server with an env variable, e.g. `REMOTE_USER=sunet rails s`
