### ISSUE TITLE
Verify whether archived requests can still be approved

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-requests#512]
Approve link is active for archived requests, but Spec reports that they are not able to approve an item once the request has been archived. "If a patron has requested too much material and the request link gets archived, if we go to approve the boxes it doesn’t allow us to approve them."

Archived request, active button...
![screen shot 2016-04-27 at 11 44 51 am](https://cloud.githubusercontent.com/assets/6945691/14864148/7c6e7480-0c6d-11e6-9794-959646d2bdf7.png)

**Comment by jkeck** [comment]
From my local tests (and from looking at the code path for mediated item approval) I don't believe there is anything that we're explicitly doing to prevent archived/expired mediated pages from being approved.

Can we get any more details about how it's failing?  Perhaps we're conflating the other mediated item approval issues with this?

**Comment by ndushay** [comment]
Tim reported this specifically but it may have been a mistaken understanding.

**Comment by jvine** [comment]
From Tim:

> If you go to Tuesday October 11 for a patron Caitlin Cawley there is a box that wasn't approved and if you do it gets this message:
> 
> MSS-30 M2042 FLAT BOX 21 Date hold expires may not be earlier than today.
> 
> We then need to re-request so that we can approve the order.

Is this an error code coming back from Symphony?

**Comment by jvine** [comment]
Note that this may be resolved by #530.

**Comment by jvine** [comment]
Closing this based on #530.
