### ISSUE TITLE
Sort and search requests table

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-requests#514]
Allow search and sort across all archived requests (not just in the current page).

**Comment by jvine** [comment]
SW-1651
SW-1665

**Comment by jvine** [comment]
Problems around:

- items moving to "archived" based on needed-on date
  - requests with no needed-on date never get archived
  - requests not approved for the requested date roll out of view
- difficulty for spec in seeing all the requests for one date when some may fall across a page break
- difficulty navigating a long list to find a specific date

Proposal:

- [ ]  filter list by "done" and "not done" 
- [ ] allow staff to mark items as "done" to move them out of pending view [separate issue #539]
- [ ] for libraries with "needed on" dates, add filters for next three business days
   - [ ] bonus points:  don't show a date that has no requests (pending or done)
- [ ] for libraries without "needed on" dates (Branner, Hopkins), show only Pending/Done
- [ ] within a selected date, show done and not done together
- [ ] add a "jump to date" calendar picker (same control as Hours)

![screen shot 2016-09-16 at 10 36 06 am](https://cloud.githubusercontent.com/assets/6945691/18597567/6f800332-7c03-11e6-88c9-bb6cfef9bfbc.png)

![screen shot 2016-09-16 at 12 05 35 pm](https://cloud.githubusercontent.com/assets/6945691/18598063/f33c3162-7c05-11e6-9b06-0b166771d35b.png)

![screen shot 2016-09-16 at 12 01 06 pm](https://cloud.githubusercontent.com/assets/6945691/18598210/81e53de6-7c06-11e6-8c13-00478b7f5891.png)

**Comment by saseestone** [comment]
While it's true that usually we have the date (or a date range) for the request that we're looking for, that's not always the case.  We always know the name of the Requester.  So the ability to search the data table by requester would be extra helpful.
