### ISSUE TITLE
Comments with quotes are truncated

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-requests#515]
https://requests.stanford.edu/mediated_pages/34092/status

The Comment field in this request was:
>  Testing to see if the "(something in quotes)" came through

and the text got truncated at the first ".

**Comment by ndushay** [comment]
@jvine we cannot reproduce this;  can you please try to reproduce?   (We were running locally on Jessie's laptop, and using your exact string above in both text areas (item request and comment), nothing got truncated.

**Comment by jvine** [comment]
tried this in prod, and the content in quotes came through fine. i'm calling this closed.
