### ISSUE TITLE
Add staff note field to request mediation space

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/sul-requests#519]
Staff in Branner have requested an area in the staff mediation space for Branner Maps to record notes on a particular request.  They would use the notes field to record and easily communicate the logic behind a decision to approve or not approve a request.  While they didn't specify if the notes should be at the request level or the item level, I think it would have to be at the item level.  Any request based notes could just be recorded on the first item that is listed.

**Comment by jvine** [comment]
IMO, comments should be at request level. Indication from Spec is that they are dealing with the request as a whole. Easier to refer from top level to a specific item, than extrapolate from item to top level. 

- [ ] Add a "Comment" button in the open request, above the table.

![mediate - mark done and comment](https://cloud.githubusercontent.com/assets/6945691/18599754/c8e0278a-7c0e-11e6-94d3-7994036777c3.png)

User clicks the button:
- [ ] Add a text field plus OK and Cancel buttons, below the active "Comment" button.

![mediate - comment form copy](https://cloud.githubusercontent.com/assets/6945691/18599758/cddd7fa8-7c0e-11e6-963b-00392f99d092.png)

- [ ] Display saved comments as a list, above the table, and below the form.
- [ ] add user ID and date/time to the comment - same format as "Approved by" column.

![mediate - comment](https://cloud.githubusercontent.com/assets/6945691/18599764/d8f9506a-7c0e-11e6-9d5d-e7e52ca2e508.png)

If user adds a second comment, 
- [ ] open text field below the buttons, above the older comments
- [ ] list multiple comments in chrono order

![mediate - comment form](https://cloud.githubusercontent.com/assets/6945691/18599774/e2755152-7c0e-11e6-8049-22281c0276ce.png)

**Comment by saseestone** [comment]
Jennifer, Team,

I agree that comments can be at the request level.  If there is a case of item specific comments, they can certainly handle that in the text (i.e. “Didn’t page volume 4 because of issues with the binding.”)

Love the name and date stamp.
Love the simple design and chrono order if there are multiple.  I’m assuming most recent at the top.  Right?

This all looks great based on my discussions with Spec and Branner.
Sarah
