### ISSUE TITLE
Add ldap check to is_it_working config

### ISSUE THREAD

**Issue by eefahy** [sul-dlss/sul-requests#520]
see https://github.com/sul-dlss/sul-directory/blob/master/config/initializers/is_it_working.rb#L10-L16

**Comment by ndushay** [comment]
We believe it was decided that app status check is not the best place to check if LDAP is working.  Do you agree, @eefahy?

**Comment by ndushay** [comment]
spoke to chris beer about this;  agreed that this ticket should not be completed.
