### ISSUE TITLE
Ignore some Symphony error responses  (like 722)

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-requests#531]
Any Symphony condition that results in the user having a hold on the material should be accepted as a success. Specifically:
- [ ]  "(User already has a hold on this material)" should not generate an alert to the user
- [ ]  are there more?

Related to #423

**Comment by jkeck** [comment]
@dlrueda can you validate the code(s) that we should add as being successful?  For reference, this is what we have configured currently: https://github.com/sul-dlss/sul-requests/blob/af4db69c4415bb09e3faf7d94377a1d696dbf8c4/config/application.rb#L165

**Comment by dlrueda** [comment]
Looks like P002B is on my list of success codes but not on yours... and it's a very edgy edge case...

Success codes
Code    Text
209      Hold placed
S001    Scan submitted
P001    Paged
P002    Hold placed for HOLD@xx
P002B  Not on shelf, hold only placed for HOLD@xx user
P001B  Not on shelf - hold placed for HOLD@xx
P005    Not on shelf - hold placed


Not success codes
7          Item not found in catalog
722     User already has a hold on this material
I001    Record doesn't exist
U001   Required field missing: Library ID
U002   Library ID doesn't exist
U003   User is BLOCKED
U004   User's privileges have expired
P004    Not a paging library
P003   Item not valid for page

**Comment by jkeck** [comment]
@dlrueda but we should be adding `722` to our list now, correct?  I believe that's the idea behind this ticket.

**Comment by dlrueda** [comment]
Ah right.  Yes, I believe adding 722 to the Success list is the right thing to do.  (Sorry I didn't catch on before.)

**Comment by dlrueda** [comment]
Jessie and I found a problem with allowing "User already has a hold on this material" for SAL and SAL3.  If the user is webauthed or puts in a specific library ID, it's fine.  It would mean the item is being paged for that particular user, so all is well.

However, if it's a name/email being submitted, then the hold is being placed for the HOLD@xx pseudopatron. The hold cannot be placed again, and the current hold cannot have the new user's name/email added to it as a comment (it has first users's name/email in the comment).

The Symphony code handles this situation for Spec Coll items by adding a new entry to the picklist, and adding a note alerting the staff that this is a 2nd request for same item for HOLD@SP user.

I would need to add similar code for SAL and SAL-NEWARK items.  Or for all other paging libraries.  However, what to do about SAL3?  There is no comment or picklist for SAL3 items.  

This needs further discussion.

**Comment by jkeck** [comment]
After #573 is reviewed and merged, I'm hoping this issue is no longer posing a problem (which it's not actually a problem) for mediators.  Is this issue still persistent for users submitting forms?  Given the complication around the pseudo-patrons and multiple holds, we may want to see if #573 solves mediation (and potentially other issues to solve the end-user issue).

If this issue is still persistent for users (and cannot be solved by moving to background jobs) then we should look into providing a different status code or handling the status code we're receiving differently.

**Comment by jkeck** [comment]
It looks like we will consider 722 a success, but we will need to coordinate this change with updates to the requests code on the symphony side.

**Comment by ndushay** [comment]
@jvine is this the ticket about "when the user already has a hold?"   I marked it as high priority thinking that.

**Comment by jkeck** [comment]
@dlrueda says that we will investigate continuing to consider 722 an error, but considering certain cases that are now returning a 722 NOT a 722 in the future.

**Comment by ndushay** [comment]
@dlrueda talked to Sarah:

In some cases 722 will be returned to the requests app -- in these cases, it should be considered success.  This could happen for hold/recall or for a page ...

**Comment by dlrueda** [comment]
Symphony code in test (-stage) is handling all cases of 722.  Ready to move to production.  Need to coordinate with Sarah, her staff will get email alerts, she needs to warn them before go to prod.

I THINK I can move Symphony code to prod before requests app handles 722 as a Success code?  Or need to coordinate this move to prod, do together?

**Comment by jkeck** [comment]
If 722s that are returned to the requests app will need to be considered a success then we'll need to coordinate with the change to our code.

**Comment by ndushay** [comment]
This is ready for live testing.
