### ISSUE TITLE
Add link to / instructions re finding aid to request form (has SW api component)

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-requests#536]
SW-1660 parent ticket but there are a couple more.

**Comment by jvine** [comment]
If collection has a finding aid, add a block to the bottom of the item selector box. Link to the finding aid, with an "outside link" icon following the link. Add `title="Opens in a new window"` to the `<a>` tag.

![screen shot 2016-09-15 at 4 20 58 pm](https://cloud.githubusercontent.com/assets/6945691/18570822/0379b454-7b62-11e6-92f7-f228afb57a3b.png)

**Comment by jkeck** [comment]
This ticket will require a small change to the SearchWorks codebase.  [This line](https://github.com/sul-dlss/SearchWorks/blob/b8d1eacfa3a174b7ce2e5ea26b37445c7a6eb882/app/controllers/catalog_controller.rb#L379) will need to be changed to use the `finding_aid` index link and not the `fulltext` index link.  We're not actively using these links, so this shouldn't be a problem to change.

**Comment by jkeck** [comment]
Let's use a new field from the API (like `finding_aid`) for this.  That way we can code this up and deploy it, and it will appear once the SearchWorks API returns the finding aid in that field.
