### ISSUE TITLE
Truncate comments at 2 lines with more/less toggle

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-requests#540]
Default is closed:

![screen shot 2016-09-16 at 11 44 08 am](https://cloud.githubusercontent.com/assets/6945691/18597466/0a450b84-7c03-11e6-80c1-1bfc34cd0e76.png)

User can click to expand in place, and collapse again:

![screen shot 2016-09-16 at 11 43 41 am](https://cloud.githubusercontent.com/assets/6945691/18597467/0a468b8a-7c03-11e6-9511-fab73f48e4aa.png)

Same logic as in SW masthead:
https://searchworks.stanford.edu/catalog?f%5Bcollection%5D%5B%5D=4085340

**Comment by ndushay** [comment]
See also #566
