### ISSUE TITLE
Add scan option to additional SAL3 locations

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/sul-requests#543]
For Item Library = SAL3, add the ability for the user to choose the scan & deliver option for items in Home Location = PAGE-GR.

Possibly also add the following Home Locations (pending DO approval):
PAGE-SP
PAGE-EA

Some items in Home Location = PAGE-GR have an item type = NH-INHOUSE or NEWSPAPER.  They want these items to be scannable, so we need to make sure that we're NOT restricting the scan option based on the "NH-" item type prefix or by something like record format.

**Comment by jkeck** [comment]
FWIW the current acceptable item types globally are `BUS-STACKS` `STKS` `STKS-MONO`, and `STKS-PERI`.  This will require that we do something like build location specific item type logic.

**Comment by jkeck** [comment]
Just confirmed with @saseestone that `PAGE-SP` and `PAGE-EA` are good to go.

**Comment by saseestone** [comment]
Unfortunately I just triple checked with Rebecca Pernell and she says that PAGE-SP and PAGE-EA are **NOT** good to go.  (ugh...how the wind blows around here....)  So we should only move forward with PAGE-GR.

Example ckeys for all 3 locations are:

PAGE-GR:
https://searchworks.stanford.edu/view/11613538
https://searchworks.stanford.edu/view/10736132

PAGE-EA:
https://searchworks.stanford.edu/view/9068720
https://searchworks.stanford.edu/view/8640111

PAGE-SP:
https://searchworks.stanford.edu/view/11715291
https://searchworks.stanford.edu/view/11693458
