### ISSUE TITLE
Sort and Filter options needed in Request Dashboard

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/sul-requests#544]
This issue is similar to sort and filter options requested by Mediators.  (#514)

ILL staff are consistently using the Requests dashboard to: 
1. Find a particular Scan request submitted on a particular date/timestamp to get to the Request Status link and view the complete user comment.  It appears that for some requests, user's comment gets cut off in the exchange between the request app and ILLiad. 
1. Find a particular title so that they can determine the Requester of that title.  This happens when they get a book in their SAL3 shipment, but don't get the request information in ILLiad (which used to happen a lot, but hasn't happened in the few months...)
2. to double check that they have all the requests submitted

Currently they are using the ctrl-F function to search for "Scan" and then paging through results.  Being able to limit by "Type" would be helpful.  Or separating out the Scan requests into a dashboard just for them would also work.  

Adding a "Jump to date" calendar picker would help all of us using the Requests dashboard.

**Comment by ndushay** [comment]
we've done work to address this;  will close this and open specific new tickets if there are still problems.
