### ISSUE TITLE
get holdings/current location from symphony web svcs for barcode level item status on mediation page

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/sul-requests#546]
We can use this on the mediation page to improve the speed of fetching the holdings/current location.

**Comment by jgreben** [comment]
These might work better for you: https://gist.github.com/jgreben/188ada8f9a9d493c06628e813e74188a and https://gist.github.com/jgreben/c9219e3f610a1b3db0739214bbc67880

**Comment by ndushay** [comment]
branch in progress (badly named as this is 546):  547-live-lookup-by-barcode

**Comment by ndushay** [comment]
@jkeck if we want to do this, I think I have the pieces we need, maybe.

**Comment by ndushay** [comment]
is this part of #547, or is it something else?

**Comment by jkeck** [comment]
We think this was resolved by @jgreben supplying us with the info.
