### ISSUE TITLE
Get current location for barcode for mediation via symphony web services

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/sul-requests#547]
Instead of using the SearchWorks Availability API to get the current location use the symphony web services API.

See #546 for details on the web services API.

**Comment by ndushay** [comment]
Pieces:
- requests app to SW LiveLookup (current location, status ...): (send in flag?) needs to stop going to symphony for live availability info
- requests app to use Symphony Web Services directly to get live lookup by barcode as it will be faster than the SW call to symphony by catkey

**Comment by jkeck** [comment]
For those following along at home, @ndushay and myself are submitting PRs to the [improved-item-lookup](https://github.com/sul-dlss/sul-requests/tree/improved-item-lookup) branch.  We'll then submit a PR from that branch to master once we're ready for review.

**Comment by ndushay** [comment]
Also for those following at home, Shelley found a better symphony web services call for this purpose than the one suggested in #546.  Details in the code.

**Comment by ndushay** [comment]
I'm probably confused - but how does this ticket differ from ticket #546?
