### ISSUE TITLE
use shared configs / update shared_configs methods

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/sul-requests#561]
if the requests app is using shared_configs, then they are not in the (new?) standard place.

- change puppet so shared_configs go in standard place
- use capistrano/shared_configs  or  some other mechanism (chris beer's work in dlss-capistrano?) to make updating shared_configs part of the deploy

**Comment by ndushay** [comment]
@jkeck  it looks like there are branches in shared_configs, but they are not called out in puppet ...

**Comment by jkeck** [comment]
Ah, I think we were getting those ready (and the shared configs paradigm was just forming) when we stopped development on requests.

Luckily, that means that 1/2 our job is already done!

**Comment by jkeck** [comment]
PR to puppet is merged.  Just waiting for puppet to run on each machine.

**Comment by ndushay** [comment]
can this be closed now?

**Comment by jkeck** [comment]
Yeah, we were keeping it open to follow up on if a change to the shared configs branch in puppet changed the branch on the VM (which my indication is that it does not).
