### ISSUE TITLE
Connect to SearchWorks API

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/sul-requests#57]
Pull in title information through the SearchWorks API.

We should probably tack on basic title information to the eventual Availability API that we'll create in SearchWorks, until then, we can use the mobile API to get basic title info. `http://searchworks.stanford.edu/view/#{ckey}.mobile?covers=false`

We should store the title along w/ the ID to make fetching easier on the admin/mediation interface.

**Comment by jgreben** [comment]
Does anyone mind if I try to tackle this? Is there documentation for the mobile searchworks api? or are there anymore fields than this?
![screen shot 2015-04-21 at 6 02 39 pm](https://cloud.githubusercontent.com/assets/3093850/7265578/c67a9578-e850-11e4-9dc6-a4055c88ba5e.png)

**Comment by jkeck** [comment]
@jgreben sure!  WRT any documentation on the API there really isn't any.  The scope of this ticket is to pull the title out of the response that you linked above so I don't think you need much more than what you already have.

A couple of thoughts I have about this that may help you get on your way.

1. We like [Faraday](https://github.com/lostisland/faraday) for making HTTP(S) connections.
2. We like (and have already as a dependency) [RailsConfig](https://github.com/railsconfig/rails_config) for configuring things like URLs to APIs (as well as other handy things).
3. This should be hooked up somehow in the Request model.
  * There is already some initial plumbing in the request model to store the ID of a SearchWorks item.

Feel free to submit a PR w/ your code and we can start from there (make sure to write/run your tests!).  Alternatively; if you prefer, we can talk/walk through the code you have tomorrow.
