### ISSUE TITLE
Remove Hoover Library from mediated library list

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/sul-requests#578]
Hoover Library does not need to be in the mediated library list.  Paul Thomas and Maria Quinonez  have indicated that any items physically stored at SAL3, with a Library = HOOVER and a Location = STACKS-30 should have a request link, and the items can be added to the SAL3 picklist without prior staff approval.

**Comment by ndushay** [comment]
@jkeck:  Is this as simple as getting rid of this

https://github.com/sul-dlss/sul-requests/blob/master/app/models/concerns/mediateable.rb#L11

and the config stuff in `application.rb` ?

**Comment by jkeck** [comment]
Does this apply **only** to Hoover library (and not the archive)?  If so, we'll need to git in and modify the methods a bit more.

We may want to also remove the HOOVER `origin_admin_groups` in our `settings.yml` in `shared_configs` so that the link doesn't show up on the home page anymore either.

**Comment by jvine** [comment]
Just Hoover Library
