### ISSUE TITLE
Change text on confirmation email for move to background workers

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/sul-requests#586]
Will we need to make changes to the text on the confirmation email?  Should the email wait for the status of the symphony request before being sent, or send the email immediately once we receive the user's request?

If we want to wait for symphony's response, we should probably change the text to include information on the status of the request.

**Comment by ndushay** [comment]
depends on #587

**Comment by jvine** [comment]
### From address
is currently:
`"greencirc@stanford.edu" <greencirc@stanford.edu>`
(and possibly a different email address per library). Can we make it this:
`"Stanford Libraries Requests" <whateveremail@stanford.edu>`

### Title
for success:
- Your request has been processed ("Title")

for failure: 
- Attention needed:  Your request could not be processed ("Title")

(Note the quotes added around the title in parens.)

### Body for successful request

```
On Tuesday, Nov 15 2016, you requested:

    Title

The items listed below have been processed:

    PN4841 .E3 V.28 1953 - hold placed
    PN4841 .E3 V.27 1952 - hold placed

Not needed after:  ...

Any further updates will be posted on the status page at https://requests.stanford.edu/pages/65214/status
You can also see the status at http://library.stanford.edu/myaccount
```

### Body for failed or mixed request

```
On Tuesday, Nov 15 2016, you requested:

    Title

There were problems with one or more of the items listed below:

    PN4841 .E3 V.28 1953 - hold placed
    PN4841 .E3 V.27 1952 - awful Symphony error message

What can you do now?

    Request assistance by replying to this email, or
    try your request again, at https://searchworks.stanford.edu/view/4320145
```

### Body for user blocked

```
On Tuesday, Nov 15 2016, you requested:

    Title

Items:

    PN4841 .E3 V.28 1953
    PN4841 .E3 V.27 1952

Your request could not be processed because your user privileges <have expired/are blocked>.

What can you do now?

    Request assistance by replying to this email, or
    check MyAccount (http://library.stanford.edu/myaccount) for more information. 
```
and add the logic for this bit from the success page:
```
Just need a chapter or article?
     Even though your status is blocked, you are eligible for Scan to PDF. 
     You can request a single article or chapter, up to 50 pages.
     https://searchworks.stanford.edu/view/4320145
```

### And then the footer as it exists now:

```
Questions about your request?
Contact:
 (650) 723-1493
 greencirc@stanford.edu
```

**Comment by jkeck** [comment]
After conversation with @jvine: these email updates will not apply to scan OR mediated page (they should retain the confirmation mail behavior).

Pages and HoldRecalls should get the new processing complete mail behavior.

**Comment by jkeck** [comment]
Work in progress on `586-email-text-changes`
