### ISSUE TITLE
Prevent users who enter wrong library IDs from submitting requests

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/sul-requests#588]
Users entering library IDs that are incorrect or do not have privileges can be a problem.  If we can safely query symphony for library IDs we could do some up-front validation before we allow the user to submit the request (which will be particularly friendly once we move requests to being processed in background jobs).

See https://github.com/sul-dlss/sul-requests/issues/493#issuecomment-254661908 for more details about potentially accessing this information.

**Comment by cbeer** [comment]
Replaced by #1272
