### ISSUE TITLE
proxy: dlss-wowza honeybadger deploy

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/sul-requests#599]
sul-dlss/dlss-wowza#45

sul-dlss/dlss-wowza#46

**Comment by hannahfrost** [comment]
@jmartin-sul I was asked to assess how urgent this is, in particular relative to the Requests work underway. It seems pretty important to have Wowza monitored. Can you offer an estimate of time needed to finish? Are we even in ready to start finishing, or are we waiting on something in puppet?
