### ISSUE TITLE
need PAGE-RM location

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/sul-requests#605]
Implement a new location: PAGE-RM

The drop down for pickup library should be limited to RUMSEYMAP for requests being made on items with this location.

Pages will be NON-MEDIATED.  (Just plain SAL3 page requests.)

**Comment by ndushay** [comment]
does this need coord with libsys team or is your part done?   What about SW or other apps?  @jkeck??

**Comment by jkeck** [comment]
AFAIK this doesn't need to be coordinated with symphony (or rather it probably already exists, which is what prompted this ticket).

There is already a SW ticket: sul-dlss/SearchWorks#1291

And that should be it. 😄

**Comment by jkeck** [comment]
For the requests app purposes we should really only have to add a location -> pickup library mapping in the [location_specific_pickup_libraries](https://github.com/sul-dlss/sul-requests/blob/ddda727a1fe76ad23864325739531215ce500e3f/config/application.rb#L108) configuration.

The other pieces will be taken care of in sul-dlss/SearchWorks#1291 (which this is a pre-requisite to).

**Comment by ndushay** [comment]
pushed branch 605-add-page-rm-location  with the change.  Will confer with @dlrueda tomorrow.

**Comment by ndushay** [comment]
Darsi confirms that a) symphony doesn't yet have this location  and  b) that we should do the requests and SW  work on this  before they add the location to symphony and start creating such data.
