### ISSUE TITLE
Add 5-item limit to SAL3 PAGE-SP items

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-requests#606]
For items that are not in Spec as a library, but are paged to Spec, add 5-item limit.

Example record https://searchworks.stanford.edu/view/35581 

SW-1709

**Comment by jkeck** [comment]
This will require that we allow for some location specific item limits to be defined in the `MediatedPage` class and fetched [here](https://github.com/sul-dlss/sul-requests/blob/6448b8af0e2859a1ffc1bceb6b4c956cc720cb52/app/models/requests/mediated_page.rb#L43-L45).
