### ISSUE TITLE
Optimize/confirm Sidekiq configuration

### ISSUE THREAD

**Issue by tingulfsen** [sul-dlss/sul-requests#627]
We need to take a close look at the Sidekiq configuration to make sure that our settings make sense. In particular I'm thinking about:

- [ ] Prioritization between threads/processes
- [ ] Redis configuration
- [ ] Number of queues

etc.

I'm not saying that using the default configuration settings is wrong - just that we need to avoid getting bit later on like with did with Argo (although I think the number and size of background jobs is much lower for Requests).

**Comment by ndushay** [comment]
so is this ticket done?  Or not yet?
