### ISSUE TITLE
Document the background processing

### ISSUE THREAD

**Issue by tingulfsen** [sul-dlss/sul-requests#628]
This may be an obvious one - but we should make sure to document how the background processing works after it's been added (presumably in DevOpsDocs).

**Comment by ndushay** [comment]
There is an open PR in DevOpsDocs that Tommy wrote.

**Comment by tingulfsen** [comment]
Now fixed by sul-dlss/DevOpsDocs#106 and sul-dlss/DevOpsDocs#99
