### ISSUE TITLE
Set up the Sidekiq web UI

### ISSUE THREAD

**Issue by tingulfsen** [sul-dlss/sul-requests#629]
Our chosen background processing framework - Sidekiq - comes with a rather nice [web application/UI](https://github.com/mperham/sidekiq/wiki/Monitoring) that displays statistics and statuses.

We should consider setting this up for Requests.

I suppose one issue would be who (what user level) gets to access this page?

**Comment by jkeck** [comment]
I'm thinking super admins initially.  If we determine that it would be helpful for site admins to have access to the queue, we can easily change that later.

**Comment by ndushay** [comment]
@jkeck informs me that exhibits has done something very similar and to model our work on that.
