### ISSUE TITLE
Add a "jump to date" calendar picker on dashboard and mediation UI

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/sul-requests#632]
Pulled from #624 

We should use the same date selector as the Hours app.

![screen shot 2016-09-16 at 12 01 06 pm](https://cloud.githubusercontent.com/assets/6945691/18598210/81e53de6-7c06-11e6-8c13-00478b7f5891.png)

**Comment by ndushay** [comment]
part of #544?

**Comment by ndushay** [comment]
@jvine:  is this for the needed-on  date and for those libraries only?   Or is it also for the requested-on date for those libraries without a needed-on date?

**Comment by jvine** [comment]
Feature should be available for all libraries and the requests dashboard - which means it does need to find requested-on dates. Checking w Sarah to see if it also needs to find needed-on dates.

**Comment by jvine** [comment]
Okay, the use cases we're aware of are all around requested-on dates. So let's do requested-on across all contexts for now.

**Comment by ndushay** [comment]
follow pattern in toolbar of library hours that is html5 picker.  The one here:  https://sul-library-hours-prod.stanford.edu/

**Comment by ndushay** [comment]
> it should be like a variation of the specific date filter - show all the pending and done from that date (though it’s a different date)

(from slack chat with jvine)
