### ISSUE TITLE
Update definition of what is scannable

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/sul-requests#65]
Depends on #57 and possible #16 

We currently define scannable by the origin being "SAL3" and the origin_location being "STACKS".

This needs to be refined to limit things that have a resource_type of either "Book" or "Journal/Periodical".

At the item level, we'll restrict based on circulating item types. (For SAL3: STKS, STKS-MONO, and STKS-PERI).

**Comment by jvine** [comment]
Confirmation from Darsi that she will be converting the items types for non-scannable items so that the definition above will be clean and accurate. She is aiming to have this done by end of May, but since the item type codes already exist, we shouldn't necessarily be dependent on the data cleanup.
