### ISSUE TITLE
fix pending spec (Library ID exists now?)

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/sul-requests#668]
We have one pending spec with a message about Library ID.  Didn't Tommy implement some stuff with library ID?   Should this spec still be pending?

https://github.com/sul-dlss/sul-requests/blob/master/spec/features/create_hold_recall_spec.rb#L9

**Comment by ndushay** [comment]
See #476

**Comment by jkeck** [comment]
That ticket is unrelated to the work that @tingulfsen did wrt library ID.  #476 is more about HTML5 form validation and different authentication requirements.  I'll try to update that ticket with more details.
