### ISSUE TITLE
Double jump-to date fields when I jump in browser history

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-requests#670]
Here's how I did it:

Start at home page. Pick Spec. Click around a bit - pending, done, date buttons. Click browser Back button. Voilà.

Page refresh clears it.

![screen shot 2016-11-18 at 9 32 45 am](https://cloud.githubusercontent.com/assets/6945691/20439780/1c6c0646-ad72-11e6-8c2a-b32058559ef4.png)
![screen shot 2016-11-18 at 9 30 59 am](https://cloud.githubusercontent.com/assets/6945691/20439781/1c88374e-ad72-11e6-932d-c81cf7ce38b6.png)

**Comment by ndushay** [comment]
closing this in favor of #671
