### ISSUE TITLE
DEC 15:  enable Science library; retire 3 old libraries

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-requests#692]
This needs to be coordinated on Dec 15th, so the closed libraries can no longer be selected as pickup libraries.

config.libraries = {
'SCIENCE' => 'Science Library (Li and Ma)',

config.pickup_libraries = [ 
add:
- 'SCIENCE',

remove:
- 'CHEMCHMENG', 
- 'MATH-CS', 
- 'BIOLOGY',

**Comment by cbeer** [comment]
I'm assuming this was probably done?
