### ISSUE TITLE
Add scan-to-PDF for SAL items

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-requests#716]
Needs:
- details about which locations/types to allow
- coordination w Darsi on the systems end

**Comment by saseestone** [comment]
Here's a list of SAL Locations that should display the scan option in the request form:
EAL-SETS
EAL-STKS-C
EAL-STKS-J
EAL-STKS-K
FED-DOCS
HY-PAGE-EA
ND-PAGE-EA
PAGE-EA
PAGE-GR
SAL-ARABIC
SAL-FOLIO
SAL-PAGE
SAL-SERG
SAL-TEMP
SALTURKISH
SOUTH-MEZZ
STACKS
TECH-RPTS
UNCAT

Coordination with Systems will need to include:
- (Josh) ILL staff have requested a new folder be created in ILLiad for Scan requests for SAL1&2 items. Item, Request, and User information should be in the same format, and be placed in the same ILLiad fields as the current production requests submitted for SAL3 items.
- (Darsi) SAL and ILL staff have requested that items in 2 SAL locations (HY-PAGE-EA and ND-PAGE-EA) have holds placed for a new psuedopatron (User ID: EAL-SCANREVIEW), and have a pickup library = EAST-ASIA.  Items in all other approved SAL locations can have the hold placed for the standard psuedopatron (User ID: GRE-SCANDELIVER) and standard pickup library (GREEN).

Sarah

**Comment by dlrueda** [comment]
I have finished the Symphony code to handle SCAN requests for items with library=SAL, including separate pickup lib and pseudopatron for locations HY-PAGE-EA and ND-PAGE-EA.

Ready for requests team to allow requests for SAL materials in above locations.  Can you deploy to requests-dev so we can do some UAT/integration testing?

**Comment by jgreben** [comment]
Please also pull the shared_configs for sul-requests-dev because I added a yml configuration for sul_illiad that points to the sul-illiad-test server.

See https://github.com/sul-dlss/shared_configs/commit/2791f9713bb2784c6fb757bf4949bb00974a144a

**Comment by jkeck** [comment]
@saseestone do we have a paging schedule from SAL1/2 for scanning?

**Comment by saseestone** [comment]
Paging schedule for SAL1/2 scanning should be:

When paging to SCAN before 1:00pm the item will arrive after 6:00pm 1 day later
When paging to SCAN after 1:00pm the item will arrive after 6:00pm 2 days later
