### ISSUE TITLE
Reword request confirmation emails

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-requests#718]
### Subject line

hold, page, scan
> Request confirmed: "Title"

mediated page
> Request waiting for approval: "Title"

error condition (request failed)
> Attention needed: Your request could not be processed ("Title")

### First line

hold
> You have been added to the hold queue for the following item(s):

page
> The following items are scheduled to be delivered to [pickup library]:

scan 
> The following items have been queued for scanning:

mediated page
> The following items are waiting for approval. Items are typically approved 1-3 days before your scheduled visit.

error (bad library id)
> We were unable to process your request because the Stanford Library ID you entered (badidgoeshere) was not found in our system. 

error (patron blocked)
> We were unable to process your request because your status is BLOCKED. 

error (other)
> We were unable to process your request because of a system error.

### Title / call number block

> Title:  title goes here
> Call number(s):
>    *  call number 1
>    *  call number 2

If there is no call number, display `   *  (no call number)`

### Additional info

hold
> We'll send another email when your request is ready for pickup.
> 
> Request was placed:   Monday, May 22 2017 at 2:11pm
> Request will be canceled if it cannot be fulfilled before:   Tuesday, May 22 2018

page
> Estimated delivery:   Monday, Jun 15 2017, after 10:00am. 
> We'll send you another email when your request is ready for pickup.
>
> Request was placed:   Tuesday, Jun 13 2017 at 3:07pm

scan
> Title of article or chapter:   
> [content]
> 
> Earliest delivery:   Monday, Jun 19 2017, after 6:00pm
> We'll send you another email when your request is ready for download.
>
> Request was placed:   Thursday, Jun 16 2017 at 5:07pm

mediated page
> Request was placed:   Friday, Jun 9 2017 at 2:11pm
> Planned date of visit:  Tuesday, Jun 27 2017

error (bad library id)
> Try your request again using just your name and email:   https://searchworks.stanford.edu/view/11474214
>
> Request was placed:   Thursday, Jun 15 2017 at 2:11pm

error (patron blocked)
> Request assistance by replying to this email, or check MyAccount (http://library.stanford.edu/myaccount) for more information.
>
> Even though your status is blocked, you are eligible for Scan to PDF. You can request a single article or chapter, up to 50 pages.
>  https://searchworks.stanford.edu/view/11474214

### URLs
hold, page, scan, error
> You can see this request status online at http://requests.stanford.edu/pages/105683/status

... and this line appears if the user has a valid SUNet ID or lib ID
> You can also see and change your requests at http://library.stanford.edu/myaccount

mediated page
> Check the status before you visit, at https://requests.stanford.edu/mediated_pages/105249/status

### Footer
no change (contact info specific to library)

**Comment by jvine** [comment]
### Hold

> From: Stanford Libraries Requests <greencirc@stanford.edu>
> Subject: Request confirmed: "The handmaid's tale"
> Date: May 22, 2017 at 2:12:29 PM PDT
> To: <jvine@stanford.edu>
> 
> You have been added to the hold queue for the following item(s):
> Title:   The handmaid's tale
> Call number(s):
> -    PR9199.3 .A8 H3 1986
> 
> We'll send another email when your request is ready for pickup.
> 
> Request was placed:   Monday, May 22 2017 at 2:11pm
> Request will be canceled if it cannot be fulfilled before:   Tuesday, May 22 2018
> 
> You can see this request status online at http://requests.stanford.edu/hold_recalls/101871/status
> You can also see and change your requests at http://library.stanford.edu/myaccount
> 
> Questions about your request?
> Contact:
>  (650) 723-1493
>  greencirc@stanford.edu

### Page

> From: Stanford Libraries Requests <greencirc@stanford.edu>
> Subject: Request confirmed: "Education"
> Date: June 13, 2017 at 3:07:09 PM PDT
> To: <jvine@stanford.edu>
> 
> The following items are scheduled to be delivered to Green Library:
> Title:   Education
> Call number(s):
> -   370.5 .E1 V.2 1881/1882 
> -   370.5 .E1 V.1 1880/1881 
> 
> Estimated delivery:   Monday, Jun 15 2017, after 10:00am. 
> We'll send you another email when your request is ready for pickup.
> 
> Request was placed:   Tuesday, Jun 13 2017 at 3:07pm
> 
> You can see this request status online at http://requests.stanford.edu/pages/105683/status
> You can also see and change your requests at http://library.stanford.edu/myaccount
> 
> Questions about your request?
> Contact:
>  (650) 723-1493
>  greencirc@stanford.edu

### Scan

> From: Stanford Libraries Requests <scan-and-deliver@stanford.edu>
> Subject: Request confirmed: "Monitoring population dynamics among closely related organohalide respiring bacteria"
> Date: June 13, 2017 at 3:07:09 PM PDT
> To: <jvine@stanford.edu>
> 
> The following items have been queued for scanning:
> Title:   Monitoring population dynamics among closely related organohalide respiring bacteria
> Call number(s):
> -   3781 2016 M 
> 
> Title of article or chapter:
> Chapter 3
>
> Earliest delivery: Monday, Jun 19 2017, after 6:00pm
> We'll send you another email when your request is ready for download.
>
> Request was placed: Thursday, Jun 16 2017 at 5:07pm
> 
> You can see this request status online at http://requests.stanford.edu/pages/105683/status
> You can also see and change your requests at http://library.stanford.edu/myaccount
> 
> Questions about your request?
> Contact:
> (650) 723-1493
> scan-and-deliver@stanford.edu

### Mediated page

> From: Stanford Libraries Requests <specialcollections@stanford.edu>
> Subject: Request waiting for approval: "Canyon Cinema records, circa 1961-2008"
> Date: June 15, 2017 at 4:28:36 PM PDT
> To: <jvine@stanford.edu>
> 
> The following items are waiting for approval. Items are typically approved 1-3 days before your scheduled visit.
> Title:   Canyon Cinema records, circa 1961-2008
> Call number(s):
> -   M1681 BOX 20
> -   M1681 BOX 21
> -   M1681 BOX 22
> -   M1681 BOX 23
> -   M1681 BOX 24
> 
> Request was placed:   Friday, Jun 9 2017 at 2:11pm
> Planned date of visit:  Tuesday, Jun 27 2017
> 
> Check the status before you visit, at https://requests.stanford.edu/mediated_pages/105249/status
> 
> Questions about your request?
> Contact:
> (650) 725-1022
> specialcollections@stanford.edu

### Error (bad library ID)
Note, this is only relevant if they have a bad lib ID and enter an email... and Darsi may be able to make the system fall back to the email if the lib ID fails. 

> From: Stanford Libraries Requests <greencirc@stanford.edu>
> Subject: Attention needed: Your request could not be processed ("Annual report")
> Date: June 15, 2017 at 2:26:43 PM PDT
> To: <jvine@stanford.edu>
> 
> We were unable to process your request because the Stanford Library ID you entered (badidgoeshere) was not found in our system. 
> 
> Title:   Annual report
> Call number(s):
> -   HJ81.4 .A2149A 2012
> 
> Try your request again using just your name and email:   https://searchworks.stanford.edu/view/11474214
> 
> Request was placed:   Thursday, Jun 15 2017 at 2:11pm
> 
> You can see this request status online at https://requests.stanford.edu/pages/105936/status
> 
> Questions about your request?
> Contact:
>  (650) 723-1493
>  greencirc@stanford.edu

### Error (user is blocked)

> From: Stanford Libraries Requests <greencirc@stanford.edu>
> Subject: Attention needed: Your request could not be processed ("Annual report")
> Date: June 15, 2017 at 2:26:43 PM PDT
> To: <jvine@stanford.edu>
> 
> We were unable to process your request because your status is BLOCKED.
> 
> Title:   Annual report
> Call number(s):
> -   HJ81.4 .A2149A 2012
> 
> Request assistance by replying to this email, or check MyAccount (http://library.stanford.edu/myaccount) for more information.
> 
> Even though your status is blocked, you are eligible for Scan to PDF. You can request a single article or chapter, up to 50 pages.
> https://searchworks.stanford.edu/view/11474214
> 
> Request was placed:   Thursday, Jun 15 2017 at 2:11pm
> 
> You can see this request status online at https://requests.stanford.edu/pages/105936/status
> You can also see and change your requests at http://library.stanford.edu/myaccount
> 
> Questions about your request?
> Contact:
>  (650) 723-1493
>  greencirc@stanford.edu

**Comment by jkeck** [comment]
Just a few clarifying questions @jvine:

1. Do we want to turn this into an HTML email as opposed to plain text? Only thing that would indicate that is the bulleted list of call-numbers.  (It is easier to format line breaks and spacing in HTML FWIW)
1. We will be adding emails for request types that previously received no emails from us (`Scan` and `Hold/Recall`)?
1. In the cases where we say "We'll send you another email when..." is it okay that it's not the same email address that'll be sending follow up emails? (Perhaps just also trying to clarify that it's not the requests app that is sending these follow up emails)
1. The error emails only apply to non-mediated page requests?

**Comment by jvine** [comment]
1. Yes, I would like to do HTML email. If you see a technical downside, please let me know. 

2. Ah. This was unclear to me from the code. Are these processed in real time? If not, I would like the experience to be the same: Requests UI says "we got your request, we'll send you an email when it's processed" and then they get a confirmation email.

3. Could be generic/passive: "You'll receive another email when.."

4. I don't know...?

5. What approval emails? I thought we just told them to check the status page.

**Comment by saseestone** [comment]
I suspect that keeping the word "confirmed' in the subject line for hold, page and scan will continue to cause confusion for the user.  Can we use "Request received: ..." 

We've encountered many users that interpret "confirmed" as "received AND ready for you" (particularly for Media paging and hold requests - where the delivery time can be quick.) These users don't open the text of the email, but act on the subject line alone.

**Comment by jkeck** [comment]
Un-assigning myself as to not block anybody from picking this testing up.

**Comment by saseestone** [comment]
@camillevilla and @jvine I'm seeing one more problem with what appears in the "URLs" section for scan.  The user actually can't see or change their scan request at https://library.stanford.edu/myaccount.  The scan request is directed to ILLiad and we don't have any ILLiad data or functionality in My Account.  With the quick turn around time for these request types, I think its best to strike this line and just have the one URL:
"You can see this request status online at http://requests.stanford.edu/pages/105683/status"

I'm so sorry to have missed this in previous reviews.  I was focused on the text, and not focused enough on the URLs appearing in each type.

**Comment by saseestone** [comment]
All the other example emails look perfect!
