### ISSUE TITLE
Send Request Buttons spec consistently fails in Travis

### ISSUE THREAD

**Issue by camillevilla** [sul-dlss/sul-requests#722]
`sul-requests` builds often pass locally but fail on Travis on the feature test in `/spec/features/send_request_buttons_spec.rb:18`:

"disables the submit button (and adds a tooltip) when additional user validation is needed"

## Example error:

```
1) Send Request Buttons by anonymous user disables the submit button (and adds a tooltip) when additional user validation is needed
     Failure/Error: expect(page).not_to have_css('input[value="Send request"].disabled')
     ...
 TypeError: null is not an object (evaluating 'that.$element.off')

```

## Action:
- ~~Increase Capybara / Poltergeist waittime for this particular test~~

**Comment by jkeck** [comment]
@camillevilla I believe this is 🆗 now?  Feel free to close unless I'm missing something

**Comment by jkeck** [comment]
![sergio-romo-celebrates](https://user-images.githubusercontent.com/96776/27551545-b761e13c-5a58-11e7-94fe-a1f303a691f6.gif)
