### ISSUE TITLE
Use a different link for paid accounts confirmation emails

### ISSUE THREAD

**Issue by camillevilla** [sul-dlss/sul-requests#788]
Split off from #718 after consulting with @saseestone. 

Currently, users will see a link to check their account status at the bottom of a confirmation email for Hold, Page, Scan, and Errors u0003 (blocked) and u0004 (expired). Most users will be directed to [http://library.stanford.edu/myaccount](http://library.stanford.edu/myaccount). 

Paid account users should be directed to `library.stanford.edu/libraryaccount` instead.

**Comment by saseestone** [comment]
We have a landing page now: https://mylibrary.stanford.edu/
