### ISSUE TITLE
LibID requests - if validation not possible (#898), require name/email everywhere

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-requests#899]
Part of #895 

If server-side validation of the LibID proves to be too difficult, this is the fallback option:

For cases where the library ID is required to complete the request, where we currently display this when the user selects "I don't have a SUNet ID":

<img width="491" alt="request - required current" src="https://user-images.githubusercontent.com/6945691/67041697-0ee67880-f0db-11e9-87b6-22b3829c8337.png">

(Side note: It seems like a bug that there's an empty required field but the Send button is enabled...?)

**Add required Name and Email fields.**

<img width="522" alt="request - all fields required" src="https://user-images.githubusercontent.com/6945691/67044607-7a334900-f0e1-11e9-9b68-a547ff348d26.png">

Require all three values. If the user manages to enter an invalid LibID, libsys (@dlrueda heads-up) can place a hold for a pseudo-patron, and add the name & email to the comments. This will cause the request to be fulfilled and will allow staff to get it to the right person, BUT it requires manual intervention from staff, and does not provide the patron with automatic notification or MyAccount visibility.

**Comment by jkeck** [comment]
We added validation in #903 so I believe this can be closed.  Feel free to re-open if I've missed an actionable task here.
