### ISSUE TITLE
Add an eligibility overlay for mediated pages

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/sul-requests#971]
Overlay wording TBD.

* This may take the place of the off-campus IP check

**Comment by jvine** [comment]
<img width="613" alt="spec overlay" src="https://user-images.githubusercontent.com/6945691/83462022-ff742f80-a41e-11ea-9702-3c84e7839ea8.png">

```
<h1>Special Collections access</h1>
<p>This item can be viewed only in the Field Reading Room of Green Library.</p>
<h2 class="h3">Who can visit the Reading Room?</h2>
<p>Stanford faculty (including emeriti), graduate students, and post docs are eligible.</p>
<p>To maintain social distancing, the Reading Room will admit one researcher per table in 2-hour blocks.</p>
<h2 class="h3">How does it work?</h2>
<ol>
<li>Request the item.</li>
<li>When it's ready for use, we'll send you an email with instructions to schedule your visit.</li>
<li>Follow the required health and safety protocols and Special Collections policies when you arrive for your visit.</li>
</ol>
<a href="https://library.stanford.edu/spc/use-materials-field-room">Use of materials in the Field Room</a>
```

**Comment by jkeck** [comment]
Rumsey Map Center is also a mediated library (and would technically share this text as we've set it up).

Will we need this to be library specific now, or in the near future?

**Comment by jvine** [comment]
... we might need it to be library-specific. I couldn't figure out how to make this generic and still informative enough. At one point there was discussion that Rumsey material might be made available in the same location (Field room) but I'm sure that's not a long-term solution. @saseestone any insight here?

**Comment by jkeck** [comment]
Okay, I'll think a bit about how we can do that (to at least give us the seam so that the bar is lower when we do need to turn on another mediated location)

**Comment by jvine** [comment]
... we might need it to be library-specific. I couldn't figure out how to make this generic and still informative enough. At one point there was discussion that Rumsey material might be made available in the same location (Field room) but I'm sure that's not a long-term solution. @saseestone any insight here?
