### ISSUE TITLE
Update "success" page wording / links

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/sul-requests#972]
This is the page that the user gets to right after submitting the request (before symphony has responded).  We need to update that wording and remove links to the status page (as we want status communications to happen via email).

Wording TBD

**Comment by jvine** [comment]
As long as #794 is possible, set aside any additional wording changes here - just remove the link to the status page.

The eligibility group may change to eliminate the gap in stanford:stanford (people who pass that test but aren't actually eligible); or the actual effect on users may be different than we imagine.

**Comment by jkeck** [comment]
Do we want to replace the link (or add a link elsewhere) w/ a link to MyAccount or wording about going to MyAccount?  Or will the email contain all that info so no need to have it here?

**Comment by jvine** [comment]
The email will contain all the info. Going to MyAccount directly from the request will not always be successful, since a request might have been rejected, or not display there yet. I'd rather it get to the next stage (response from Symphony) before we direct them to my account.
