### ISSUE TITLE
Update various email wording / links

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/sul-requests#973]
Some of this may be accomplished in #968

Wording TBD

**Comment by jvine** [comment]
## Request approval messages

approval_status_for_holdrecall.html.erb
approval_status_for_page.html.erb
approval_status_for_scan.html.erb

Structure is:
1. new covid-related message
2. info about the item
3. questions about your request?

### 1. Replace initial sentence

> We'll email you again when your request is ready for pickup.

with

> We've received your request. We'll email you again when it's ready for pickup.
>
> At that time, you'll be able to schedule a pickup appointment in [My Library Account](url). 
>
> If you haven't already, complete [COVID-19 Hygiene Best Practices, EHS-2470-WEB](https://starsexpress.stanford.edu/index.html?ref=LM_SS_LEARNING.LM_BROWSE_LEARNER.GBL&amp;type=COURSE&amp;code=EHS-2470) in preparation.

### 2. Remove/hide link to status page (and MyAcct)
```
<p>
      You can see this request status online at <%= link_to('requests.stanford.edu', @status_url) %><br/>
      You can also see and change your requests at <%= link_to('https://library.stanford.edu/myaccount', 'https://library.stanford.edu/myaccount') %>
    </p>
```

## Error messages

**approval_status_for_u002.html.erb**

- Remove 
```
    <p>
      Try your request again using just your name and email: <%= link_to("#{Settings.searchworks_link}/#{@request.item_id}", "#{Settings.searchworks_link}/#{@request.item_id}") %>
    </p>
```

- Add (to be parallel to 003 and 004)
```
  <p>
      Request assistance by replying to this email, or check My Library Account (<%= link_to('https://library.stanford.edu/myaccount', 'https://library.stanford.edu/myaccount') %>) for more information.
    </p>
```

**approval_status_for_u003.html.erb**

- <% if @request.scannable? %> - assuming this section will not appear while scan service is turned off? do we need to explicitly suppress it?

No other changes to this email.

**approval_status_for_u004.html.erb**

- Remove (I don't think this needs to be present at all in this email). 
```
    <p>
      You can see this request status online at <%= link_to('requests.stanford.edu', @status_url) %><br/>
      You can also see and change your requests at <%= link_to('https://library.stanford.edu/myaccount', 'https://library.stanford.edu/myaccount') %>
    </p>
```

**Comment by jvine** [comment]
Spec request email still WIP.
