### ISSUE TITLE
Capture for stanford:stanford priv users and display an error if they...

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/sul-requests#974]
...they do not have the appropriate privs.

Wording of error message TBD

This is an attempt to prevent ineligible users from making several requests before they check their email to determine that the requests are failing due to their Stanford privs.

We don't have access to `stanford:stanford` but all of the following affiliations should effectively give us that same set of users according to https://uit.stanford.edu/service/registry/data-affiliation-types-qualifiers

```
stanford:student
stanford:student:onleave
stanford:student:postdoc
stanford:faculty
stanford:faculty:onleave
stanford:faculty:emeritus
stanford:faculty:otherteaching
stanford:faculty:affiliate
stanford:faculty:slac
stanford:staff
stanford:staff:academic
stanford:staff:onleave
stanford:staff:emeritus
stanford:staff:otherteaching
```

**Comment by jvine** [comment]
<img width="613" alt="stanford-stanford fail" src="https://user-images.githubusercontent.com/6945691/83462506-33038980-a420-11ea-849f-48fad7a13aa5.png">

```
<h1>Sorry, we can't fulfill your request</h1>
<p>Your SUNet ID indicates that you do not belong to any of the groups eligible for this service:</p>
<ul><li>faculty</li>
<li>emeritus faculty</li>
<li>students</li>
<li>staff</li>
<li>academic staff</li>
<li>fellows</li>
<li>post-doctoral students</li>
</ul>
<p>... with a current Stanford University card.</p>
<p>If you believe this is an error, contact <a href="mailto:greencirc@stanford.edu">greencirc@stanford.edu</a>.</p>
```

**Comment by jkeck** [comment]
The above list does not include `stanford:affiliate:fellow` (which I'm assuming we want to allow to page), but that is not `stanford:stanford` according to the page linked above.  @saseestone I can add fellow, but would you mind taking a quick look over that page and just sanity checking me on any others I may have missed (when you have a chance, of course)?

**Comment by jkeck** [comment]
Also, should we show the user this notice or something else if they happen to already be authenticated? It is unlikely since they would have most likely authenticated through making a request and determined they were not eligible, but technically possible I suppose.  I don't think we need to block anything to answer this (as they will eventually see the eligibility notification)

**Comment by jvine** [comment]
I think we should explicitly show it when they click the Send button, even if they have previously authenticated.

**Comment by jkeck** [comment]
I added fellows. I'll mark the PR ready for review so we can get the code out and we can refine the list later if needed.

**Comment by saseestone** [comment]
Just checked the list.  Thanks or adding stanfod:affiliate:fellow.  Also add: 
stanford:affiliate:visitscholarvs
stanford:affiliate:visitscholarvt
