### ISSUE TITLE
Wording changes for Spec/mediated page requests

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-requests#993]
### Eligibility overlay

- [x] Under Who can visit the Reading Room?

> Professors (including emeriti), post-docs, graduate students, fellows, and Stanford Visiting Scholars with a current Stanford ID card.
> To maintain social distancing, the Reading Room will admit one researcher per table in 2-hour blocks.

- [x] Change link text from `Use of materials in the Field Room` to `Special Collections policies`

### Form

- [x] Change "Reading Room access" text to `When the items have been approved and are ready for use, you'll receive an email with a link to schedule an appointment for access to the Reading Room.`

### Failure

- [x] Replace text:

> It appears that you do not belong to any of the groups eligible for this service:
> - professors (including emeriti)
> - post-docs
> - graduate students
> - fellows
> - Stanford Visiting Scholars
> ... with a current Stanford University card.
>
> If you believe this is an error, contact greencirc@stanford.edu.

**Comment by saseestone** [comment]
On the Failure, should we have the contact be specialcollections@stanford.edu?
